SELECT 
    GER.CODVEND AS CODIGO_GERENTE_GOL,
    GER.APELIDO AS NOME_GERENTE_GOL,
    GER.NOMEVEND AS NOME_COMPLETO_GERENTE_GOL,
    GER.ATIVO AS STATUS_GERENTE_GOL,
    
    COUNT(DISTINCT SUP.CODVEND) AS TOTAL_SUPERVISORES_EQUIPE,
    COUNT(DISTINCT VEN.CODVEND) AS TOTAL_VENDEDORES_EQUIPE,
    COUNT(CAB.NUNOTA) AS TOTAL_NOTAS_PERIODO,
    SUM(CAB.VLRNOTA) AS VALOR_TOTAL_PERIODO,
    ROUND(AVG(CAB.VLRNOTA), 2) AS VALOR_MEDIO_NOTA,
    MIN(CAB.DTNEG) AS PRIMEIRA_VENDA,
    MAX(CAB.DTNEG) AS ULTIMA_VENDA,
    
    COUNT(CASE WHEN CAB.TIPMOV = 'V' THEN 1 END) AS TOTAL_VENDAS,
    COUNT(CASE WHEN CAB.TIPMOV = 'P' THEN 1 END) AS TOTAL_PEDIDOS,
    SUM(CASE WHEN CAB.TIPMOV = 'V' THEN CAB.VLRNOTA ELSE 0 END) AS VALOR_VENDAS,
    SUM(CASE WHEN CAB.TIPMOV = 'P' THEN CAB.VLRNOTA ELSE 0 END) AS VALOR_PEDIDOS,
    
    COUNT(DISTINCT CAB.CODPARC) AS TOTAL_CLIENTES_ATENDIDOS,
    COUNT(DISTINCT CAB.CODEMP) AS TOTAL_EMPRESAS,
    COUNT(DISTINCT VEN.CODVEND) AS TOTAL_VENDEDORES_ATIVOS

FROM TGFCAB CAB
INNER JOIN TGFVEN VEN ON VEN.CODVEND = CAB.CODVEND AND VEN.ATIVO = 'S'
INNER JOIN TGFVEN GER ON GER.CODVEND = VEN.CODGER AND GER.ATIVO = 'S'
LEFT JOIN TGFVEN SUP ON SUP.CODVEND = VEN.AD_SUPERVISOR AND SUP.ATIVO = 'S'
INNER JOIN TGFPAR PAR ON PAR.CODPARC = CAB.CODPARC AND PAR.ATIVO = 'S'
INNER JOIN TSIEMP EMP ON EMP.CODEMP = CAB.CODEMP AND EMP.ATIVO = 'S'
INNER JOIN TGFTOP TOP ON TOP.CODTIPOPER = CAB.CODTIPOPER AND TOP.DHALTER = CAB.DHTIPOPER

WHERE CAB.STATUSNOTA = 'L'
  AND CAB.DTNEG BETWEEN :DATA_INICIO AND :DATA_FIM
  AND (CAB.CODEMP = :P_CODEMP OR :P_CODEMP IS NULL)
  AND (GER.CODVEND = :P_CODGERENTE_GOL OR :P_CODGERENTE_GOL IS NULL)
  AND (TOP.TIPMOV IN ('V', 'P') OR :P_TIPMOV = 'T')

GROUP BY 
    GER.CODVEND,
    GER.APELIDO,
    GER.NOMEVEND,
    GER.ATIVO

ORDER BY 
    VALOR_TOTAL_PERIODO DESC,
    GER.APELIDO



