SELECT 
    GER.CODVEND AS CODIGO_GERENTE,
    GER.APELIDO AS NOME_GERENTE,
    GER.NOMEVEND AS NOME_COMPLETO_GERENTE,
    
    COUNT(DISTINCT VEN.CODVEND) AS TOTAL_VENDEDORES_EQUIPE,
    COUNT(CAB.NUNOTA) AS TOTAL_NOTAS_PERIODO,
    SUM(CAB.VLRNOTA) AS VALOR_TOTAL_PERIODO,
    AVG(CAB.VLRNOTA) AS VALOR_MEDIO_NOTA,
    MIN(CAB.DTNEG) AS PRIMEIRA_VENDA,
    MAX(CAB.DTNEG) AS ULTIMA_VENDA,
    
    COUNT(CASE WHEN CAB.TIPMOV = 'V' THEN 1 END) AS TOTAL_VENDAS,
    COUNT(CASE WHEN CAB.TIPMOV = 'P' THEN 1 END) AS TOTAL_PEDIDOS,
    SUM(CASE WHEN CAB.TIPMOV = 'V' THEN CAB.VLRNOTA ELSE 0 END) AS VALOR_VENDAS,
    SUM(CASE WHEN CAB.TIPMOV = 'P' THEN CAB.VLRNOTA ELSE 0 END) AS VALOR_PEDIDOS,
    
    COUNT(DISTINCT CAB.CODPARC) AS TOTAL_CLIENTES_ATENDIDOS,
    COUNT(DISTINCT CAB.CODEMP) AS TOTAL_EMPRESAS

FROM TGFCAB CAB
INNER JOIN TGFVEN VEN ON VEN.CODVEND = CAB.CODVEND AND VEN.ATIVO = 'S'
INNER JOIN TGFVEN GER ON GER.CODVEND = VEN.CODGER AND GER.ATIVO = 'S'
INNER JOIN TGFPAR PAR ON PAR.CODPARC = CAB.CODPARC AND PAR.ATIVO = 'S'
INNER JOIN TSIEMP EMP ON EMP.CODEMP = CAB.CODEMP AND EMP.ATIVO = 'S'
INNER JOIN TGFTOP TOP ON TOP.CODTIPOPER = CAB.CODTIPOPER AND TOP.DHALTER = CAB.DHTIPOPER

WHERE CAB.STATUSNOTA = 'L'
  AND CAB.DTNEG BETWEEN :DATA_INICIO AND :DATA_FIM
  AND (CAB.CODEMP = :P_CODEMP OR :P_CODEMP IS NULL)
  AND (GER.CODVEND = :P_CODGERENTE OR :P_CODGERENTE IS NULL)
  AND (TOP.TIPMOV IN ('V', 'P') OR :P_TIPMOV = 'T')

GROUP BY 
    GER.CODVEND,
    GER.APELIDO,
    GER.NOMEVEND

ORDER BY 
    VALOR_TOTAL_PERIODO DESC,
    GER.APELIDO



