SELECT 
    GER.CODVEND AS CODIGO_GERENTE_GOL,
    GER.APELIDO AS NOME_GERENTE_GOL,
    GER.NOMEVEND AS NOME_COMPLETO_GERENTE_GOL,
    GER.ATIVO AS STATUS_GERENTE_GOL,
    
    SUP.CODVEND AS CODIGO_SUPERVISOR,
    SUP.APELIDO AS NOME_SUPERVISOR,
    SUP.NOMEVEND AS NOME_COMPLETO_SUPERVISOR,
    SUP.ATIVO AS STATUS_SUPERVISOR,
    
    VEN.CODVEND AS CODIGO_VENDEDOR,
    VEN.APELIDO AS NOME_VENDEDOR,
    VEN.NOMEVEND AS NOME_COMPLETO_VENDEDOR,
    VEN.ATIVO AS STATUS_VENDEDOR,
    VEN.AD_SUPERVISOR AS CODIGO_SUPERVISOR_VENDEDOR,
    
    CAB.NUNOTA,
    CAB.NUMNOTA,
    CAB.DTNEG AS DATA_NEGOCIACAO,
    CAB.DTENTSAI AS DATA_ENTREGA,
    CAB.VLRNOTA AS VALOR_NOTA,
    CAB.PESO AS PESO_TOTAL,
    CAB.CODPARC AS CODIGO_CLIENTE,
    PAR.RAZAOSOCIAL AS NOME_CLIENTE,
    PAR.CGC_CPF AS CNPJ_CPF_CLIENTE,
    PAR.TELEFONE AS TELEFONE_CLIENTE,
    PAR.EMAIL AS EMAIL_CLIENTE,
    
    EMP.CODEMP AS CODIGO_EMPRESA,
    EMP.RAZAOSOCIAL AS NOME_EMPRESA,
    
    TOP.CODTIPOPER,
    TOP.DESCROPER AS DESCRICAO_OPERACAO,
    TOP.TIPMOV AS TIPO_MOVIMENTO,
    
    CASE 
        WHEN CAB.TIPMOV = 'V' THEN 'Venda'
        WHEN CAB.TIPMOV = 'P' THEN 'Pedido'
        WHEN CAB.TIPMOV = 'C' THEN 'Compra'
        WHEN CAB.TIPMOV = 'E' THEN 'Devolução'
        WHEN CAB.TIPMOV = 'T' THEN 'Transferência'
        ELSE 'Outro'
    END AS TIPO_DOCUMENTO,
    
    CAB.STATUSNOTA,
    CASE 
        WHEN CAB.STATUSNOTA = 'L' THEN 'Liberada'
        WHEN CAB.STATUSNOTA = 'G' THEN 'Gerada'
        WHEN CAB.STATUSNOTA = 'C' THEN 'Cancelada'
        WHEN CAB.STATUSNOTA = 'P' THEN 'Pendente'
        ELSE 'Outro'
    END AS STATUS_DESCRICAO,
    
    COUNT(DISTINCT VEN.CODVEND) OVER (PARTITION BY GER.CODVEND) AS TOTAL_VENDEDORES_EQUIPE_GOL,
    COUNT(CAB.NUNOTA) OVER (PARTITION BY GER.CODVEND, TRUNC(CAB.DTNEG, 'MM')) AS TOTAL_NOTAS_MES_GERENTE_GOL,
    SUM(CAB.VLRNOTA) OVER (PARTITION BY GER.CODVEND, TRUNC(CAB.DTNEG, 'MM')) AS VALOR_TOTAL_MES_GERENTE_GOL,
    COUNT(CAB.NUNOTA) OVER (PARTITION BY SUP.CODVEND, TRUNC(CAB.DTNEG, 'MM')) AS TOTAL_NOTAS_MES_SUPERVISOR,
    SUM(CAB.VLRNOTA) OVER (PARTITION BY SUP.CODVEND, TRUNC(CAB.DTNEG, 'MM')) AS VALOR_TOTAL_MES_SUPERVISOR,
    COUNT(CAB.NUNOTA) OVER (PARTITION BY VEN.CODVEND, TRUNC(CAB.DTNEG, 'MM')) AS TOTAL_NOTAS_MES_VENDEDOR,
    SUM(CAB.VLRNOTA) OVER (PARTITION BY VEN.CODVEND, TRUNC(CAB.DTNEG, 'MM')) AS VALOR_TOTAL_MES_VENDEDOR,
    
    ROUND(AVG(CAB.VLRNOTA) OVER (PARTITION BY GER.CODVEND, TRUNC(CAB.DTNEG, 'MM')), 2) AS VALOR_MEDIO_NOTA_GERENTE_GOL,
    ROUND(AVG(CAB.VLRNOTA) OVER (PARTITION BY VEN.CODVEND, TRUNC(CAB.DTNEG, 'MM')), 2) AS VALOR_MEDIO_NOTA_VENDEDOR

FROM TGFCAB CAB
INNER JOIN TGFVEN VEN ON VEN.CODVEND = CAB.CODVEND AND VEN.ATIVO = 'S'
INNER JOIN TGFVEN GER ON GER.CODVEND = VEN.CODGER AND GER.ATIVO = 'S'
LEFT JOIN TGFVEN SUP ON SUP.CODVEND = VEN.AD_SUPERVISOR AND SUP.ATIVO = 'S'
INNER JOIN TGFPAR PAR ON PAR.CODPARC = CAB.CODPARC AND PAR.ATIVO = 'S'
INNER JOIN TSIEMP EMP ON EMP.CODEMP = CAB.CODEMP AND EMP.ATIVO = 'S'
INNER JOIN TGFTOP TOP ON TOP.CODTIPOPER = CAB.CODTIPOPER AND TOP.DHALTER = CAB.DHTIPOPER

WHERE CAB.STATUSNOTA = 'L'
  AND CAB.DTNEG BETWEEN :DATA_INICIO AND :DATA_FIM
  AND (CAB.CODEMP = :P_CODEMP OR :P_CODEMP IS NULL)
  AND (GER.CODVEND = :P_CODGERENTE_GOL OR :P_CODGERENTE_GOL IS NULL)
  AND (SUP.CODVEND = :P_CODSUPERVISOR OR :P_CODSUPERVISOR IS NULL)
  AND (VEN.CODVEND = :P_CODVENDEDOR OR :P_CODVENDEDOR IS NULL)
  AND (CAB.TIPMOV = :P_TIPMOV OR :P_TIPMOV = 'T')
  AND (TOP.TIPMOV IN ('V', 'P') OR :P_TIPMOV = 'T')

ORDER BY 
    GER.APELIDO,
    SUP.APELIDO,
    VEN.APELIDO,
    CAB.DTNEG DESC,
    CAB.NUMNOTA DESC



