SELECT 
 DISTINCT RPE.NUPESQ,PER.CODPERG, PER.DESCRPERG,RES.DESCRRESP, RES.CODRESP,
 CASE WHEN (SELECT RES2.AD_MENSAL FROM TPQRES RES2
  WHERE RES2.CODPERG = PER.CODPERG
 AND UPPER(RES2.DESCRRESP) = 'SIM'
 )  IS NULL
 THEN 
     (SELECT RES2.AD_JIVA FROM TPQRES RES2
      WHERE RES2.CODPERG = PER.CODPERG
      
     AND UPPER(RES2.DESCRRESP) = 'SIM')
 ELSE 
    (SELECT RES2.AD_MENSAL FROM TPQRES RES2
      WHERE RES2.CODPERG = PER.CODPERG
     AND UPPER(RES2.DESCRRESP) = 'SIM'
     ) END VALOR,
 CASE WHEN (SELECT RES2.AD_MENSAL FROM TPQRES RES2
  WHERE RES2.CODPERG = PER.CODPERG
 AND UPPER(RES2.DESCRRESP) = 'SIM'
 )  IS NULL
 THEN  'Y'
 ELSE 'N' END CALCULAR_PORCENTAGEM
 
FROM  TCSOSE OS
INNER JOIN TCSFXO FXO ON FXO.NUMOS = OS.NUMOS
INNER JOIN  TCSPOS POS ON POS.NUMOS = FXO.NUMOS
INNER JOIN TPQPES PES ON PES.NUPESQ = POS.NUPESQ
INNER JOIN  TPQRPE RPE ON RPE.NUPESQ = PES.NUPESQ
INNER JOIN TCSQXF QXF ON QXF.CODFLD = FXO.CODFLD
INNER JOIN TPQQUE QUE ON QUE.CODQUEST = QXF.CODQUEST
INNER JOIN TPQPER PER ON PER.CODQUEST = QUE.CODQUEST AND  PER.CODPERG = RPE.CODPERG 
INNER JOIN TPQRES RES ON RES.CODPERG = RPE.CODPERG AND RES.CODRESP = RPE.CODRESP
INNER JOIN AD_TCSPROC PROC ON PROC.NUPROC = PER.CODPERG
INNER JOIN  TCSPAP PR ON PR.CODPAP = OS.CODPAP
INNER JOIN TCSCON C ON C.CODPARC =  PR.CODPARC
WHERE OS.NUMOS = :NUMOS
AND FXO.CODFLD = :CODFLD
AND UPPER(RES.DESCRRESP) LIKE '%CONTRATADO'
AND (SELECT COUNT(*) FROM TPQRPE RPE2 
INNER JOIN TPQRES RES ON RES.CODPERG = RPE2.CODPERG AND  RES.CODRESP =  RPE2.CODRESP 
WHERE RPE2.CODPERG = PER.CODPERG
AND RPE2.NUPESQ = RPE.NUPESQ
AND UPPER(RES.DESCRRESP) = 'SIM') = 1
ORDER BY PER.DESCRPERG

