SELECT  DISTINCT  PER.CODPERG, PER.DESCRPERG, PER.CODPERG, RES.DESCRRESP, RES.CODRESP, RES.AD_MENSAL,PES.NUPESQ
FROM TCSOSE SO 
INNER JOIN TCSFXO FXO ON FXO.NUMOS = SO.NUMOS
INNER JOIN TCSQXF QXF ON QXF.CODFLD = FXO.CODFLD
INNER JOIN TPQQUE Q ON  Q.CODQUEST = QXF.CODQUEST
INNER JOIN TCSPOS POS ON POS.CODFLD =  FXO.CODFLD AND SO.NUMOS = POS.NUMOS
INNER JOIN TPQPES PES ON PES.NUPESQ = POS.NUPESQ
INNER JOIN TPQRPE RPE ON RPE.NUPESQ  = PES.NUPESQ
INNER JOIN TPQPER PER ON PER.CODPERG = RPE.CODPERG AND PER.CODQUEST = Q.CODQUEST
INNER JOIN TPQRES RES ON RES.CODPERG = PER.CODPERG AND RES.CODRESP = RPE.CODRESP
WHERE POS.NUMOS = :NUMOS
AND FXO.CODFLD = 30
AND RES.AD_MENSAL IS NOT NULL
AND RES.AD_JIVA IS NULL
AND (SELECT COUNT(*) FROM TPQDPD PD
      INNER JOIN TPQRPE RPE2 ON  RPE2.CODPERG = PD.CODPERGMESTRE
      INNER JOIN TPQRES R2 ON R2.CODPERG =  RPE2.CODPERG AND R2.CODRESP = RPE2.CODRESP
      WHERE PD.CODPERGDEP = PER.CODPERG
      AND UPPER(R2.DESCRRESP) = 'SIM'
      ) > 0
order by  PER.DESCRPERG desc