SELECT  DISTINCT    CONCAT(CONCAT(CONCAT(CONCAT('A resposta: ', RES.DESCRRESP ), ' da pergunta ' ), COALESCE(SUBSTR(PER.DESCRPERG, 1 ,  INSTR(PER.DESCRPERG,CHR(10) , 1, 1)), PER.DESCRPERG  )  ), ' só pode ser usada no tipo Venda Base - NP') "RESP"
FROM TCSOSE SO 
INNER JOIN TCSFXO FXO ON FXO.NUMOS = SO.NUMOS
INNER JOIN TCSQXF QXF ON QXF.CODFLD = FXO.CODFLD
INNER JOIN TPQQUE Q ON  Q.CODQUEST = QXF.CODQUEST
INNER JOIN TCSPOS POS ON POS.CODFLD =  FXO.CODFLD AND SO.NUMOS = POS.NUMOS
INNER JOIN TPQPES PES ON PES.NUPESQ = POS.NUPESQ
INNER JOIN TPQRPE RPE ON RPE.NUPESQ  = PES.NUPESQ
INNER JOIN TPQPER PER ON PER.CODPERG = RPE.CODPERG AND PER.CODQUEST = Q.CODQUEST
INNER JOIN TPQRES RES ON RES.CODPERG = PER.CODPERG AND RES.CODRESP = RPE.CODRESP
WHERE POS.NUMOS = :NUMOS
AND FXO.CODFLD = :CODFLD
AND RES.AD_EXCLUSIVABASE LIKE '%S%'