SELECT 
 DISTINCT PER.CODPERG, PER.DESCRPERG,
(SELECT RES2.AD_JIVA FROM TPQRPE RPE2
INNER JOIN TPQRES RES2 ON (RES2.CODPERG = RPE2.CODPERG AND RES2.CODRESP = RPE2.CODRESP)
WHERE RPE2.NUPESQ = RPE.NUPESQ
AND RPE2.CODPERG = RPE.CODPERG 
AND UPPER(RES2.DESCRRESP) = 'SIM') AS VALOR
FROM  TCSOSE OS
INNER JOIN TCSFXO FXO ON FXO.NUMOS = OS.NUMOS
INNER JOIN  TCSPOS POS ON POS.NUMOS = FXO.NUMOS
INNER JOIN TPQPES PES ON PES.NUPESQ = POS.NUPESQ
INNER JOIN  TPQRPE RPE ON RPE.NUPESQ = PES.NUPESQ
INNER JOIN TCSQXF QXF ON QXF.CODFLD = FXO.CODFLD
INNER JOIN TPQQUE QUE ON QUE.CODQUEST = QXF.CODQUEST
INNER JOIN TPQPER PER ON PER.CODQUEST = QUE.CODQUEST AND  PER.CODPERG = RPE.CODPERG 
INNER JOIN TPQRES RES ON RES.CODPERG = RPE.CODPERG AND RES.CODRESP = RPE.CODRESP
INNER JOIN AD_TCSPROC PROC ON PROC.NUPROC = PER.CODPERG
INNER JOIN  TCSPAP PR ON PR.CODPAP = OS.CODPAP
INNER JOIN TCSCON C ON C.CODPARC =  PR.CODPARC
WHERE OS.NUMOS = :NUMOS
AND FXO.CODFLD = :CODFLD
AND UPPER(RES.DESCRRESP) LIKE '%CONTRATADO'
AND (SELECT COUNT(RPE2.CODPERG) FROM TPQRPE RPE2
INNER JOIN TPQRES RES2 ON (RES2.CODPERG = RPE2.CODPERG AND RES2.CODRESP = RPE2.CODRESP)
WHERE RPE2.NUPESQ = RPE.NUPESQ
AND RPE2.CODPERG = RPE.CODPERG 
AND UPPER(RES2.DESCRRESP) = 'SIM') = 1
--AND ( ( C.AD_TIPOVENDA  = 'VP' ) OR ( C.AD_TIPOVENDA  = 'VU'  AND PER.AD_DEFAULTUSU  = 'NAO'  )) 
AND ( ( C.AD_TIPOVENDA  = 'VP' ) OR ( C.AD_TIPOVENDA  = 'VU'  )) 

