SELECT  DISTINCT
RES.DESCRRESP, RES.CODRESP
FROM TCSOSE SO
INNER JOIN  TCSPAP PR ON PR.CODPAP = SO.CODPAP
INNER JOIN TCSFXO FXO ON FXO.NUMOS = SO.NUMOS
INNER JOIN TCSQXF QXF ON QXF.CODFLD = FXO.CODFLD
INNER JOIN TPQQUE Q ON  Q.CODQUEST = QXF.CODQUEST
INNER JOIN TCSPOS POS ON POS.CODFLD =  FXO.CODFLD AND SO.NUMOS = POS.NUMOS
 INNER JOIN TPQPES PES ON PES.NUPESQ = POS.NUPESQ
 INNER JOIN TPQRPE RPE ON RPE.NUPESQ  = PES.NUPESQ
 INNER JOIN TPQPER PER ON PER.CODPERG = RPE.CODPERG AND PER.CODQUEST = Q.CODQUEST
 INNER JOIN TPQRES RES ON RES.CODPERG = PER.CODPERG AND RES.CODRESP = RPE.CODRESP
WHERE SO.NUMOS = :NUMOS
AND FXO.CODFLD = :CODFLD
AND Q.DESCRQUEST = 'DADOS BÁSICOS'
AND RPE.CODPERG = :CODPERG
AND RPE.CODRESP  = :CODSAAS