CREATE OR REPLACE PROCEDURE SANKHYA.PROC_ANALISE_COMPRAS_ATU_NOVA
IS
/*====================================================================================
   OBJETO:  PROCEDURE PERSONALIZADA
   AUTOR:   LEANDRO MARCOS MOREIRA (leandromarcosmoreira@gmail.com) 34 99120-4642
   INTUITO: AUTOMATIZAR TAREFAS DE IMPORTAR DADOS PARA DASHBOARD ANÁLISE DE COMPRAS
            O RESULTADO É A SUBSTITUIÇÃO DO PROGRAMA DE COMPRAS.
   ÚLTIMA ATUALIZAÇÃO: 10/08/2018 AS 12:00
   ==================================================================================*/
   
   P_COUNT INT := 0;
   P_CODEMP NUMBER;
   P_CODPROD INT;
   P_CONTROLE VARCHAR2(10);
   P_ESTATUAL NUMBER;
   P_SOMPEDPEN NUMBER;
   P_ATUALIZACAO VARCHAR2(20);
   
   CURSOR AnaliseCompras IS
   SELECT DISTINCT CAB.CODEMP AS PK_CODEMP
                 , ITE.CODPROD
                 , ITE.CONTROLE
                 , NVL((SELECT SUM(EST.ESTOQUE) 
                          FROM TGFEST EST 
                         WHERE EST.CODEMP = CAB.CODEMP
                           AND EST.CODLOCAL IN (1, 3, 5) 
                           AND EST.CODPROD = ITE.CODPROD 
                           AND EST.CONTROLE = ITE.CONTROLE),0) AS ESTATUAL
                 , SUM(CASE WHEN ((CAB.TIPMOV = 'O' AND ITE.PENDENTE = 'S') OR (CAB.TIPMOV = 'C' AND CAB.STATUSNOTA = 'A')) AND  CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -12)) AND TRUNC (SYSDATE)
                            THEN ITE.QTDNEG - ITE.QTDENTREGUE ELSE 0 END) AS SOMPEDPEN
     FROM TGFITE ITE
     INNER JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA 
                          AND ((CAB.TIPMOV = 'O' AND ITE.PENDENTE = 'S') OR (CAB.TIPMOV = 'C' AND CAB.STATUSNOTA = 'A')) AND  CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -12)) AND TRUNC (SYSDATE)
   INNER JOIN TGFPRO PRO ON PRO.CODPROD = ITE.CODPROD 
                        AND PRO.CODGRUPOPROD BETWEEN 10000000 AND 30000000 
                        AND (
                              (PRO.TIPCONTEST = 'S' AND ITE.CONTROLE <> ' ') 
                           OR (PRO.TIPCONTEST = 'N' AND ITE.CONTROLE = ' ')
                            )
  WHERE ITE.CODEMP IN (1, 31, 41, 51)
    AND ITE.CODLOCALORIG IN (1, 3, 5)
    AND PRO.ATIVO = 'S'
GROUP BY ITE.CODPROD
       , ITE.CONTROLE
       , CAB.CODEMP;

BEGIN

  OPEN AnaliseCompras;
  
  LOOP
  
  FETCH AnaliseCompras INTO
        P_CODEMP
      , P_CODPROD
      , P_CONTROLE
      , P_ESTATUAL
      , P_SOMPEDPEN;

    UPDATE ANALISE_COMPRAS_NOVA COM 
       SET (COM.ESTATUAL
          , COM.SOMPEDPEN) =
   (SELECT P_ESTATUAL
         , P_SOMPEDPEN
      FROM DUAL)
     WHERE COM.CODPROD = P_CODPROD
       AND COM.CONTROLE = P_CONTROLE
       AND COM.PK_CODEMP = P_CODEMP;
  
   EXIT WHEN AnaliseCompras%NOTFOUND;
   END LOOP;

CLOSE AnaliseCompras;

UPDATE ANALISE_COMPRAS_NOVA UP
   SET ESTATUAL =
(SELECT SUM(EST.ESTOQUE)
   FROM TGFEST EST
  WHERE EST.CODLOCAL IN (1, 3, 5)
    AND EST.CODEMP = UP.PK_CODEMP
    AND EST.CODPROD = UP.CODPROD
    AND EST.CONTROLE = UP.CONTROLE);

UPDATE ANALISE_COMPRAS_NOVA UP
   SET ESTATUAL = 0
 WHERE UP.ESTATUAL IS NULL;
 
UPDATE ANALISE_COMPRAS_NOVA UP
   SET (ESTATUAL, ESTMIN, MEDIAPVEND, AD_MESESTMAX, SOMPEDPEN, ESTMAX, ESTEXC) =
(SELECT ESTATUAL
      , ESTMIN
      , MEDIAPVEND
      , AD_MESESTMAX
      , SOMPEDPEN
      , ESTMAX
      , ESTEXC
FROM
   (SELECT PK_CODEMP
     , CODPROD
     , CONTROLE
     , SUM(UNIAO.ESTATUAL) AS ESTATUAL
     , SUM(UNIAO.ESTMIN) AS ESTMIN
     , SUM(UNIAO.MEDIAPVEND) AS MEDIAPVEND
     , SUM(UNIAO.AD_MESESTMAX) AS AD_MESESTMAX
     , SUM(UNIAO.SOMPEDPEN) AS SOMPEDPEN
     , SUM(UNIAO.ESTMAX) AS ESTMAX
     , SUM(UNIAO.ESTEXC) AS ESTEXC
  FROM
(SELECT COM.PK_CODEMP
     , PAL.CODPROD
     , NVL(COM.CONTROLE, ' ') AS CONTROLE
     , NVL(COM.ESTATUAL, 0) AS ESTATUAL
     , NVL(COM.ESTMIN, 0) AS ESTMIN
     , NVL(COM.MEDIAPVEND, 0) AS MEDIAPVEND
     , NVL(COM.AD_MESESTMAX, 0) AS AD_MESESTMAX
     , NVL(COM.SOMPEDPEN, 0) AS SOMPEDPEN
     , NVL(COM.ESTMAX, 0) AS ESTMAX
     , NVL(COM.ESTEXC, 0) AS ESTEXC
 FROM ANALISE_COMPRAS_NOVA COM
    , TGFPAL PAL
WHERE COM.CODPROD = PAL.CODPRODALT
UNION
SELECT COM.PK_CODEMP
     , PAL.CODPROD
     , NVL(COM.CONTROLE, ' ') AS CONTROLE
     , NVL(COM.ESTATUAL, 0) AS ESTATUAL
     , NVL(COM.ESTMIN, 0) AS ESTMIN
     , NVL(COM.MEDIAPVEND, 0) AS MEDIAPVEND
     , NVL(COM.AD_MESESTMAX, 0) AS AD_MESESTMAX
     , NVL(COM.SOMPEDPEN, 0) AS SOMPEDPEN
     , NVL(COM.ESTMAX, 0) AS ESTMAX
     , NVL(COM.ESTEXC, 0) AS ESTEXC
 FROM ANALISE_COMPRAS_NOVA COM
    , TGFPAL PAL
WHERE COM.CODPROD = PAL.CODPROD) UNIAO
GROUP BY PK_CODEMP, CODPROD, CONTROLE) ANA
WHERE ANA.PK_CODEMP = UP.PK_CODEMP
  AND ANA.CODPROD = UP.CODPROD
  AND ANA.CONTROLE = UP.CONTROLE)
 WHERE UP.CODPROD IN (SELECT CODPROD FROM TGFPAL);
   
UPDATE ANALISE_COMPRAS_NOVA UP
   SET (ESTATUAL, ESTMIN, MEDIAPVEND, AD_MESESTMAX, SOMPEDPEN, ESTMAX, ESTEXC) =
   (SELECT 0,0,0,0,0,0,0 FROM DUAL)
 WHERE UP.CODPROD IN (SELECT CODPRODALT FROM TGFPAL)
   AND UP.CODPROD IN (SELECT CODPROD FROM TGFPRO WHERE AD_SOMANCOM = 'N' AND SOLCOMPRA = 'N');

UPDATE ANALISE_COMPRAS_NOVA UP SET (SUGESTAO, VLRSUGESTAO) =
(
SELECT  TRUNC(Snk_Dividir(CASE WHEN ESTATUAL <= ESTMIN THEN (MEDIAPVEND * AD_MESESTMAX) - SOMPEDPEN
                              WHEN ESTATUAL <= MEDIAPVEND * (AD_MESESTMAX / 2) THEN (ESTMAX - ESTATUAL) - SOMPEDPEN ELSE 0 END, QTDEMB) + 0.99) * QTDEMB - (TRUNC(SNK_DIVIDIR(ESTEXC, QTDEMB) + 0.99) * QTDEMB) AS SUGESTAO
     , (TRUNC(Snk_Dividir(CASE WHEN ESTATUAL <= ESTMIN THEN (MEDIAPVEND * AD_MESESTMAX) - SOMPEDPEN
                               WHEN ESTATUAL <= MEDIAPVEND * (AD_MESESTMAX / 2) THEN (ESTMAX - ESTATUAL) - SOMPEDPEN ELSE 0 END, QTDEMB) + 0.99) * QTDEMB - (TRUNC(SNK_DIVIDIR(ESTEXC, QTDEMB) + 0.99) * QTDEMB)) * ROUND(NVL(CUSREP, 0),2) AS VLRSUGESTAO
  FROM ANALISE_COMPRAS_NOVA 
 WHERE ANALISE_COMPRAS_NOVA.CODPROD = UP.CODPROD 
   AND ANALISE_COMPRAS_NOVA.CONTROLE = UP.CONTROLE
   AND ANALISE_COMPRAS_NOVA.PK_CODEMP = UP.PK_CODEMP);

UPDATE ANALISE_COMPRAS_NOVA SET ATUALIZACAO = TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS');

COMMIT;

END;
/
