WITH ORCADO_SISTEMA_UNPIVOT AS (
    SELECT
        EMPRESA,
        PROJETO,
        CR,
        NATUREZA,
        CONCAT(ANO, '-01') AS MES_ANO,
        CASE WHEN TIPNAT = 'R' THEN JANEIRO ELSE 0 END AS ORCADO_SISTEMA_REC,
        CASE WHEN TIPNAT = 'D' THEN JANEIRO ELSE 0 END AS ORCADO_SISTEMA_DESP
    FROM ORCAMENTO_APROVADO
    WHERE JANEIRO <> 0
      AND (
            :VAR_AUDIT_ORC_PAI IS NULL
            OR :VAR_AUDIT_ORC_PAI = ''
            OR FIND_IN_SET(ID_ORCAMENTO_PAI, :VAR_AUDIT_ORC_PAI)
          )

    UNION ALL

    SELECT
        EMPRESA,
        PROJETO,
        CR,
        NATUREZA,
        CONCAT(ANO, '-02') AS MES_ANO,
        CASE WHEN TIPNAT = 'R' THEN FEVEREIRO ELSE 0 END AS ORCADO_SISTEMA_REC,
        CASE WHEN TIPNAT = 'D' THEN FEVEREIRO ELSE 0 END AS ORCADO_SISTEMA_DESP
    FROM ORCAMENTO_APROVADO
    WHERE FEVEREIRO <> 0
      AND (
            :VAR_AUDIT_ORC_PAI IS NULL
            OR :VAR_AUDIT_ORC_PAI = ''
            OR FIND_IN_SET(ID_ORCAMENTO_PAI, :VAR_AUDIT_ORC_PAI)
          )

    UNION ALL

    SELECT
        EMPRESA,
        PROJETO,
        CR,
        NATUREZA,
        CONCAT(ANO, '-03') AS MES_ANO,
        CASE WHEN TIPNAT = 'R' THEN MARCO ELSE 0 END AS ORCADO_SISTEMA_REC,
        CASE WHEN TIPNAT = 'D' THEN MARCO ELSE 0 END AS ORCADO_SISTEMA_DESP
    FROM ORCAMENTO_APROVADO
    WHERE MARCO <> 0
      AND (
            :VAR_AUDIT_ORC_PAI IS NULL
            OR :VAR_AUDIT_ORC_PAI = ''
            OR FIND_IN_SET(ID_ORCAMENTO_PAI, :VAR_AUDIT_ORC_PAI)
          )

    UNION ALL

    SELECT
        EMPRESA,
        PROJETO,
        CR,
        NATUREZA,
        CONCAT(ANO, '-04') AS MES_ANO,
        CASE WHEN TIPNAT = 'R' THEN ABRIL ELSE 0 END AS ORCADO_SISTEMA_REC,
        CASE WHEN TIPNAT = 'D' THEN ABRIL ELSE 0 END AS ORCADO_SISTEMA_DESP
    FROM ORCAMENTO_APROVADO
    WHERE ABRIL <> 0
      AND (
            :VAR_AUDIT_ORC_PAI IS NULL
            OR :VAR_AUDIT_ORC_PAI = ''
            OR FIND_IN_SET(ID_ORCAMENTO_PAI, :VAR_AUDIT_ORC_PAI)
          )

    UNION ALL

    SELECT
        EMPRESA,
        PROJETO,
        CR,
        NATUREZA,
        CONCAT(ANO, '-05') AS MES_ANO,
        CASE WHEN TIPNAT = 'R' THEN MAIO ELSE 0 END AS ORCADO_SISTEMA_REC,
        CASE WHEN TIPNAT = 'D' THEN MAIO ELSE 0 END AS ORCADO_SISTEMA_DESP
    FROM ORCAMENTO_APROVADO
    WHERE MAIO <> 0
      AND (
            :VAR_AUDIT_ORC_PAI IS NULL
            OR :VAR_AUDIT_ORC_PAI = ''
            OR FIND_IN_SET(ID_ORCAMENTO_PAI, :VAR_AUDIT_ORC_PAI)
          )

    UNION ALL

    SELECT
        EMPRESA,
        PROJETO,
        CR,
        NATUREZA,
        CONCAT(ANO, '-06') AS MES_ANO,
        CASE WHEN TIPNAT = 'R' THEN JUNHO ELSE 0 END AS ORCADO_SISTEMA_REC,
        CASE WHEN TIPNAT = 'D' THEN JUNHO ELSE 0 END AS ORCADO_SISTEMA_DESP
    FROM ORCAMENTO_APROVADO
    WHERE JUNHO <> 0
      AND (
            :VAR_AUDIT_ORC_PAI IS NULL
            OR :VAR_AUDIT_ORC_PAI = ''
            OR FIND_IN_SET(ID_ORCAMENTO_PAI, :VAR_AUDIT_ORC_PAI)
          )

    UNION ALL

    SELECT
        EMPRESA,
        PROJETO,
        CR,
        NATUREZA,
        CONCAT(ANO, '-07') AS MES_ANO,
        CASE WHEN TIPNAT = 'R' THEN JULHO ELSE 0 END AS ORCADO_SISTEMA_REC,
        CASE WHEN TIPNAT = 'D' THEN JULHO ELSE 0 END AS ORCADO_SISTEMA_DESP
    FROM ORCAMENTO_APROVADO
    WHERE JULHO <> 0
      AND (
            :VAR_AUDIT_ORC_PAI IS NULL
            OR :VAR_AUDIT_ORC_PAI = ''
            OR FIND_IN_SET(ID_ORCAMENTO_PAI, :VAR_AUDIT_ORC_PAI)
          )

    UNION ALL

    SELECT
        EMPRESA,
        PROJETO,
        CR,
        NATUREZA,
        CONCAT(ANO, '-08') AS MES_ANO,
        CASE WHEN TIPNAT = 'R' THEN AGOSTO ELSE 0 END AS ORCADO_SISTEMA_REC,
        CASE WHEN TIPNAT = 'D' THEN AGOSTO ELSE 0 END AS ORCADO_SISTEMA_DESP
    FROM ORCAMENTO_APROVADO
    WHERE AGOSTO <> 0
      AND (
            :VAR_AUDIT_ORC_PAI IS NULL
            OR :VAR_AUDIT_ORC_PAI = ''
            OR FIND_IN_SET(ID_ORCAMENTO_PAI, :VAR_AUDIT_ORC_PAI)
          )

    UNION ALL

    SELECT
        EMPRESA,
        PROJETO,
        CR,
        NATUREZA,
        CONCAT(ANO, '-09') AS MES_ANO,
        CASE WHEN TIPNAT = 'R' THEN SETEMBRO ELSE 0 END AS ORCADO_SISTEMA_REC,
        CASE WHEN TIPNAT = 'D' THEN SETEMBRO ELSE 0 END AS ORCADO_SISTEMA_DESP
    FROM ORCAMENTO_APROVADO
    WHERE SETEMBRO <> 0
      AND (
            :VAR_AUDIT_ORC_PAI IS NULL
            OR :VAR_AUDIT_ORC_PAI = ''
            OR FIND_IN_SET(ID_ORCAMENTO_PAI, :VAR_AUDIT_ORC_PAI)
          )

    UNION ALL

    SELECT
        EMPRESA,
        PROJETO,
        CR,
        NATUREZA,
        CONCAT(ANO, '-10') AS MES_ANO,
        CASE WHEN TIPNAT = 'R' THEN OUTUBRO ELSE 0 END AS ORCADO_SISTEMA_REC,
        CASE WHEN TIPNAT = 'D' THEN OUTUBRO ELSE 0 END AS ORCADO_SISTEMA_DESP
    FROM ORCAMENTO_APROVADO
    WHERE OUTUBRO <> 0
      AND (
            :VAR_AUDIT_ORC_PAI IS NULL
            OR :VAR_AUDIT_ORC_PAI = ''
            OR FIND_IN_SET(ID_ORCAMENTO_PAI, :VAR_AUDIT_ORC_PAI)
          )

    UNION ALL

    SELECT
        EMPRESA,
        PROJETO,
        CR,
        NATUREZA,
        CONCAT(ANO, '-11') AS MES_ANO,
        CASE WHEN TIPNAT = 'R' THEN NOVEMBRO ELSE 0 END AS ORCADO_SISTEMA_REC,
        CASE WHEN TIPNAT = 'D' THEN NOVEMBRO ELSE 0 END AS ORCADO_SISTEMA_DESP
    FROM ORCAMENTO_APROVADO
    WHERE NOVEMBRO <> 0
      AND (
            :VAR_AUDIT_ORC_PAI IS NULL
            OR :VAR_AUDIT_ORC_PAI = ''
            OR FIND_IN_SET(ID_ORCAMENTO_PAI, :VAR_AUDIT_ORC_PAI)
          )

    UNION ALL

    SELECT
        EMPRESA,
        PROJETO,
        CR,
        NATUREZA,
        CONCAT(ANO, '-12') AS MES_ANO,
        CASE WHEN TIPNAT = 'R' THEN DEZEMBRO ELSE 0 END AS ORCADO_SISTEMA_REC,
        CASE WHEN TIPNAT = 'D' THEN DEZEMBRO ELSE 0 END AS ORCADO_SISTEMA_DESP
    FROM ORCAMENTO_APROVADO
    WHERE DEZEMBRO <> 0
      AND (
            :VAR_AUDIT_ORC_PAI IS NULL
            OR :VAR_AUDIT_ORC_PAI = ''
            OR FIND_IN_SET(ID_ORCAMENTO_PAI, :VAR_AUDIT_ORC_PAI)
          )
),
ORCADO_SISTEMA AS (
    SELECT
        MES_ANO,
        CAST(EMPRESA AS UNSIGNED) AS EMPRESA,
        CAST(PROJETO AS UNSIGNED) AS PROJETO,
        CAST(CR AS UNSIGNED) AS CR,
        CAST(NATUREZA AS UNSIGNED) AS NATUREZA,
        SUM(ORCADO_SISTEMA_REC) AS ORCADO_SISTEMA_REC,
        SUM(ORCADO_SISTEMA_DESP) AS ORCADO_SISTEMA_DESP
    FROM ORCADO_SISTEMA_UNPIVOT
    GROUP BY
        MES_ANO,
        CAST(EMPRESA AS UNSIGNED),
        CAST(PROJETO AS UNSIGNED),
        CAST(CR AS UNSIGNED),
        CAST(NATUREZA AS UNSIGNED)
),
ORCADO_IMPORTADO_AGRUPADO AS (
    SELECT
        MES_ANO,
        EMPRESA,
        PROJETO,
        CR,
        NATUREZA,
        SUM(ORCADO_REC) AS ORCADO_IMPORTADO_REC,
        SUM(ORCADO_DESP) AS ORCADO_IMPORTADO_DESP,
        SUM(REALIZADO_REC) AS REALIZADO_REC,
        SUM(REALIZADO_DESP) AS REALIZADO_DESP
    FROM (
        SELECT
            CAST(CODEMP AS UNSIGNED) AS EMPRESA,
            CAST(CODPROJ AS UNSIGNED) AS PROJETO,
            CAST(CODCENCUS AS UNSIGNED) AS CR,
            CAST(CODNAT AS UNSIGNED) AS NATUREZA,
            DATE_FORMAT(DTREF, '%Y-%m') AS MES_ANO,
            COALESCE(PREVREC, 0) AS ORCADO_REC,
            COALESCE(PREVDESP, 0) AS ORCADO_DESP,
            COALESCE(BAIXA_REC, 0) AS REALIZADO_REC,
            COALESCE(BAIXA_DESP, 0) AS REALIZADO_DESP
        FROM IMP_ORCAMANTO_IMPORTADO_RESULTADO
        WHERE CODMETA IN (
            SELECT ID_TIPO_ORCAMENTO
            FROM ORCAMENTO_PAI
            WHERE
                :VAR_AUDIT_ORC_PAI IS NULL
                OR :VAR_AUDIT_ORC_PAI = ''
                OR FIND_IN_SET(ID, :VAR_AUDIT_ORC_PAI)
        )
    ) BASE_DE_DADOS
    GROUP BY
        MES_ANO,
        EMPRESA,
        PROJETO,
        CR,
        NATUREZA
)
SELECT *
FROM ORCADO_IMPORTADO_AGRUPADO;



