SELECT 
    CAB.NUNOTA AS NUMERO_NOTA,
    CAB.NUMNOTA AS NUMERO_NF,
    CAB.SERIENOTA AS SERIE_NF,
    CAB.DTNEG AS DATA_NEGOCIACAO,
    FIN_AGG.DTVENC_PRIMEIRO AS DATA_VENCIMENTO,
    FIN_AGG.DTVENC_ULTIMO AS DATA_VENCIMENTO_ULTIMA,
    VEN.CODVEND AS CODIGO_VENDEDOR,
    VEN.APELIDO AS NOME_VENDEDOR,
    PAR.CODPARC AS CODIGO_CLIENTE,
    PAR.RAZAOSOCIAL AS NOME_CLIENTE,
    PAR.NOMEPARC AS FANTASIA_CLIENTE,
    EMP.CODEMP AS CODIGO_EMPRESA,
    EMP.RAZAOSOCIAL AS NOME_EMPRESA,
    ITE.SEQUENCIA AS SEQUENCIA_ITEM,
    ITE.CODPROD AS CODIGO_PRODUTO,
    PRO.DESCRPROD AS DESCRICAO_PRODUTO,
    NVL(PRO.REFERENCIA, LPAD(TO_CHAR(PRO.CODPROD), 13, '0')) AS CODIGO_BARRAS,
    ITE.QTDNEG AS QUANTIDADE,
    ITE.VLRUNIT AS VALOR_UNITARIO,
    ITE.VLRTOT AS VALOR_TOTAL_ITEM,
    ITE.VLRDESC AS VALOR_DESCONTO,
    ITE.VLRICMS AS VALOR_ICMS_ITEM,
    CUS.CUSSEMICM AS CUSTO_UNITARIO_SEM_ICMS,
    ITE.QTDNEG*CUS.CUSSEMICM AS CUSTO_TOTAL_SEM_ICMS,
  --  OBTEMCUSTO2(ITE.CODPROD, 'S', CAB.CODEMP, 'N', 0, 'N', '', CAB.DTNEG, 3) AS CUSTO_UNITARIO_SEM_ICMS,
  --  (ITE.QTDNEG * OBTEMCUSTO2(ITE.CODPROD, 'S', CAB.CODEMP, 'N', 0, 'N', '', CAB.DTNEG, 3)) AS CUSTO_TOTAL_SEM_ICMS,
    CAB.VLRNOTA AS VALOR_TOTAL_NOTA,
    FIN_AGG.VLR_TOTAL_TITULOS AS VALOR_TOTAL_TITULOS,
    FIN_AGG.VLR_TOTAL_BAIXADO AS VALOR_TOTAL_BAIXADO,
    FIN_AGG.DATA_PRIMEIRA_BAIXA AS DATA_PRIMEIRA_BAIXA,
    FIN_AGG.DATA_ULTIMA_BAIXA AS DATA_ULTIMA_BAIXA,
    CASE 
        WHEN FIN_AGG.VLR_TOTAL_BAIXADO > 0 THEN 'BAIXADO'
        ELSE 'ABERTO'
    END AS STATUS_BAIXA,
    CASE 
        WHEN FIN_AGG.VLR_TOTAL_TITULOS > 0 THEN 
            ROUND((FIN_AGG.VLR_TOTAL_BAIXADO / FIN_AGG.VLR_TOTAL_TITULOS) * 100, 2)
        ELSE 0
    END AS PERCENTUAL_BAIXADO
FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON ITE.NUNOTA = CAB.NUNOTA
INNER JOIN TGFPRO PRO ON PRO.CODPROD = ITE.CODPROD AND PRO.ATIVO = 'S'
INNER JOIN TGFPAR PAR ON PAR.CODPARC = CAB.CODPARC AND PAR.ATIVO = 'S'
INNER JOIN TSIEMP EMP ON EMP.CODEMP = CAB.CODEMP --AND EMP.ATIVA = 'S'
LEFT JOIN TGFVEN VEN ON VEN.CODVEND = CAB.CODVEND AND VEN.ATIVO = 'S'
LEFT JOIN TGFCUS CUS ON ITE.CODPROD = CUS.CODPROD AND CUS.DTATUAL = (SELECT MAX(DTATUAL)FROM TGFCUS WHERE CODPROD = ITE.CODPROD AND DTATUAL< CAB.DTNEG )
LEFT JOIN (
    SELECT 
        FIN.NUNOTA,
        SUM(FIN.VLRDESDOB) AS VLR_TOTAL_TITULOS,
        SUM(NVL(FIN.VLRBAIXA, 0)) AS VLR_TOTAL_BAIXADO,
        MIN(FIN.DTVENC) AS DTVENC_PRIMEIRO,
        MAX(FIN.DTVENC) AS DTVENC_ULTIMO,
        MIN(FIN.DHBAIXA) AS DATA_PRIMEIRA_BAIXA,
        MAX(FIN.DHBAIXA) AS DATA_ULTIMA_BAIXA
    FROM TGFFIN FIN
    WHERE FIN.RECDESP = 1 
        AND FIN.PROVISAO = 'N'
        AND FIN.CODTIPTIT NOT IN (0, 18, 27, 99)
    GROUP BY FIN.NUNOTA
) FIN_AGG ON FIN_AGG.NUNOTA = CAB.NUNOTA
WHERE CAB.STATUSNOTA = 'L'
    AND CAB.TIPMOV = 'V'
    AND ITE.QTDNEG > 0
ORDER BY CAB.DTNEG DESC, CAB.NUNOTA, ITE.SEQUENCIA

