SELECT 
    CAB.NUNOTA AS NUMERO_NOTA,
    CAB.NUMNOTA AS NUMERO_NF,
    CAB.SERIENOTA AS SERIE_NF,
    CAB.DTNEG AS DATA_NEGOCIACAO,
    FIN_AGG.DTVENC_PRIMEIRO AS DATA_VENCIMENTO,
    FIN_AGG.DTVENC_ULTIMO AS DATA_VENCIMENTO_ULTIMA,
    VEN.CODVEND AS CODIGO_VENDEDOR,
    VEN.APELIDO AS NOME_VENDEDOR,
    PAR.CODPARC AS CODIGO_CLIENTE,
    PAR.RAZAOSOCIAL AS NOME_CLIENTE,
    PAR.NOMEPARC AS FANTASIA_CLIENTE,
    EMP.CODEMP AS CODIGO_EMPRESA,
    EMP.RAZAOSOCIAL AS NOME_EMPRESA,
    CUS_AGG.CUSTO_TOTAL_SEM_ICMS,
    CAB.VLRNOTA AS VALOR_TOTAL_NOTA,
    FIN_AGG.VLR_TOTAL_TITULOS AS VALOR_TOTAL_TITULOS,
    FIN_AGG.VLR_TOTAL_BAIXADO AS VALOR_TOTAL_BAIXADO,
    FIN_AGG.DATA_PRIMEIRA_BAIXA AS DATA_PRIMEIRA_BAIXA,
    FIN_AGG.DATA_ULTIMA_BAIXA AS DATA_ULTIMA_BAIXA,
    CASE 
        WHEN FIN_AGG.VLR_TOTAL_BAIXADO > 0 THEN 'BAIXADO'
        ELSE 'ABERTO'
    END AS STATUS_BAIXA,
    CASE 
        WHEN FIN_AGG.VLR_TOTAL_TITULOS > 0 THEN 
            ROUND((FIN_AGG.VLR_TOTAL_BAIXADO / FIN_AGG.VLR_TOTAL_TITULOS) * 100, 2)
        ELSE 0
    END AS PERCENTUAL_BAIXADO,
    (CAB.VLRNOTA - CUS_AGG.CUSTO_TOTAL_SEM_ICMS) AS MARGEM_BRUTA,
    CASE 
        WHEN CAB.VLRNOTA > 0 THEN 
            ROUND(((CAB.VLRNOTA - CUS_AGG.CUSTO_TOTAL_SEM_ICMS) / CAB.VLRNOTA) * 100, 2)
        ELSE 0
    END AS PERCENTUAL_MARGEM
FROM TGFCAB CAB
INNER JOIN TGFPAR PAR ON PAR.CODPARC = CAB.CODPARC AND PAR.ATIVO = 'S'
INNER JOIN TSIEMP EMP ON EMP.CODEMP = CAB.CODEMP
LEFT JOIN TGFVEN VEN ON VEN.CODVEND = CAB.CODVEND AND VEN.ATIVO = 'S'
LEFT JOIN (
    SELECT 
        ITE.NUNOTA,
        SUM(ITE.QTDNEG * NVL(CUS.CUSSEMICM, 0)) AS CUSTO_TOTAL_SEM_ICMS
    FROM TGFITE ITE
    INNER JOIN TGFCAB CAB_CUS ON CAB_CUS.NUNOTA = ITE.NUNOTA
    INNER JOIN TGFPRO PRO ON PRO.CODPROD = ITE.CODPROD AND PRO.ATIVO = 'S'
    LEFT JOIN TGFCUS CUS ON ITE.CODPROD = CUS.CODPROD 
        AND CUS.DTATUAL = (
            SELECT MAX(DTATUAL) 
            FROM TGFCUS 
            WHERE CODPROD = ITE.CODPROD 
                AND DTATUAL <= CAB_CUS.DTNEG
        )
    WHERE ITE.QTDNEG > 0
    GROUP BY ITE.NUNOTA
) CUS_AGG ON CUS_AGG.NUNOTA = CAB.NUNOTA
LEFT JOIN (
    SELECT 
        FIN.NUNOTA,
        SUM(FIN.VLRDESDOB) AS VLR_TOTAL_TITULOS,
        SUM(NVL(FIN.VLRBAIXA, 0)) AS VLR_TOTAL_BAIXADO,
        MIN(FIN.DTVENC) AS DTVENC_PRIMEIRO,
        MAX(FIN.DTVENC) AS DTVENC_ULTIMO,
        MIN(FIN.DHBAIXA) AS DATA_PRIMEIRA_BAIXA,
        MAX(FIN.DHBAIXA) AS DATA_ULTIMA_BAIXA
    FROM TGFFIN FIN
    WHERE FIN.RECDESP = 1 
        AND FIN.PROVISAO = 'N'
        AND FIN.CODTIPTIT NOT IN (0, 18, 27, 99)
    GROUP BY FIN.NUNOTA
) FIN_AGG ON FIN_AGG.NUNOTA = CAB.NUNOTA
WHERE CAB.STATUSNOTA = 'L'
    AND CAB.TIPMOV = 'V'
ORDER BY CAB.DTNEG DESC, CAB.NUNOTA;

