SELECT CASE WHEN 
CAB.TIPMOV = 'P' THEN  'Pedido' ELSE 'Nota' END AS TIPO,
CAB.NUNOTA AS "ID_PEDIDO",
CAB.NUMNOTA AS N_NOTA,
CAB.DTNEG AS DATA,
VEN.CODVEND AS COD_VENDEDOR,
VEN.APELIDO,
VEN.AD_SUPERVISOR,
(SELECT DISTINCT APELIDO FROM TGFVEN VE WHERE VE.CODVEND = VEN.AD_SUPERVISOR) AS NOME_SUPERVISOR,
VEN.CODGER,
(SELECT DISTINCT APELIDO FROM TGFVEN VE WHERE VE.CODVEND = VEN.CODGER) AS NOME_GERENTE,
CAB.CODPARC AS "ID_CLIENTE",
PAR.RAZAOSOCIAL AS CLIENTE,
EN.NOMEEND||', '|| PAR.NUMEND AS ENDERECO, 
CID.NOMECID AS CIDADE, 
UFS.UF AS UF,
PAR.CEP,
CAB.PESO, 
(SELECT sum(FC_QTDALT_HL(ITE.CODPROD,ITE.QTDNEG,'HL')) FROM TGFITE ITE WHERE ITE.NUNOTA = CAB.NUNOTA) AS VOLUME,
(SELECT sum(FC_QTDALT_HL(ITE.CODPROD,ITE.QTDNEG,ITE.CODVOL)) FROM TGFITE ITE WHERE ITE.NUNOTA = CAB.NUNOTA) AS PT,
'' AS "TEMPO_ATENDIMENTO",
'' AS "PRIORIDADE_CLIENTE",
PAR.TELEFONE,
PAR.EMAIL,
BAI.NOMEBAI AS BAIRRO,
CAB.VLRNOTA, 
PAR.AD_HRENTREGA AS "JANELA_INICIO",
PAR.AD_HRENTREGAFIM AS "JANELA_FIM",
'' AS "JANELA_INICIO_2",
'' AS "JANELA_FIM_2",
'' AS "TERRITORIOS",
(SELECT NOMECANAL FROM AD_CANAL CA WHERE CA.CDCANAL = PAR.AD_CDCANAL AND CA.CDGRUPOCANAL = PAR.AD_CDGRUPOCANAL) AS "TIPO_DO_CLIENTE",
'' AS "TIPO_ATENDIMENTO",
CAB.OBSERVACAO AS "INSTRUCOES_ENTREGA",
'' AS "CODIGOS_DE_BARRAS",
(SELECT NOMECONTATO FROM TGFCTT CTT WHERE CTT.CODPARC = PAR.CODPARC AND CTT.CODCONTATO = 1 ) AS "Nome_do_Contato",
'' AS "ID_Embalagem",
'' AS "Id_Deposito",
'' AS "Nome_Deposito",
'' AS "Embalagem",
TRANSP.CODPARC AS "ID_Transportadora",
TRANSP.RAZAOSOCIAL AS "Nome_Transportadora",
'' AS "NumeroLote",
'' AS "Quantidade_de_Itens",
'' AS "Bandeira",
PAR.CGC_CPF AS "CPF_OU_CNPJ",
CAB.CODTIPOPER,
TOP.DESCROPER,
'' AS "Comentarios",
'' AS "Senha",
'' AS "NUMERO_LOTE",
'' AS "CODIGO_REMESSA",
'' AS "DATA_LIMITE_ATENDIMENTO",
CAB.ORDEMCARGA, 
CAB.CODVEICULO,
CAB.CODEMP

FROM TGFCAB CAB
JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
JOIN TSICID CID ON PAR.CODCID = CID.CODCID
JOIN TSIUFS UFS ON CID.UF = UFS.CODUF
JOIN TSIEND EN ON PAR.CODEND = EN.CODEND
JOIN TSIBAI BAI ON PAR.CODBAI = BAI.CODBAI
JOIN TGFTOP TOP ON CAB.CODTIPOPER = TOP.CODTIPOPER AND CAB.DHTIPOPER = TOP.DHALTER
JOIN TGFORD ORD ON ORD.ORDEMCARGA = CAB.ORDEMCARGA AND ORD.CODEMP = CAB.CODEMP
LEFT JOIN TGFPAR MOT ON MOT.CODPARC = ORD.CODPARCMOTORISTA
LEFT JOIN TGFPAR TRANSP ON TRANSP.CODPARC = ORD.CODPARCTRANSP
JOIN TSIEMP EMP ON EMP.CODEMP = ORD.CODEMP
JOIN TGFVEN VEN ON VEN.CODVEND = CAB.CODVEND

WHERE (CAB.DTNEG BETWEEN :PERIODO_INI AND :PERIODO_FIN)
AND (CAB.CODEMP IN :P_CODEMP OR :P_CODEMP IS NULL)
AND (CAB.CODVEND IN :P_CODVEND OR :P_CODVEND IS NULL)
AND (CAB.TIPMOV = :P_TIPO OR :P_TIPO = 'T')
AND (CAB.PENDENTE = :P_PENDENTE OR :P_PENDENTE = 'T')
AND (CAB.CODPARC = :P_CODPARC OR :P_CODPARC IS NULL)
AND (CAB.ORDEMCARGA = :P_ORDEMCARGA OR :P_ORDEMCARGA IS NULL)
AND (CAB.CODVEICULO = :P_CODVEICULO OR :P_CODVEICULO IS NULL)