WITH TIPO_PESO_CORRETO AS (
    SELECT CODPARC, TIPO_PESO, ID_TIPO_ARMAZENAGEM
    FROM (
        SELECT V.CODPARC, TA.TIPO_PESO, V.ID_TIPO_ARMAZENAGEM,
               ROW_NUMBER() OVER (PARTITION BY V.CODPARC ORDER BY V.ID DESC) AS RN
        FROM VINCULO_PARCEIRO_TIPO V
        JOIN TIPO_ARMAZENAGEM TA ON V.ID_TIPO_ARMAZENAGEM = TA.ID
    ) X
    WHERE RN = 1
)
SELECT IFNULL(SUM(CASE WHEN TPC.TIPO_PESO = 'Líquido' THEN N.PESO_ITEM_LIQ ELSE N.PESO_ITEM END), 0) AS VALOR
FROM IMP_NOTAS_ARMAZ N
JOIN TIPO_PESO_CORRETO TPC ON N.CODPARC = TPC.CODPARC
WHERE N.ATUALESTOQUE = 1
  AND N.DTNEG BETWEEN :VAR_DT_INICIO AND :VAR_DT_FIM
  AND (COALESCE(:VAR_FILTRO_PARCEIRO, '') IN ('', 'all') OR N.CODPARC = :VAR_FILTRO_PARCEIRO)
  AND (COALESCE(:VAR_FILTRO_TIPO, '') IN ('', 'all') OR TPC.ID_TIPO_ARMAZENAGEM = :VAR_FILTRO_TIPO)
