SELECT DISTINCT P.CODPARC, P.NOMEPARC
FROM IMP_PACEIRO P
WHERE P.CODPARC IN (
    SELECT CODPARC FROM IMP_NOTAS_ARMAZ
    UNION
    SELECT CODPARC FROM GESTAO_NOTAS_APROVACAO WHERE ENTREGUE = 1
)
ORDER BY P.NOMEPARC
