WITH VINCULO_CORRETO AS (
    SELECT CODPARC, TIPO_PESO, ID_TIPO_ARMAZENAGEM
    FROM (
        SELECT V.CODPARC, TA.TIPO_PESO, V.ID_TIPO_ARMAZENAGEM,
               ROW_NUMBER() OVER (PARTITION BY V.CODPARC ORDER BY V.ID DESC) AS RN
        FROM VINCULO_PARCEIRO_TIPO V
        JOIN TIPO_ARMAZENAGEM TA ON TA.ID = V.ID_TIPO_ARMAZENAGEM
    ) X
    WHERE RN = 1
),
ITENS AS (
    SELECT I.DESCRPROD AS PRODUTO,
           (CASE WHEN VC.TIPO_PESO = 'Líquido' THEN I.PESO_ITEM_LIQ ELSE I.PESO_ITEM END) AS ENTRADA,
           0 AS SAIDA,
           (I.VLRUNIT * I.QTDNEG) AS VALOR
    FROM GESTAO_NOTAS_APROVACAO G
    JOIN IMP_ITENS_NOTAS_APRV I ON I.NUNOTA = G.NUNOTA
    JOIN VINCULO_CORRETO VC ON VC.CODPARC = G.CODPARC
    WHERE G.ENTREGUE = 1
      AND (COALESCE(:VAR_DT_INICIO, '') = '' OR G.DATA_ENTREGA >= :VAR_DT_INICIO)
      AND (COALESCE(:VAR_DT_FIM, '') = '' OR G.DATA_ENTREGA <= :VAR_DT_FIM)
      AND (COALESCE(:VAR_FILTRO_PARCEIRO, '') IN ('', 'all') OR G.CODPARC = :VAR_FILTRO_PARCEIRO)
      AND (COALESCE(:VAR_FILTRO_TIPO, '') IN ('', 'all') OR VC.ID_TIPO_ARMAZENAGEM = :VAR_FILTRO_TIPO)
    UNION ALL
    SELECT N.DESCRPROD AS PRODUTO,
           0 AS ENTRADA,
           (CASE WHEN VC.TIPO_PESO = 'Líquido' THEN N.PESO_ITEM_LIQ ELSE N.PESO_ITEM END) AS SAIDA,
           -(N.VLRUNIT * N.QTDNEG) AS VALOR
    FROM IMP_NOTAS_ARMAZ N
    JOIN VINCULO_CORRETO VC ON VC.CODPARC = N.CODPARC
    WHERE N.ATUALESTOQUE = 1
      AND (COALESCE(:VAR_DT_INICIO, '') = '' OR N.DTNEG >= :VAR_DT_INICIO)
      AND (COALESCE(:VAR_DT_FIM, '') = '' OR N.DTNEG <= :VAR_DT_FIM)
      AND (COALESCE(:VAR_FILTRO_PARCEIRO, '') IN ('', 'all') OR N.CODPARC = :VAR_FILTRO_PARCEIRO)
      AND (COALESCE(:VAR_FILTRO_TIPO, '') IN ('', 'all') OR VC.ID_TIPO_ARMAZENAGEM = :VAR_FILTRO_TIPO)
)
SELECT PRODUTO,
       ROUND(SUM(ENTRADA), 2) AS ENTRADA,
       ROUND(SUM(SAIDA), 2) AS SAIDA,
       ROUND(SUM(ENTRADA) - SUM(SAIDA), 2) AS SALDO,
       ROUND(SUM(VALOR), 2) AS VALOR_TOTAL
FROM ITENS
GROUP BY PRODUTO
ORDER BY SALDO DESC
