WITH VINCULO_CORRETO AS (
    SELECT CODPARC, TIPO_PESO, ID_TIPO_ARMAZENAGEM
    FROM (
        SELECT V.CODPARC, TA.TIPO_PESO, V.ID_TIPO_ARMAZENAGEM,
               ROW_NUMBER() OVER (PARTITION BY V.CODPARC ORDER BY V.ID DESC) AS RN
        FROM VINCULO_PARCEIRO_TIPO V
        JOIN TIPO_ARMAZENAGEM TA ON TA.ID = V.ID_TIPO_ARMAZENAGEM
    ) X
    WHERE RN = 1
),
MOVIMENTOS AS (
    SELECT G.CODPARC, G.DATA_ENTREGA AS DT_MOV, I.AUTO_ID,
           (CASE WHEN VC.TIPO_PESO = 'Líquido' THEN I.PESO_ITEM_LIQ ELSE I.PESO_ITEM END) AS PESO,
           (I.VLRUNIT * I.QTDNEG) AS VALOR,
           'ENTRADA' AS TIPO_MOV,
           VC.ID_TIPO_ARMAZENAGEM
    FROM GESTAO_NOTAS_APROVACAO G
    JOIN IMP_ITENS_NOTAS_APRV I ON I.NUNOTA = G.NUNOTA
    JOIN VINCULO_CORRETO VC ON VC.CODPARC = G.CODPARC
    WHERE G.ENTREGUE = 1
    UNION ALL
    SELECT N.CODPARC, N.DTNEG AS DT_MOV, N.AUTO_ID,
           -(CASE WHEN VC.TIPO_PESO = 'Líquido' THEN N.PESO_ITEM_LIQ ELSE N.PESO_ITEM END) AS PESO,
           -(N.VLRUNIT * N.QTDNEG) AS VALOR,
           'SAIDA' AS TIPO_MOV,
           VC.ID_TIPO_ARMAZENAGEM
    FROM IMP_NOTAS_ARMAZ N
    JOIN VINCULO_CORRETO VC ON VC.CODPARC = N.CODPARC
    WHERE N.ATUALESTOQUE = 1
),
MOVIMENTOS_FILTRADOS AS (
    SELECT *
    FROM MOVIMENTOS
    WHERE (COALESCE(:VAR_FILTRO_PARCEIRO, '') IN ('', 'all') OR CODPARC = :VAR_FILTRO_PARCEIRO)
      AND (COALESCE(:VAR_FILTRO_TIPO, '') IN ('', 'all') OR ID_TIPO_ARMAZENAGEM = :VAR_FILTRO_TIPO)
),
SALDO_INICIAL AS (
    SELECT CODPARC,
           GREATEST(COALESCE(SUM(PESO), 0), 0) AS SI_PESO,
           GREATEST(COALESCE(SUM(VALOR), 0), 0) AS SI_VALOR
    FROM MOVIMENTOS_FILTRADOS
    WHERE COALESCE(:VAR_DT_INICIO, '') <> ''
      AND DT_MOV < :VAR_DT_INICIO
    GROUP BY CODPARC
),
MOVIMENTOS_PERIODO AS (
    SELECT *
    FROM MOVIMENTOS_FILTRADOS
    WHERE (COALESCE(:VAR_DT_INICIO, '') = '' OR DT_MOV >= :VAR_DT_INICIO)
      AND (COALESCE(:VAR_DT_FIM, '') = '' OR DT_MOV <= :VAR_DT_FIM)
),
SALDOS_PERIODO AS (
    SELECT MP.CODPARC, MP.TIPO_MOV, MP.PESO,
           COALESCE(SI.SI_PESO, 0) + SUM(MP.PESO) OVER (PARTITION BY MP.CODPARC ORDER BY MP.DT_MOV, MP.AUTO_ID) AS SALDO_PESO,
           COALESCE(SI.SI_VALOR, 0) + SUM(MP.VALOR) OVER (PARTITION BY MP.CODPARC ORDER BY MP.DT_MOV, MP.AUTO_ID) AS SALDO_VALOR
    FROM MOVIMENTOS_PERIODO MP
    LEFT JOIN SALDO_INICIAL SI ON SI.CODPARC = MP.CODPARC
),
BASE_PARCEIRO AS (
    SELECT PM.CODPARC,
           GREATEST(COALESCE(AP.MAX_SALDO_PESO, 0), COALESCE(SI.SI_PESO, 0), 0) AS PICO_PESO,
           GREATEST(COALESCE(AP.MAX_SALDO_VALOR, 0), COALESCE(SI.SI_VALOR, 0), 0) AS PICO_VALOR,
           COALESCE(AP.ENTRADA_PESO, 0) AS ENTRADA_PESO,
           COALESCE(AP.SAIDA_PESO, 0) AS SAIDA_PESO
    FROM (SELECT DISTINCT CODPARC FROM MOVIMENTOS_FILTRADOS) PM
    LEFT JOIN (
        SELECT CODPARC,
               MAX(SALDO_PESO) AS MAX_SALDO_PESO,
               MAX(SALDO_VALOR) AS MAX_SALDO_VALOR,
               SUM(CASE WHEN TIPO_MOV = 'ENTRADA' THEN PESO ELSE 0 END) AS ENTRADA_PESO,
               SUM(CASE WHEN TIPO_MOV = 'SAIDA' THEN -PESO ELSE 0 END) AS SAIDA_PESO
        FROM SALDOS_PERIODO
        GROUP BY CODPARC
    ) AP ON AP.CODPARC = PM.CODPARC
    LEFT JOIN SALDO_INICIAL SI ON SI.CODPARC = PM.CODPARC
),
CUSTO_ITEM AS (
    SELECT B.CODPARC, VC.ID_TIPO_ARMAZENAGEM, CP.NOME_CRITERIO,
           ROUND(CASE
               WHEN C.TIPO_VALOR = 'Percentual' OR CP.TIPO_CALCULO = 'Valor Declarado'
                   THEN GREATEST(0, B.PICO_VALOR) * (C.VALOR / 100)
               ELSE (CASE
                   WHEN CP.TIPO_CALCULO = 'Entrada' THEN GREATEST(0, B.ENTRADA_PESO / 1000)
                   WHEN CP.TIPO_CALCULO = 'Saida' THEN GREATEST(0, B.SAIDA_PESO / 1000)
                   ELSE GREATEST(0, B.PICO_PESO / 1000)
               END) * C.VALOR
           END, 2) AS CUSTO
    FROM BASE_PARCEIRO B
    JOIN VINCULO_CORRETO VC ON VC.CODPARC = B.CODPARC
    JOIN CRITERIO_COBRANCA C ON C.ID_TIPO_ARMAZENAGEM = VC.ID_TIPO_ARMAZENAGEM
    JOIN CRITERIO_PADRAO CP ON CP.NOME_CRITERIO = C.NOME_CRITERIO
)
SELECT
    (SELECT COUNT(DISTINCT N.NUNOTA)
     FROM IMP_NOTAS_ARMAZ N
     WHERE (COALESCE(:VAR_DT_INICIO, '') = '' OR N.DTNEG >= :VAR_DT_INICIO)
       AND (COALESCE(:VAR_DT_FIM, '') = '' OR N.DTNEG <= :VAR_DT_FIM)
       AND (COALESCE(:VAR_FILTRO_PARCEIRO, '') IN ('', 'all') OR N.CODPARC = :VAR_FILTRO_PARCEIRO)
       AND (COALESCE(:VAR_FILTRO_TIPO, '') IN ('', 'all') OR EXISTS (
             SELECT 1 FROM VINCULO_CORRETO VC
             WHERE VC.CODPARC = N.CODPARC AND VC.ID_TIPO_ARMAZENAGEM = :VAR_FILTRO_TIPO))
    ) AS QTD_LANCAMENTOS,
    (SELECT ROUND(COALESCE(SUM(CUSTO), 0), 2) FROM CUSTO_ITEM) AS CUSTO_TOTAL,
    (SELECT ROUND(COALESCE(SUM(-PESO), 0), 2)
     FROM MOVIMENTOS_PERIODO
     WHERE TIPO_MOV = 'SAIDA'
    ) AS VOLUME_TOTAL
