WITH TIPO_PESO_CORRETO AS (
    SELECT CODPARC, TIPO_PESO, ID_TIPO_ARMAZENAGEM
    FROM (
        SELECT V.CODPARC, TA.TIPO_PESO, V.ID_TIPO_ARMAZENAGEM,
               ROW_NUMBER() OVER (PARTITION BY V.CODPARC ORDER BY V.ID DESC) AS RN
        FROM VINCULO_PARCEIRO_TIPO V
        JOIN TIPO_ARMAZENAGEM TA ON V.ID_TIPO_ARMAZENAGEM = TA.ID
    ) X
    WHERE RN = 1
)
SELECT IFNULL(SUM(CASE WHEN TPC.TIPO_PESO = 'Líquido' THEN I.PESO_ITEM_LIQ ELSE I.PESO_ITEM END), 0) AS VALOR
FROM GESTAO_NOTAS_APROVACAO G
JOIN IMP_ITENS_NOTAS_APRV I ON G.NUNOTA = I.NUNOTA
JOIN TIPO_PESO_CORRETO TPC ON G.CODPARC = TPC.CODPARC
WHERE G.ENTREGUE = 1
  AND G.DATA_ENTREGA BETWEEN :VAR_DT_INICIO AND :VAR_DT_FIM
  AND (COALESCE(:VAR_FILTRO_PARCEIRO, '') IN ('', 'all') OR G.CODPARC = :VAR_FILTRO_PARCEIRO)
  AND (COALESCE(:VAR_FILTRO_TIPO, '') IN ('', 'all') OR TPC.ID_TIPO_ARMAZENAGEM = :VAR_FILTRO_TIPO)
