WITH VINCULO_CORRETO AS (
    SELECT CODPARC, TIPO_PESO, ID_TIPO_ARMAZENAGEM
    FROM (
        SELECT V.CODPARC, TA.TIPO_PESO, V.ID_TIPO_ARMAZENAGEM,
               ROW_NUMBER() OVER (PARTITION BY V.CODPARC ORDER BY V.ID DESC) AS RN
        FROM VINCULO_PARCEIRO_TIPO V
        JOIN TIPO_ARMAZENAGEM TA ON TA.ID = V.ID_TIPO_ARMAZENAGEM
    ) X
    WHERE RN = 1
),
MOVIMENTOS AS (
    SELECT G.CODPARC, G.DATA_ENTREGA AS DT_MOV, I.AUTO_ID,
           (CASE WHEN VC.TIPO_PESO = 'Líquido' THEN I.PESO_ITEM_LIQ ELSE I.PESO_ITEM END) AS PESO,
           'ENTRADA' AS TIPO_MOV,
           VC.ID_TIPO_ARMAZENAGEM
    FROM GESTAO_NOTAS_APROVACAO G
    JOIN IMP_ITENS_NOTAS_APRV I ON I.NUNOTA = G.NUNOTA
    JOIN VINCULO_CORRETO VC ON VC.CODPARC = G.CODPARC
    WHERE G.ENTREGUE = 1
    UNION ALL
    SELECT N.CODPARC, N.DTNEG AS DT_MOV, N.AUTO_ID,
           -(CASE WHEN VC.TIPO_PESO = 'Líquido' THEN N.PESO_ITEM_LIQ ELSE N.PESO_ITEM END) AS PESO,
           'SAIDA' AS TIPO_MOV,
           VC.ID_TIPO_ARMAZENAGEM
    FROM IMP_NOTAS_ARMAZ N
    JOIN VINCULO_CORRETO VC ON VC.CODPARC = N.CODPARC
    WHERE N.ATUALESTOQUE = 1
)
SELECT ROUND(GREATEST(COALESCE(SUM(PESO), 0), 0), 2) AS VALOR
FROM MOVIMENTOS
WHERE (COALESCE(:VAR_DT_FIM, '') = '' OR DT_MOV <= :VAR_DT_FIM)
  AND (COALESCE(:VAR_FILTRO_PARCEIRO, '') IN ('', 'all') OR CODPARC = :VAR_FILTRO_PARCEIRO)
  AND (COALESCE(:VAR_FILTRO_TIPO, '') IN ('', 'all') OR ID_TIPO_ARMAZENAGEM = :VAR_FILTRO_TIPO)
