WITH VINCULO_CORRETO AS (
    SELECT CODPARC, TIPO_PESO, ID_TIPO_ARMAZENAGEM
    FROM (
        SELECT V.CODPARC, TA.TIPO_PESO, V.ID_TIPO_ARMAZENAGEM,
               ROW_NUMBER() OVER (PARTITION BY V.CODPARC ORDER BY V.ID DESC) AS RN
        FROM VINCULO_PARCEIRO_TIPO V
        JOIN TIPO_ARMAZENAGEM TA ON TA.ID = V.ID_TIPO_ARMAZENAGEM
    ) X
    WHERE RN = 1
),
MOVIMENTOS AS (
    SELECT G.CODPARC, G.DATA_ENTREGA AS DT_MOV, I.AUTO_ID,
           (CASE WHEN VC.TIPO_PESO = 'Líquido' THEN I.PESO_ITEM_LIQ ELSE I.PESO_ITEM END) AS PESO,
           (I.VLRUNIT * I.QTDNEG) AS VALOR,
           'ENTRADA' AS TIPO_MOV,
           VC.ID_TIPO_ARMAZENAGEM
    FROM GESTAO_NOTAS_APROVACAO G
    JOIN IMP_ITENS_NOTAS_APRV I ON I.NUNOTA = G.NUNOTA
    JOIN VINCULO_CORRETO VC ON VC.CODPARC = G.CODPARC
    WHERE G.ENTREGUE = 1
    UNION ALL
    SELECT N.CODPARC, N.DTNEG AS DT_MOV, N.AUTO_ID,
           -(CASE WHEN VC.TIPO_PESO = 'Líquido' THEN N.PESO_ITEM_LIQ ELSE N.PESO_ITEM END) AS PESO,
           -(N.VLRUNIT * N.QTDNEG) AS VALOR,
           'SAIDA' AS TIPO_MOV,
           VC.ID_TIPO_ARMAZENAGEM
    FROM IMP_NOTAS_ARMAZ N
    JOIN VINCULO_CORRETO VC ON VC.CODPARC = N.CODPARC
    WHERE N.ATUALESTOQUE = 1
),
MOVIMENTOS_FILTRADOS AS (
    SELECT *
    FROM MOVIMENTOS
    WHERE (COALESCE(:VAR_FILTRO_PARCEIRO, '') IN ('', 'all') OR CODPARC = :VAR_FILTRO_PARCEIRO)
      AND (COALESCE(:VAR_FILTRO_TIPO, '') IN ('', 'all') OR ID_TIPO_ARMAZENAGEM = :VAR_FILTRO_TIPO)
),
SALDOS AS (
    SELECT CODPARC, DT_MOV, AUTO_ID, PESO, VALOR, TIPO_MOV,
           SUM(PESO) OVER (PARTITION BY CODPARC ORDER BY DT_MOV, AUTO_ID) AS SALDO_PESO,
           SUM(VALOR) OVER (PARTITION BY CODPARC ORDER BY DT_MOV, AUTO_ID) AS SALDO_VALOR
    FROM MOVIMENTOS_FILTRADOS
),
SALDOS_MES AS (
    SELECT CODPARC,
           DATE_FORMAT(DT_MOV, '%Y-%m-01') AS MES,
           PESO, VALOR, TIPO_MOV, SALDO_PESO, SALDO_VALOR,
           FIRST_VALUE(SALDO_PESO - PESO) OVER (PARTITION BY CODPARC, DATE_FORMAT(DT_MOV, '%Y-%m-01') ORDER BY DT_MOV, AUTO_ID) AS SI_PESO,
           FIRST_VALUE(SALDO_VALOR - VALOR) OVER (PARTITION BY CODPARC, DATE_FORMAT(DT_MOV, '%Y-%m-01') ORDER BY DT_MOV, AUTO_ID) AS SI_VALOR
    FROM SALDOS
    WHERE (COALESCE(:VAR_DT_INICIO, '') = '' OR DT_MOV >= :VAR_DT_INICIO)
      AND (COALESCE(:VAR_DT_FIM, '') = '' OR DT_MOV <= :VAR_DT_FIM)
),
BASE_MES AS (
    SELECT CODPARC, MES,
           GREATEST(MAX(SALDO_PESO) + GREATEST(-MAX(SI_PESO), 0), GREATEST(MAX(SI_PESO), 0), 0) AS PICO_PESO,
           GREATEST(MAX(SALDO_VALOR) + GREATEST(-MAX(SI_VALOR), 0), GREATEST(MAX(SI_VALOR), 0), 0) AS PICO_VALOR,
           COALESCE(SUM(CASE WHEN TIPO_MOV = 'ENTRADA' THEN PESO END), 0) AS ENTRADA_PESO,
           COALESCE(SUM(CASE WHEN TIPO_MOV = 'SAIDA' THEN -PESO END), 0) AS SAIDA_PESO
    FROM SALDOS_MES
    GROUP BY CODPARC, MES
)
SELECT B.MES AS DATA_LANCAMENTO,
       ROUND(SUM(
           CASE
               WHEN C.TIPO_VALOR = 'Percentual' OR CP.TIPO_CALCULO = 'Valor Declarado'
                   THEN GREATEST(0, B.PICO_VALOR) * (C.VALOR / 100)
               ELSE (CASE
                   WHEN CP.TIPO_CALCULO = 'Entrada' THEN GREATEST(0, B.ENTRADA_PESO / 1000)
                   WHEN CP.TIPO_CALCULO = 'Saida' THEN GREATEST(0, B.SAIDA_PESO / 1000)
                   ELSE GREATEST(0, B.PICO_PESO / 1000)
               END) * C.VALOR
           END
       ), 2) AS CUSTO
FROM BASE_MES B
JOIN VINCULO_CORRETO VC ON VC.CODPARC = B.CODPARC
JOIN CRITERIO_COBRANCA C ON C.ID_TIPO_ARMAZENAGEM = VC.ID_TIPO_ARMAZENAGEM
JOIN CRITERIO_PADRAO CP ON CP.NOME_CRITERIO = C.NOME_CRITERIO
GROUP BY B.MES
ORDER BY B.MES
