WITH VINCULO_CORRETO AS (
    SELECT CODPARC, TIPO_PESO, ID_TIPO_ARMAZENAGEM
    FROM (
        SELECT V.CODPARC, TA.TIPO_PESO, V.ID_TIPO_ARMAZENAGEM,
               ROW_NUMBER() OVER (PARTITION BY V.CODPARC ORDER BY V.ID DESC) AS RN
        FROM VINCULO_PARCEIRO_TIPO V
        JOIN TIPO_ARMAZENAGEM TA ON TA.ID = V.ID_TIPO_ARMAZENAGEM
    ) X
    WHERE RN = 1
),
MOVIMENTOS AS (
    SELECT G.CODPARC, G.DATA_ENTREGA AS DT_MOV, I.AUTO_ID,
           (CASE WHEN VC.TIPO_PESO = 'Líquido' THEN I.PESO_ITEM_LIQ ELSE I.PESO_ITEM END) AS PESO,
           VC.ID_TIPO_ARMAZENAGEM
    FROM GESTAO_NOTAS_APROVACAO G
    JOIN IMP_ITENS_NOTAS_APRV I ON I.NUNOTA = G.NUNOTA
    JOIN VINCULO_CORRETO VC ON VC.CODPARC = G.CODPARC
    WHERE G.ENTREGUE = 1
    UNION ALL
    SELECT N.CODPARC, N.DTNEG AS DT_MOV, N.AUTO_ID,
           -(CASE WHEN VC.TIPO_PESO = 'Líquido' THEN N.PESO_ITEM_LIQ ELSE N.PESO_ITEM END) AS PESO,
           VC.ID_TIPO_ARMAZENAGEM
    FROM IMP_NOTAS_ARMAZ N
    JOIN VINCULO_CORRETO VC ON VC.CODPARC = N.CODPARC
    WHERE N.ATUALESTOQUE = 1
),
MOVIMENTOS_FILTRADOS AS (
    SELECT *
    FROM MOVIMENTOS
    WHERE (COALESCE(:VAR_FILTRO_PARCEIRO, '') IN ('', 'all') OR CODPARC = :VAR_FILTRO_PARCEIRO)
      AND (COALESCE(:VAR_FILTRO_TIPO, '') IN ('', 'all') OR ID_TIPO_ARMAZENAGEM = :VAR_FILTRO_TIPO)
),
SALDO_INICIAL_VAL AS (
    SELECT GREATEST(COALESCE(SUM(CASE WHEN COALESCE(:VAR_DT_INICIO, '') <> '' AND DT_MOV < :VAR_DT_INICIO THEN PESO END), 0), 0) AS VALOR
    FROM MOVIMENTOS_FILTRADOS
),
SALDO_DIARIO AS (
    SELECT DT_MOV,
           (SELECT VALOR FROM SALDO_INICIAL_VAL) + SUM(PESO) OVER (ORDER BY DT_MOV, AUTO_ID) AS SALDO_ACUMULADO
    FROM MOVIMENTOS_FILTRADOS
    WHERE (COALESCE(:VAR_DT_INICIO, '') = '' OR DT_MOV >= :VAR_DT_INICIO)
      AND (COALESCE(:VAR_DT_FIM, '') = '' OR DT_MOV <= :VAR_DT_FIM)
),
CANDIDATOS AS (
    SELECT VALOR AS SALDO,
           CASE WHEN COALESCE(:VAR_DT_INICIO, '') <> '' THEN :VAR_DT_INICIO END AS DT_REF
    FROM SALDO_INICIAL_VAL
    UNION ALL
    SELECT SALDO_ACUMULADO AS SALDO, DT_MOV AS DT_REF
    FROM SALDO_DIARIO
)
SELECT ROUND(GREATEST(COALESCE(SALDO, 0), 0), 2) AS PICO_PERIODO,
       DATE_FORMAT(DT_REF, '%Y-%m-%d') AS DATA_PICO
FROM CANDIDATOS
ORDER BY SALDO DESC
LIMIT 1
