CREATE OR REPLACE PACKAGE PKG_MOCK_ACT AS

       PROCEDURE RESET;
       PROCEDURE SET_PARAM(P_NOME VARCHAR2, P_VALOR VARCHAR2);
       PROCEDURE SET_FIELD(P_LINHA PLS_INTEGER, P_NOME VARCHAR2, P_VALOR VARCHAR2);

       FUNCTION ACT_TXT_PARAM(P_IDSESSAO VARCHAR2, P_NOME VARCHAR2) RETURN VARCHAR2;
       FUNCTION ACT_INT_PARAM(P_IDSESSAO VARCHAR2, P_NOME VARCHAR2) RETURN NUMBER;
       FUNCTION ACT_DEC_PARAM(P_IDSESSAO VARCHAR2, P_NOME VARCHAR2) RETURN NUMBER;
       FUNCTION ACT_DTA_PARAM(P_IDSESSAO VARCHAR2, P_NOME VARCHAR2) RETURN DATE;
       FUNCTION ACT_INT_FIELD(P_IDSESSAO VARCHAR2, P_LINHA NUMBER, P_NOME VARCHAR2) RETURN NUMBER;

END PKG_MOCK_ACT;
/

CREATE OR REPLACE PACKAGE BODY PKG_MOCK_ACT AS

       TYPE T_MAPA IS TABLE OF VARCHAR2(4000) INDEX BY VARCHAR2(200);
       G_PARAMS T_MAPA;
       G_FIELDS T_MAPA;

       PROCEDURE RESET IS
       BEGIN
              G_PARAMS.DELETE;
              G_FIELDS.DELETE;
       END RESET;

       PROCEDURE SET_PARAM(P_NOME VARCHAR2, P_VALOR VARCHAR2) IS
       BEGIN
              G_PARAMS(UPPER(P_NOME)) := P_VALOR;
       END SET_PARAM;

       PROCEDURE SET_FIELD(P_LINHA PLS_INTEGER, P_NOME VARCHAR2, P_VALOR VARCHAR2) IS
       BEGIN
              G_FIELDS(P_LINHA || '.' || UPPER(P_NOME)) := P_VALOR;
       END SET_FIELD;

       FUNCTION ACT_TXT_PARAM(P_IDSESSAO VARCHAR2, P_NOME VARCHAR2) RETURN VARCHAR2 IS
       BEGIN
              IF G_PARAMS.EXISTS(UPPER(P_NOME)) THEN
                 RETURN G_PARAMS(UPPER(P_NOME));
              END IF;
              RETURN NULL;
       END ACT_TXT_PARAM;

       FUNCTION ACT_INT_PARAM(P_IDSESSAO VARCHAR2, P_NOME VARCHAR2) RETURN NUMBER IS
              V_TXT VARCHAR2(4000) := ACT_TXT_PARAM(P_IDSESSAO, P_NOME);
       BEGIN
              RETURN CASE WHEN V_TXT IS NULL THEN NULL ELSE TO_NUMBER(V_TXT) END;
       END ACT_INT_PARAM;

       FUNCTION ACT_DEC_PARAM(P_IDSESSAO VARCHAR2, P_NOME VARCHAR2) RETURN NUMBER IS
              V_TXT VARCHAR2(4000) := ACT_TXT_PARAM(P_IDSESSAO, P_NOME);
       BEGIN
              RETURN CASE WHEN V_TXT IS NULL THEN NULL ELSE TO_NUMBER(REPLACE(V_TXT, ',', '.')) END;
       END ACT_DEC_PARAM;

       FUNCTION ACT_DTA_PARAM(P_IDSESSAO VARCHAR2, P_NOME VARCHAR2) RETURN DATE IS
              V_TXT VARCHAR2(4000) := ACT_TXT_PARAM(P_IDSESSAO, P_NOME);
       BEGIN
              RETURN CASE WHEN V_TXT IS NULL THEN NULL ELSE TO_DATE(V_TXT, 'DD/MM/YYYY') END;
       END ACT_DTA_PARAM;

       FUNCTION ACT_INT_FIELD(P_IDSESSAO VARCHAR2, P_LINHA NUMBER, P_NOME VARCHAR2) RETURN NUMBER IS
              V_CHAVE VARCHAR2(200) := TO_CHAR(P_LINHA) || '.' || UPPER(P_NOME);
       BEGIN
              IF G_FIELDS.EXISTS(V_CHAVE) THEN
                 RETURN TO_NUMBER(G_FIELDS(V_CHAVE));
              END IF;
              RETURN NULL;
       END ACT_INT_FIELD;

END PKG_MOCK_ACT;
/
