CREATE OR REPLACE PROCEDURE SANKHYA.PROC_TAB_04_EXCECOES
IS
/* ------------------------------------------------------------------------------
-- OBJETO: PROCEDURE PERSONALIZADA
-- AUTOR: LEANDRO MARCOS MOREIRA
-- INTUITO: GERAR PRECOS NA CODTAB 04 EXCECOES
*/ ------------------------------------------------------------------------------

P_NUTAB       TGFEXC.NUTAB%TYPE  := 919; -- CODTAB = 04 NUTAB = 919
P_CODPROD     TGFEXC.CODPROD%TYPE;
P_CODLOCAL    TGFEXC.CODLOCAL%TYPE;
P_CONTROLE    TGFEXC.CONTROLE%TYPE;
P_VLRVENDA    TGFEXC.VLRVENDA%TYPE;
P_TIPO        TGFEXC.TIPO%TYPE := 'P'; -- TIPO = 'P' ATUALIZAR PARA PERCENTUAL NA CODTAB = 04
P_MODBASEICMS TGFEXC.MODBASEICMS%TYPE;
P_PERCDESC    TGFEXC.PERCDESC%TYPE;
P_MARGLUCRO   TGFEXC.MARGLUCRO%TYPE;
P_PERCCOM     TGFEXC.PERCCOM%TYPE;
P_AD_DTALTER  TGFEXC.AD_DTALTER%TYPE;
P_DESCMAXFLEX TGFPRO.DESCMAXFLEX%TYPE;

V_VLRVENDA    TGFEXC.VLRVENDA%TYPE;
V_TIPO        TGFEXC.TIPO%TYPE;
V_DESCMAXFLEX TGFPRO.DESCMAXFLEX%TYPE;

CURSOR Tabela_04 IS
SELECT COM.CODPROD
     , 0 AS CODLOCAL
     , ' ' AS CONTROLE
     , CASE WHEN COM.ABC = 'A' AND (COM.ESTATUAL = 0 OR COM.MEDIAPVEND = 0)            THEN -25
            WHEN COM.ABC = 'B' AND (COM.ESTATUAL = 0 OR COM.MEDIAPVEND = 0)            THEN -23
            WHEN COM.ABC = 'C' AND (COM.ESTATUAL = 0 OR COM.MEDIAPVEND = 0)            THEN -20
            WHEN COM.ABC = 'A' AND COM.ESTATUAL <= (COM.MEDIAPVEND * 0.5) + COM.ESTMIN THEN -17
            WHEN COM.ABC = 'B' AND COM.ESTATUAL <= (COM.MEDIAPVEND * 0.5) + COM.ESTMIN THEN -15
            WHEN COM.ABC = 'C' AND COM.ESTATUAL <= (COM.MEDIAPVEND * 0.5) + COM.ESTMIN THEN -15
            WHEN COM.ABC = 'A' AND COM.ESTATUAL <= COM.MEDIAPVEND + COM.ESTMIN         THEN -19
            WHEN COM.ABC = 'B' AND COM.ESTATUAL <= COM.MEDIAPVEND + COM.ESTMIN         THEN -17
            WHEN COM.ABC = 'C' AND COM.ESTATUAL <= COM.MEDIAPVEND + COM.ESTMIN         THEN -15
            WHEN COM.ABC = 'A' AND COM.ESTATUAL <= (COM.MEDIAPVEND * 2) + COM.ESTMIN   THEN -22
            WHEN COM.ABC = 'B' AND COM.ESTATUAL <= (COM.MEDIAPVEND * 2) + COM.ESTMIN   THEN -20
            WHEN COM.ABC = 'C' AND COM.ESTATUAL <= (COM.MEDIAPVEND * 2) + COM.ESTMIN   THEN -17
            WHEN COM.ABC = 'A' AND COM.ESTATUAL <= (COM.MEDIAPVEND * 3) + COM.ESTMIN   THEN -24
            WHEN COM.ABC = 'B' AND COM.ESTATUAL <= (COM.MEDIAPVEND * 3) + COM.ESTMIN   THEN -22
            WHEN COM.ABC = 'C' AND COM.ESTATUAL <= (COM.MEDIAPVEND * 3) + COM.ESTMIN   THEN -19
            WHEN COM.ABC = 'A' AND COM.ESTATUAL <= (COM.MEDIAPVEND * 4) + COM.ESTMIN   THEN -25
            WHEN COM.ABC = 'B' AND COM.ESTATUAL <= (COM.MEDIAPVEND * 4) + COM.ESTMIN   THEN -23
            WHEN COM.ABC = 'C' AND COM.ESTATUAL <= (COM.MEDIAPVEND * 4) + COM.ESTMIN   THEN -20
            WHEN COM.ABC = 'A' AND COM.ESTATUAL > (COM.MEDIAPVEND * 4) + COM.ESTMIN    THEN -26
            WHEN COM.ABC = 'B' AND COM.ESTATUAL > (COM.MEDIAPVEND * 4) + COM.ESTMIN    THEN -24
            WHEN COM.ABC = 'C' AND COM.ESTATUAL > (COM.MEDIAPVEND * 4) + COM.ESTMIN    THEN -21
        END AS VLRVENDA
     , CASE WHEN COM.ABC = 'A' AND (COM.ESTATUAL = 0 OR COM.MEDIAPVEND = 0)            THEN 5
            WHEN COM.ABC = 'B' AND (COM.ESTATUAL = 0 OR COM.MEDIAPVEND = 0)            THEN 5
            WHEN COM.ABC = 'C' AND (COM.ESTATUAL = 0 OR COM.MEDIAPVEND = 0)            THEN 5
            WHEN COM.ABC = 'A' AND COM.ESTATUAL <= (COM.MEDIAPVEND * 0.5) + COM.ESTMIN THEN 2
            WHEN COM.ABC = 'B' AND COM.ESTATUAL <= (COM.MEDIAPVEND * 0.5) + COM.ESTMIN THEN 2
            WHEN COM.ABC = 'C' AND COM.ESTATUAL <= (COM.MEDIAPVEND * 0.5) + COM.ESTMIN THEN 2
            WHEN COM.ABC = 'A' AND COM.ESTATUAL <= COM.MEDIAPVEND + COM.ESTMIN         THEN 5
            WHEN COM.ABC = 'B' AND COM.ESTATUAL <= COM.MEDIAPVEND + COM.ESTMIN         THEN 5
            WHEN COM.ABC = 'C' AND COM.ESTATUAL <= COM.MEDIAPVEND + COM.ESTMIN         THEN 5
            WHEN COM.ABC = 'A' AND COM.ESTATUAL <= (COM.MEDIAPVEND * 2) + COM.ESTMIN   THEN 7
            WHEN COM.ABC = 'B' AND COM.ESTATUAL <= (COM.MEDIAPVEND * 2) + COM.ESTMIN   THEN 7
            WHEN COM.ABC = 'C' AND COM.ESTATUAL <= (COM.MEDIAPVEND * 2) + COM.ESTMIN   THEN 7
            WHEN COM.ABC = 'A' AND COM.ESTATUAL <= (COM.MEDIAPVEND * 3) + COM.ESTMIN   THEN 10
            WHEN COM.ABC = 'B' AND COM.ESTATUAL <= (COM.MEDIAPVEND * 3) + COM.ESTMIN   THEN 10
            WHEN COM.ABC = 'C' AND COM.ESTATUAL <= (COM.MEDIAPVEND * 3) + COM.ESTMIN   THEN 10
            WHEN COM.ABC = 'A' AND COM.ESTATUAL <= (COM.MEDIAPVEND * 4) + COM.ESTMIN   THEN 15
            WHEN COM.ABC = 'B' AND COM.ESTATUAL <= (COM.MEDIAPVEND * 4) + COM.ESTMIN   THEN 15
            WHEN COM.ABC = 'C' AND COM.ESTATUAL <= (COM.MEDIAPVEND * 4) + COM.ESTMIN   THEN 15
            WHEN COM.ABC = 'A' AND COM.ESTATUAL > (COM.MEDIAPVEND * 4) + COM.ESTMIN    THEN 20
            WHEN COM.ABC = 'B' AND COM.ESTATUAL > (COM.MEDIAPVEND * 4) + COM.ESTMIN    THEN 20
            WHEN COM.ABC = 'C' AND COM.ESTATUAL > (COM.MEDIAPVEND * 4) + COM.ESTMIN    THEN 20
        END AS DESCMAXFLEX
     , 'O' AS MODBASEICMS
     , NULL AS PERCDESC
     , NULL AS MARGLUCRO
     , NULL AS PERCCOM
     , SYSDATE AS AD_DTALTER
   FROM (SELECT CODPROD
              , SUM(ESTATUAL) AS ESTATUAL
              , SUM(ESTMIN) AS ESTMIN
              , SUM(MEDIAPVEND) AS MEDIAPVEND
              , ABC
           FROM ANALISE_COMPRAS_NOVA
          GROUP BY CODPROD
                 , ABC) COM
      , TGFPRO PRO
   WHERE PRO.CODPROD = COM.CODPROD
     AND PRO.CODGRUPOPROD < 20000000; 

BEGIN
OPEN Tabela_04;
   LOOP
   FETCH Tabela_04 INTO
         P_CODPROD
       , P_CODLOCAL
       , P_CONTROLE
       , P_VLRVENDA
       , P_DESCMAXFLEX
       , P_MODBASEICMS
       , P_PERCDESC
       , P_MARGLUCRO
       , P_PERCCOM
       , P_AD_DTALTER;

   BEGIN
      SELECT V.VLRVENDA
        INTO V_VLRVENDA
        FROM TGFEXC V
      WHERE V.NUTAB = P_NUTAB
        AND V.CODPROD = P_CODPROD
        AND V.CODLOCAL = P_CODLOCAL
        AND V.CONTROLE = P_CONTROLE
        AND V.TIPO = P_TIPO;
      EXCEPTION WHEN NO_DATA_FOUND THEN
      V_VLRVENDA := P_VLRVENDA;
   END;

   IF (V_VLRVENDA <> P_VLRVENDA) THEN
      UPDATE TGFEXC U
         SET (U.VLRVENDA, U.TIPO, U.MODBASEICMS, U.PERCDESC, U.MARGLUCRO, U.PERCCOM, U.AD_DTALTER) =
     (SELECT P_VLRVENDA, P_TIPO, P_MODBASEICMS, P_PERCDESC, P_MARGLUCRO, P_PERCCOM, P_AD_DTALTER FROM DUAL)
       WHERE U.NUTAB = P_NUTAB
         AND U.CODPROD = P_CODPROD
         AND U.CODLOCAL = P_CODLOCAL
         AND U.CONTROLE = P_CONTROLE
         AND U.TIPO = P_TIPO;

      IF SQL%ROWCOUNT = 0 THEN
         INSERT INTO TGFEXC I (I.NUTAB, I.CODPROD, I.CODLOCAL, I.CONTROLE, I.VLRVENDA, I.TIPO, I.MODBASEICMS, I.PERCDESC, I.MARGLUCRO, I.PERCCOM, I.AD_DTALTER)
                       SELECT P_NUTAB, P_CODPROD, P_CODLOCAL, P_CONTROLE, P_VLRVENDA, P_TIPO, P_MODBASEICMS, P_PERCDESC, P_MARGLUCRO, P_PERCCOM, P_AD_DTALTER FROM DUAL
                        WHERE P_CODPROD NOT IN (SELECT CODPROD FROM TGFEXC WHERE NUTAB = P_NUTAB);
      END IF;
   END IF;

   SELECT V.DESCMAXFLEX
     INTO V_DESCMAXFLEX
     FROM TGFPRO V
    WHERE V.CODPROD = P_CODPROD;

   IF (V_DESCMAXFLEX <> P_DESCMAXFLEX) THEN
      UPDATE TGFPRO U
         SET U.DESCMAXFLEX = P_DESCMAXFLEX
       WHERE U.CODPROD = P_CODPROD;
   END IF;
   
   EXIT WHEN Tabela_04%NOTFOUND;
   END LOOP;
   CLOSE Tabela_04;
   
   COMMIT;
END;
/
