CREATE OR REPLACE PROCEDURE SANKHYA.Proc_ANALISE_COMPRAS_NOVA
IS
/*====================================================================================
   OBJETO:  PROCEDURE PERSONALIZADA
   AUTOR:   LEANDRO MARCOS MOREIRA (leandromarcosmoreira@gmail.com) 34 99120-4642
   INTUITO: AUTOMATIZAR TAREFAS DE IMPORTAR DADOS PARA DASHBOARD ANÁLISE DE COMPRAS
            O RESULTADO É A SUBSTITUIÇÃO DO PROGRAMA DE COMPRAS.
   ÚLTIMA ATUALIZAÇÃO: 13/07/2018 AS 12:00
   ==================================================================================*/
   
   P_COUNT INT := 0;                   P_CODEMP NUMBER;                      P_CODPROD INT;
   P_CONTROLE VARCHAR2(10);            P_ORCAME12 NUMBER;                    P_ORCAME11 NUMBER;
   P_ORCAME10 NUMBER;                  P_ORCAME09 NUMBER;                    P_ORCAME08 NUMBER;
   P_ORCAME07 NUMBER;                  P_ORCAME06 NUMBER;                    P_ORCAME05 NUMBER;
   P_ORCAME04 NUMBER;                  P_ORCAME03 NUMBER;                    P_ORCAME02 NUMBER;
   P_ORCAME01 NUMBER;                  P_SOMPEDPEN NUMBER;                   P_SOMDEVCOM NUMBER;
   P_VENLIQ12 NUMBER;                  P_VENLIQ11 NUMBER;                    P_VENLIQ10 NUMBER;
   P_VENLIQ09 NUMBER;                  P_VENLIQ08 NUMBER;                    P_VENLIQ07 NUMBER;
   P_VENLIQ06 NUMBER;                  P_VENLIQ05 NUMBER;                    P_VENLIQ04 NUMBER;
   P_VENLIQ03 NUMBER;                  P_VENLIQ02 NUMBER;                    P_VENLIQ01 NUMBER;
   P_COMLIQ12 NUMBER;                  P_COMLIQ11 NUMBER;                    P_COMLIQ10 NUMBER;
   P_COMLIQ09 NUMBER;                  P_COMLIQ08 NUMBER;                    P_COMLIQ07 NUMBER;
   P_COMLIQ06 NUMBER;                  P_COMLIQ05 NUMBER;                    P_COMLIQ04 NUMBER;
   P_COMLIQ03 NUMBER;                  P_COMLIQ02 NUMBER;                    P_COMLIQ01 NUMBER;
   P_DEVCOM12 NUMBER;                  P_DEVCOM11 NUMBER;                    P_DEVCOM10 NUMBER;
   P_DEVCOM09 NUMBER;                  P_DEVCOM08 NUMBER;                    P_DEVCOM07 NUMBER;
   P_DEVCOM06 NUMBER;                  P_DEVCOM05 NUMBER;                    P_DEVCOM04 NUMBER;
   P_DEVCOM03 NUMBER;                  P_DEVCOM02 NUMBER;                    P_DEVCOM01 NUMBER;                  
   P_QTDVE12 NUMBER;                   P_QTDVE11 NUMBER;                     P_QTDVE10 NUMBER;
   P_QTDVE09 NUMBER;                   P_QTDVE08 NUMBER;                     P_QTDVE07 NUMBER;
   P_QTDVE06 NUMBER;                   P_QTDVE05 NUMBER;                     P_QTDVE04 NUMBER;
   P_QTDVE03 NUMBER;                   P_QTDVE02 NUMBER;                     P_QTDVE01 NUMBER;
   P_SOLCOMPER12 NUMBER;               P_SOLCOMPER11 NUMBER;                 P_SOLCOMPER10 NUMBER;
   P_SOLCOMPER09 NUMBER;               P_SOLCOMPER08 NUMBER;                 P_SOLCOMPER07 NUMBER;
   P_SOLCOMPER06 NUMBER;               P_SOLCOMPER05 NUMBER;                 P_SOLCOMPER04 NUMBER;
   P_SOLCOMPER03 NUMBER;               P_SOLCOMPER02 NUMBER;                 P_SOLCOMPER01 NUMBER;

   CURSOR AnaliseCompras IS
SELECT PK_CODEMP,                      CODPROD,                              CONTROLE
     , SUM(ORCAME12) AS ORCAME12,      SUM(ORCAME11) AS ORCAME11,            SUM(ORCAME10) AS ORCAME10
     , SUM(ORCAME09) AS ORCAME09,      SUM(ORCAME08) AS ORCAME08,            SUM(ORCAME07) AS ORCAME07
     , SUM(ORCAME06) AS ORCAME06,      SUM(ORCAME05) AS ORCAME05,            SUM(ORCAME04) AS ORCAME04
     , SUM(ORCAME03) AS ORCAME03,      SUM(ORCAME02) AS ORCAME02,            SUM(ORCAME01) AS ORCAME01
     , SUM(SOMPEDPEN) AS SOMPEDPEN,    SUM(SOMDEVCOM) AS SOMDEVCOM,          SUM(VENLIQ12) AS VENLIQ12
     , SUM(VENLIQ11) AS VENLIQ11,      SUM(VENLIQ10) AS VENLIQ10,            SUM(VENLIQ09) AS VENLIQ09
     , SUM(VENLIQ08) AS VENLIQ08,      SUM(VENLIQ07) AS VENLIQ07,            SUM(VENLIQ06) AS VENLIQ06
     , SUM(VENLIQ05) AS VENLIQ05,      SUM(VENLIQ04) AS VENLIQ04,            SUM(VENLIQ03) AS VENLIQ03
     , SUM(VENLIQ02) AS VENLIQ02,      SUM(VENLIQ01) AS VENLIQ01,            SUM(COMLIQ12) AS COMLIQ12
     , SUM(COMLIQ11) AS COMLIQ11,      SUM(COMLIQ10) AS COMLIQ10,            SUM(COMLIQ09) AS COMLIQ09
     , SUM(COMLIQ08) AS COMLIQ08,      SUM(COMLIQ07) AS COMLIQ07,            SUM(COMLIQ06) AS COMLIQ06
     , SUM(COMLIQ05) AS COMLIQ05,      SUM(COMLIQ04) AS COMLIQ04,            SUM(COMLIQ03) AS COMLIQ03
     , SUM(COMLIQ02) AS COMLIQ02,      SUM(COMLIQ01) AS COMLIQ01,            SUM(DEVCOM12) AS DEVCOM12
     , SUM(DEVCOM11) AS DEVCOM11,      SUM(DEVCOM10) AS DEVCOM10,            SUM(DEVCOM09) AS DEVCOM09
     , SUM(DEVCOM08) AS DEVCOM08,      SUM(DEVCOM07) AS DEVCOM07,            SUM(DEVCOM06) AS DEVCOM06
     , SUM(DEVCOM05) AS DEVCOM05,      SUM(DEVCOM04) AS DEVCOM04,            SUM(DEVCOM03) AS DEVCOM03
     , SUM(DEVCOM02) AS DEVCOM02,      SUM(DEVCOM01) AS DEVCOM01,            SUM(QTDVE12) AS QTDVE12
     , SUM(QTDVE11) AS QTDVE11,        SUM(QTDVE10) AS QTDVE10,              SUM(QTDVE09) AS QTDVE09
     , SUM(QTDVE08) AS QTDVE08,        SUM(QTDVE07) AS QTDVE07,              SUM(QTDVE06) AS QTDVE06
     , SUM(QTDVE05) AS QTDVE05,        SUM(QTDVE04) AS QTDVE04,              SUM(QTDVE03) AS QTDVE03
     , SUM(QTDVE02) AS QTDVE02,        SUM(QTDVE01) AS QTDVE01,              SUM(SOLCOMPER12) AS SOLCOMPER12
     , SUM(SOLCOMPER11) AS SOLCOMPER11,SUM(SOLCOMPER10) AS SOLCOMPER10,      SUM(SOLCOMPER09) AS SOLCOMPER09
     , SUM(SOLCOMPER08) AS SOLCOMPER08,SUM(SOLCOMPER07) AS SOLCOMPER07,      SUM(SOLCOMPER06) AS SOLCOMPER06
     , SUM(SOLCOMPER05) AS SOLCOMPER05,SUM(SOLCOMPER04) AS SOLCOMPER04,      SUM(SOLCOMPER03) AS SOLCOMPER03
     , SUM(SOLCOMPER02) AS SOLCOMPER02,SUM(SOLCOMPER01) AS SOLCOMPER01
   FROM
(SELECT ITE.CODEMP AS PK_CODEMP
          , ITE.CODPROD
          , ITE.CONTROLE
          , SUM(CASE WHEN CAB.CODTIPOPER = 1 AND ITE.PENDENTE = 'S' AND  CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -12)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -11)) THEN ITE.QTDNEG - ITE.QTDENTREGUE ELSE 0 END) AS ORCAME12
          , SUM(CASE WHEN CAB.CODTIPOPER = 1 AND ITE.PENDENTE = 'S' AND  CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -11)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -10)) THEN ITE.QTDNEG - ITE.QTDENTREGUE ELSE 0 END) AS ORCAME11
          , SUM(CASE WHEN CAB.CODTIPOPER = 1 AND ITE.PENDENTE = 'S' AND  CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -10)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -9))  THEN ITE.QTDNEG - ITE.QTDENTREGUE ELSE 0 END) AS ORCAME10
          , SUM(CASE WHEN CAB.CODTIPOPER = 1 AND ITE.PENDENTE = 'S' AND  CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -9)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -8))   THEN ITE.QTDNEG - ITE.QTDENTREGUE ELSE 0 END) AS ORCAME09
          , SUM(CASE WHEN CAB.CODTIPOPER = 1 AND ITE.PENDENTE = 'S' AND  CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -8)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -7))   THEN ITE.QTDNEG - ITE.QTDENTREGUE ELSE 0 END) AS ORCAME08
          , SUM(CASE WHEN CAB.CODTIPOPER = 1 AND ITE.PENDENTE = 'S' AND  CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -7)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -6))   THEN ITE.QTDNEG - ITE.QTDENTREGUE ELSE 0 END) AS ORCAME07
          , SUM(CASE WHEN CAB.CODTIPOPER = 1 AND ITE.PENDENTE = 'S' AND  CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -6)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -5))   THEN ITE.QTDNEG - ITE.QTDENTREGUE ELSE 0 END) AS ORCAME06
          , SUM(CASE WHEN CAB.CODTIPOPER = 1 AND ITE.PENDENTE = 'S' AND  CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -5)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -4))   THEN ITE.QTDNEG - ITE.QTDENTREGUE ELSE 0 END) AS ORCAME05
          , SUM(CASE WHEN CAB.CODTIPOPER = 1 AND ITE.PENDENTE = 'S' AND  CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -4)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -3))   THEN ITE.QTDNEG - ITE.QTDENTREGUE ELSE 0 END) AS ORCAME04
          , SUM(CASE WHEN CAB.CODTIPOPER = 1 AND ITE.PENDENTE = 'S' AND  CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -3)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -2))   THEN ITE.QTDNEG - ITE.QTDENTREGUE ELSE 0 END) AS ORCAME03
          , SUM(CASE WHEN CAB.CODTIPOPER = 1 AND ITE.PENDENTE = 'S' AND  CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -2)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -1))   THEN ITE.QTDNEG - ITE.QTDENTREGUE ELSE 0 END) AS ORCAME02
          , SUM(CASE WHEN CAB.CODTIPOPER = 1 AND ITE.PENDENTE = 'S' AND  CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -1)) AND TRUNC (SYSDATE - 1)                    THEN ITE.QTDNEG - ITE.QTDENTREGUE ELSE 0 END) AS ORCAME01
          , SUM(CASE WHEN ((CAB.TIPMOV = 'O' AND ITE.PENDENTE = 'S') OR (CAB.TIPMOV = 'C' AND CAB.STATUSNOTA = 'A')) AND  CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -12)) AND TRUNC (SYSDATE) THEN ITE.QTDNEG - ITE.QTDENTREGUE ELSE 0 END) AS SOMPEDPEN
          , NVL((SELECT SUM(ITE2.QTDNEG) AS QTDNEG 
                          FROM TGFFIN FIN2
                             , TGFTOP TOP2
                             , TGFITE ITE2
                         WHERE FIN2.CODTIPOPER = TOP2.CODTIPOPER 
                           AND FIN2.DHTIPOPER = TOP2.DHALTER
                           AND ITE2.NUNOTA = FIN2.NUNOTA 
                           AND FIN2.DHBAIXA IS NULL
                           AND TOP2.TIPMOV = 'E' 
                           AND ITE2.CODPROD = ITE.CODPROD
                           AND ITE2.CONTROLE = ITE.CONTROLE), 0) AS SOMDEVCOM
          , SUM(CASE WHEN CAB.TIPMOV IN ('V', 'D') AND CAB.CODTIPOPER NOT IN (96,98) AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -12)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -11))    THEN CASE WHEN CAB.TIPMOV = 'V' THEN ITE.QTDNEG WHEN CAB.TIPMOV ='D' THEN ITE.QTDNEG * (-1) END ELSE 0 END) AS VENLIQ12
          , SUM(CASE WHEN CAB.TIPMOV IN ('V', 'D') AND CAB.CODTIPOPER NOT IN (96,98) AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -11))  AND TRUNC (ADD_MONTHS (SYSDATE - 1, -10))   THEN CASE WHEN CAB.TIPMOV = 'V' THEN ITE.QTDNEG WHEN CAB.TIPMOV ='D' THEN ITE.QTDNEG * (-1) END ELSE 0 END) AS VENLIQ11
          , SUM(CASE WHEN CAB.TIPMOV IN ('V', 'D') AND CAB.CODTIPOPER NOT IN (96,98) AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -10))  AND TRUNC (ADD_MONTHS (SYSDATE - 1, -9))    THEN CASE WHEN CAB.TIPMOV = 'V' THEN ITE.QTDNEG WHEN CAB.TIPMOV ='D' THEN ITE.QTDNEG * (-1) END ELSE 0 END) AS VENLIQ10
          , SUM(CASE WHEN CAB.TIPMOV IN ('V', 'D') AND CAB.CODTIPOPER NOT IN (96,98) AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -9))  AND TRUNC (ADD_MONTHS (SYSDATE - 1, -8))     THEN CASE WHEN CAB.TIPMOV = 'V' THEN ITE.QTDNEG WHEN CAB.TIPMOV ='D' THEN ITE.QTDNEG * (-1) END ELSE 0 END) AS VENLIQ09
          , SUM(CASE WHEN CAB.TIPMOV IN ('V', 'D') AND CAB.CODTIPOPER NOT IN (96,98) AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -8))  AND TRUNC (ADD_MONTHS (SYSDATE - 1, -7))     THEN CASE WHEN CAB.TIPMOV = 'V' THEN ITE.QTDNEG WHEN CAB.TIPMOV ='D' THEN ITE.QTDNEG * (-1) END ELSE 0 END) AS VENLIQ08
          , SUM(CASE WHEN CAB.TIPMOV IN ('V', 'D') AND CAB.CODTIPOPER NOT IN (96,98) AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -7))  AND TRUNC (ADD_MONTHS (SYSDATE - 1, -6))     THEN CASE WHEN CAB.TIPMOV = 'V' THEN ITE.QTDNEG WHEN CAB.TIPMOV ='D' THEN ITE.QTDNEG * (-1) END ELSE 0 END) AS VENLIQ07
          , SUM(CASE WHEN CAB.TIPMOV IN ('V', 'D') AND CAB.CODTIPOPER NOT IN (96,98) AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -6))  AND TRUNC (ADD_MONTHS (SYSDATE - 1, -5))     THEN CASE WHEN CAB.TIPMOV = 'V' THEN ITE.QTDNEG WHEN CAB.TIPMOV ='D' THEN ITE.QTDNEG * (-1) END ELSE 0 END) AS VENLIQ06
          , SUM(CASE WHEN CAB.TIPMOV IN ('V', 'D') AND CAB.CODTIPOPER NOT IN (96,98) AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -5))  AND TRUNC (ADD_MONTHS (SYSDATE - 1, -4))     THEN CASE WHEN CAB.TIPMOV = 'V' THEN ITE.QTDNEG WHEN CAB.TIPMOV ='D' THEN ITE.QTDNEG * (-1) END ELSE 0 END) AS VENLIQ05
          , SUM(CASE WHEN CAB.TIPMOV IN ('V', 'D') AND CAB.CODTIPOPER NOT IN (96,98) AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -4))  AND TRUNC (ADD_MONTHS (SYSDATE - 1, -3))     THEN CASE WHEN CAB.TIPMOV = 'V' THEN ITE.QTDNEG WHEN CAB.TIPMOV ='D' THEN ITE.QTDNEG * (-1) END ELSE 0 END) AS VENLIQ04
          , SUM(CASE WHEN CAB.TIPMOV IN ('V', 'D') AND CAB.CODTIPOPER NOT IN (96,98) AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -3 ))  AND TRUNC (ADD_MONTHS (SYSDATE - 1, -2))    THEN CASE WHEN CAB.TIPMOV = 'V' THEN ITE.QTDNEG WHEN CAB.TIPMOV ='D' THEN ITE.QTDNEG * (-1) END ELSE 0 END) AS VENLIQ03
          , SUM(CASE WHEN CAB.TIPMOV IN ('V', 'D') AND CAB.CODTIPOPER NOT IN (96,98) AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -2))  AND TRUNC (ADD_MONTHS (SYSDATE - 1, -1))     THEN CASE WHEN CAB.TIPMOV = 'V' THEN ITE.QTDNEG WHEN CAB.TIPMOV ='D' THEN ITE.QTDNEG * (-1) END ELSE 0 END) AS VENLIQ02
          , SUM(CASE WHEN CAB.TIPMOV IN ('V', 'D') AND CAB.CODTIPOPER NOT IN (96,98) AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -1))  AND TRUNC (SYSDATE - 1)                      THEN CASE WHEN CAB.TIPMOV = 'V' THEN ITE.QTDNEG WHEN CAB.TIPMOV ='D' THEN ITE.QTDNEG * (-1) END ELSE 0 END) AS VENLIQ01
          , SUM(CASE WHEN CAB.TIPMOV IN ('C', 'E') AND CAB.CODTIPOPER NOT IN (113,120,129) AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -12)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -11))  THEN CASE WHEN CAB.TIPMOV = 'C' THEN ITE.QTDNEG WHEN CAB.TIPMOV ='E' THEN ITE.QTDNEG * (-1) END ELSE 0 END) AS COMLIQ12
          , SUM(CASE WHEN CAB.TIPMOV IN ('C', 'E') AND CAB.CODTIPOPER NOT IN (113,120,129) AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -11)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -10))  THEN CASE WHEN CAB.TIPMOV = 'C' THEN ITE.QTDNEG WHEN CAB.TIPMOV ='E' THEN ITE.QTDNEG * (-1) END ELSE 0 END) AS COMLIQ11
          , SUM(CASE WHEN CAB.TIPMOV IN ('C', 'E') AND CAB.CODTIPOPER NOT IN (113,120,129) AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -10)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -9))   THEN CASE WHEN CAB.TIPMOV = 'C' THEN ITE.QTDNEG WHEN CAB.TIPMOV ='E' THEN ITE.QTDNEG * (-1) END ELSE 0 END) AS COMLIQ10
          , SUM(CASE WHEN CAB.TIPMOV IN ('C', 'E') AND CAB.CODTIPOPER NOT IN (113,120,129) AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -9)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -8))    THEN CASE WHEN CAB.TIPMOV = 'C' THEN ITE.QTDNEG WHEN CAB.TIPMOV ='E' THEN ITE.QTDNEG * (-1) END ELSE 0 END) AS COMLIQ09
          , SUM(CASE WHEN CAB.TIPMOV IN ('C', 'E') AND CAB.CODTIPOPER NOT IN (113,120,129) AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -8)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -7))    THEN CASE WHEN CAB.TIPMOV = 'C' THEN ITE.QTDNEG WHEN CAB.TIPMOV ='E' THEN ITE.QTDNEG * (-1) END ELSE 0 END) AS COMLIQ08
          , SUM(CASE WHEN CAB.TIPMOV IN ('C', 'E') AND CAB.CODTIPOPER NOT IN (113,120,129) AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -7)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -6))    THEN CASE WHEN CAB.TIPMOV = 'C' THEN ITE.QTDNEG WHEN CAB.TIPMOV ='E' THEN ITE.QTDNEG * (-1) END ELSE 0 END) AS COMLIQ07
          , SUM(CASE WHEN CAB.TIPMOV IN ('C', 'E') AND CAB.CODTIPOPER NOT IN (113,120,129) AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -6)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -5))    THEN CASE WHEN CAB.TIPMOV = 'C' THEN ITE.QTDNEG WHEN CAB.TIPMOV ='E' THEN ITE.QTDNEG * (-1) END ELSE 0 END) AS COMLIQ06
          , SUM(CASE WHEN CAB.TIPMOV IN ('C', 'E') AND CAB.CODTIPOPER NOT IN (113,120,129) AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -5)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -4))    THEN CASE WHEN CAB.TIPMOV = 'C' THEN ITE.QTDNEG WHEN CAB.TIPMOV ='E' THEN ITE.QTDNEG * (-1) END ELSE 0 END) AS COMLIQ05
          , SUM(CASE WHEN CAB.TIPMOV IN ('C', 'E') AND CAB.CODTIPOPER NOT IN (113,120,129) AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -4)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -3))    THEN CASE WHEN CAB.TIPMOV = 'C' THEN ITE.QTDNEG WHEN CAB.TIPMOV ='E' THEN ITE.QTDNEG * (-1) END ELSE 0 END) AS COMLIQ04
          , SUM(CASE WHEN CAB.TIPMOV IN ('C', 'E') AND CAB.CODTIPOPER NOT IN (113,120,129) AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -3)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -2))    THEN CASE WHEN CAB.TIPMOV = 'C' THEN ITE.QTDNEG WHEN CAB.TIPMOV ='E' THEN ITE.QTDNEG * (-1) END ELSE 0 END) AS COMLIQ03
          , SUM(CASE WHEN CAB.TIPMOV IN ('C', 'E') AND CAB.CODTIPOPER NOT IN (113,120,129) AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -2)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -1))    THEN CASE WHEN CAB.TIPMOV = 'C' THEN ITE.QTDNEG WHEN CAB.TIPMOV ='E' THEN ITE.QTDNEG * (-1) END ELSE 0 END) AS COMLIQ02
          , SUM(CASE WHEN CAB.TIPMOV IN ('C', 'E') AND CAB.CODTIPOPER NOT IN (113,120,129) AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -1)) AND TRUNC (SYSDATE - 1)                     THEN CASE WHEN CAB.TIPMOV = 'C' THEN ITE.QTDNEG WHEN CAB.TIPMOV ='E' THEN ITE.QTDNEG * (-1) END ELSE 0 END) AS COMLIQ01
          , SUM(CASE WHEN CAB.TIPMOV = 'E' AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -12)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -11))                                              THEN ITE.QTDNEG ELSE 0 END) AS DEVCOM12
          , SUM(CASE WHEN CAB.TIPMOV = 'E' AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -11)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -10))  THEN ITE.QTDNEG ELSE 0 END) AS DEVCOM11
          , SUM(CASE WHEN CAB.TIPMOV = 'E' AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -10)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -9))   THEN ITE.QTDNEG ELSE 0 END) AS DEVCOM10
          , SUM(CASE WHEN CAB.TIPMOV = 'E' AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -9)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -8))    THEN ITE.QTDNEG ELSE 0 END) AS DEVCOM09
          , SUM(CASE WHEN CAB.TIPMOV = 'E' AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -8)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -7))    THEN ITE.QTDNEG ELSE 0 END) AS DEVCOM08
          , SUM(CASE WHEN CAB.TIPMOV = 'E' AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -7)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -6))    THEN ITE.QTDNEG ELSE 0 END) AS DEVCOM07
          , SUM(CASE WHEN CAB.TIPMOV = 'E' AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -6)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -5))    THEN ITE.QTDNEG ELSE 0 END) AS DEVCOM06
          , SUM(CASE WHEN CAB.TIPMOV = 'E' AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -5)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -4))    THEN ITE.QTDNEG ELSE 0 END) AS DEVCOM05
          , SUM(CASE WHEN CAB.TIPMOV = 'E' AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -4)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -3))    THEN ITE.QTDNEG ELSE 0 END) AS DEVCOM04
          , SUM(CASE WHEN CAB.TIPMOV = 'E' AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -3)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -2))    THEN ITE.QTDNEG ELSE 0 END) AS DEVCOM03
          , SUM(CASE WHEN CAB.TIPMOV = 'E' AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -2)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -1))    THEN ITE.QTDNEG ELSE 0 END) AS DEVCOM02
          , SUM(CASE WHEN CAB.TIPMOV = 'E' AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -1)) AND TRUNC (SYSDATE - 1)                     THEN ITE.QTDNEG ELSE 0 END) AS DEVCOM01
          , NVL(COUNT(CASE WHEN TIPMOV = 'V' AND CAB.CODTIPOPER NOT IN (96,98)  AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -12))  AND TRUNC (ADD_MONTHS (SYSDATE - 1, -11)) THEN 1 END), 0) AS QTDVE12
          , NVL(COUNT(CASE WHEN TIPMOV = 'V' AND CAB.CODTIPOPER NOT IN (96,98)  AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -11))  AND TRUNC (ADD_MONTHS (SYSDATE - 1, -10)) THEN 1 END), 0) AS QTDVE11
          , NVL(COUNT(CASE WHEN TIPMOV = 'V' AND CAB.CODTIPOPER NOT IN (96,98)  AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -10))  AND TRUNC (ADD_MONTHS (SYSDATE - 1, -9))  THEN 1 END), 0) AS QTDVE10
          , NVL(COUNT(CASE WHEN TIPMOV = 'V' AND CAB.CODTIPOPER NOT IN (96,98)  AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -9))   AND TRUNC (ADD_MONTHS (SYSDATE - 1, -8))  THEN 1 END), 0) AS QTDVE09
          , NVL(COUNT(CASE WHEN TIPMOV = 'V' AND CAB.CODTIPOPER NOT IN (96,98)  AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -8))   AND TRUNC (ADD_MONTHS (SYSDATE - 1, -7))  THEN 1 END), 0) AS QTDVE08
          , NVL(COUNT(CASE WHEN TIPMOV = 'V' AND CAB.CODTIPOPER NOT IN (96,98)  AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -7))   AND TRUNC (ADD_MONTHS (SYSDATE - 1, -6))  THEN 1 END), 0) AS QTDVE07
          , NVL(COUNT(CASE WHEN TIPMOV = 'V' AND CAB.CODTIPOPER NOT IN (96,98)  AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -6))   AND TRUNC (ADD_MONTHS (SYSDATE - 1, -5))  THEN 1 END), 0) AS QTDVE06
          , NVL(COUNT(CASE WHEN TIPMOV = 'V' AND CAB.CODTIPOPER NOT IN (96,98)  AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -5))   AND TRUNC (ADD_MONTHS (SYSDATE - 1, -4))  THEN 1 END), 0) AS QTDVE05
          , NVL(COUNT(CASE WHEN TIPMOV = 'V' AND CAB.CODTIPOPER NOT IN (96,98)  AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -4))   AND TRUNC (ADD_MONTHS (SYSDATE - 1, -3))  THEN 1 END), 0) AS QTDVE04
          , NVL(COUNT(CASE WHEN TIPMOV = 'V' AND CAB.CODTIPOPER NOT IN (96,98)  AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -3))   AND TRUNC (ADD_MONTHS (SYSDATE - 1, -2))  THEN 1 END), 0) AS QTDVE03
          , NVL(COUNT(CASE WHEN TIPMOV = 'V' AND CAB.CODTIPOPER NOT IN (96,98)  AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -2))   AND TRUNC (ADD_MONTHS (SYSDATE - 1, -1))  THEN 1 END), 0) AS QTDVE02
          , NVL(COUNT(CASE WHEN TIPMOV = 'V' AND CAB.CODTIPOPER NOT IN (96,98)  AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -1))   AND TRUNC (SYSDATE -1)  THEN 1 END), 0) AS QTDVE01
          , SUM(CASE WHEN CAB.CODTIPOPER = 6 AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -12)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -11))                   THEN ITE.QTDNEG ELSE 0 END) AS SOLCOMPER12
          , SUM(CASE WHEN CAB.CODTIPOPER = 6 AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -11)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -10))                   THEN ITE.QTDNEG ELSE 0 END) AS SOLCOMPER11
          , SUM(CASE WHEN CAB.CODTIPOPER = 6 AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -10)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -9))                    THEN ITE.QTDNEG ELSE 0 END) AS SOLCOMPER10
          , SUM(CASE WHEN CAB.CODTIPOPER = 6 AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -9)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -8))                     THEN ITE.QTDNEG ELSE 0 END) AS SOLCOMPER09
          , SUM(CASE WHEN CAB.CODTIPOPER = 6 AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -8)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -7))                     THEN ITE.QTDNEG ELSE 0 END) AS SOLCOMPER08
          , SUM(CASE WHEN CAB.CODTIPOPER = 6 AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -7)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -6))                     THEN ITE.QTDNEG ELSE 0 END) AS SOLCOMPER07
          , SUM(CASE WHEN CAB.CODTIPOPER = 6 AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -6)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -5))                     THEN ITE.QTDNEG ELSE 0 END) AS SOLCOMPER06
          , SUM(CASE WHEN CAB.CODTIPOPER = 6 AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -5)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -4))                     THEN ITE.QTDNEG ELSE 0 END) AS SOLCOMPER05
          , SUM(CASE WHEN CAB.CODTIPOPER = 6 AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -4)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -3))                     THEN ITE.QTDNEG ELSE 0 END) AS SOLCOMPER04
          , SUM(CASE WHEN CAB.CODTIPOPER = 6 AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -3)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -2))                     THEN ITE.QTDNEG ELSE 0 END) AS SOLCOMPER03
          , SUM(CASE WHEN CAB.CODTIPOPER = 6 AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -2)) AND TRUNC (ADD_MONTHS (SYSDATE - 1, -1))                     THEN ITE.QTDNEG ELSE 0 END) AS SOLCOMPER02
          , SUM(CASE WHEN CAB.CODTIPOPER = 6 AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -1)) AND TRUNC (SYSDATE - 1)                                      THEN ITE.QTDNEG ELSE 0 END) AS SOLCOMPER01
   FROM TGFITE ITE
   INNER JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA AND CAB.DTMOV BETWEEN TRUNC (ADD_MONTHS (SYSDATE, -12)) AND TRUNC (SYSDATE)
       AND ((CAB.CODTIPOPER IN (28, 50, 206, 132, 231, 612) AND CAB.STATUSNOTA = 'L') 
         OR (CAB.CODTIPOPER = 1 AND (CAB.DUPLICADO = 'N' OR CAB.DUPLICADO IS NULL) AND ITE.PENDENTE = 'S' AND CAB.CODPARC NOT IN (11, 14543, 14604, 14541) AND CAB.STATUSNOTA = 'L')
   OR (CAB.CODTIPOPER = 6 AND CAB.CODPARC NOT IN (11, 14543, 14545, 14604, 14541) AND CAB.STATUSNOTA = 'L')
   OR (CAB.TIPMOV IN ('O', 'E') OR (CAB.CODTIPOPER IN (SELECT CODTIPOPER FROM TGFTOP WHERE GRUPO = 'COMPRA' AND ATIVO = 'S' AND TIPMOV = 'C')))
   )
   INNER JOIN TGFPRO PRO ON PRO.CODPROD = ITE.CODPROD AND PRO.CODGRUPOPROD BETWEEN 10000000 AND 30000000 AND ((PRO.TIPCONTEST = 'S' AND ITE.CONTROLE <> ' ') OR (PRO.TIPCONTEST = 'N' AND ITE.CONTROLE = ' '))
  WHERE ITE.CODEMP IN (1, 31, 41, 51)
    AND ITE.CODLOCALORIG IN (1, 3, 5)
    AND PRO.ATIVO = 'S'
GROUP BY ITE.CODEMP
       , ITE.CODPROD
       , ITE.CONTROLE
UNION
SELECT DISTINCT 
       ITE.CODEMP AS PK_CODEMP,        ITE.CODPROD,                          ITE.CONTROLE
     , 0 AS ORCAME12,                  0 AS ORCAME11,                        0 AS ORCAME10
     , 0 AS ORCAME09,                  0 AS ORCAME08,                        0 AS ORCAME07
     , 0 AS ORCAME06,                  0 AS ORCAME05,                        0 AS ORCAME04
     , 0 AS ORCAME03,                  0 AS ORCAME02,                        0 AS ORCAME01
     , 0 AS SOMPEDPEN,                 0 AS SOMDEVCOM,                       0 AS VENLIQ12
     , 0 AS VENLIQ11,                  0 AS VENLIQ10,                        0 AS VENLIQ09
     , 0 AS VENLIQ08,                  0 AS VENLIQ07,                        0 AS VENLIQ06
     , 0 AS VENLIQ05,                  0 AS VENLIQ04,                        0 AS VENLIQ03
     , 0 AS VENLIQ02,                  0 AS VENLIQ01,                        0 AS COMLIQ12
     , 0 AS COMLIQ11,                  0 AS COMLIQ10,                        0 AS COMLIQ09
     , 0 AS COMLIQ08,                  0 AS COMLIQ07,                        0 AS COMLIQ06
     , 0 AS COMLIQ05,                  0 AS COMLIQ04,                        0 AS COMLIQ03
     , 0 AS COMLIQ02,                  0 AS COMLIQ01,                        0 AS DEVCOM12
     , 0 AS DEVCOM11,                  0 AS DEVCOM10,                        0 AS DEVCOM09
     , 0 AS DEVCOM08,                  0 AS DEVCOM07,                        0 AS DEVCOM06
     , 0 AS DEVCOM05,                  0 AS DEVCOM04,                        0 AS DEVCOM03
     , 0 AS DEVCOM02,                  0 AS DEVCOM01,                        0 AS QTDVE12
     , 0 AS QTDVE11,                   0 AS QTDVE10,                         0 AS QTDVE09
     , 0 AS QTDVE08,                   0 AS QTDVE07,                         0 AS QTDVE06
     , 0 AS QTDVE05,                   0 AS QTDVE04,                         0 AS QTDVE03
     , 0 AS QTDVE02,                   0 AS QTDVE01,                         0 AS SOLCOMPER12
     , 0 AS SOLCOMPER11,               0 AS SOLCOMPER10,                     0 AS SOLCOMPER09
     , 0 AS SOLCOMPER08,               0 AS SOLCOMPER07,                     0 AS SOLCOMPER06
     , 0 AS SOLCOMPER05,               0 AS SOLCOMPER04,                     0 AS SOLCOMPER03
     , 0 AS SOLCOMPER02,               0 AS SOLCOMPER01
  FROM TGFITE ITE
     , TGFPRO PRO
 WHERE PRO.CODPROD = ITE.CODPROD
   AND PRO.CODGRUPOPROD BETWEEN 10000000 AND 30000000
   AND ((PRO.TIPCONTEST = 'S' AND ITE.CONTROLE <> ' ') OR (PRO.TIPCONTEST = 'N' AND ITE.CONTROLE = ' ')))
 GROUP BY PK_CODEMP
        , CODPROD
        , CONTROLE
ORDER BY PK_CODEMP
       , CODPROD
       , CONTROLE;

BEGIN

  -- LIMPA SOMA PEDIDOS PENDENTES PARA EVITAR LIXO.
  UPDATE ANALISE_COMPRAS_NOVA COM SET COM.SOMPEDPEN = 0;
  COMMIT;
  
  OPEN AnaliseCompras;
  
  LOOP
  
    FETCH AnaliseCompras 
     INTO P_CODEMP, P_CODPROD, P_CONTROLE, P_ORCAME12, P_ORCAME11, P_ORCAME10, P_ORCAME09, P_ORCAME08, P_ORCAME07, P_ORCAME06
        , P_ORCAME05, P_ORCAME04, P_ORCAME03, P_ORCAME02, P_ORCAME01, P_SOMPEDPEN, P_SOMDEVCOM, P_VENLIQ12, P_VENLIQ11, P_VENLIQ10
        , P_VENLIQ09, P_VENLIQ08, P_VENLIQ07, P_VENLIQ06, P_VENLIQ05, P_VENLIQ04, P_VENLIQ03, P_VENLIQ02, P_VENLIQ01, P_COMLIQ12, P_COMLIQ11
        , P_COMLIQ10, P_COMLIQ09, P_COMLIQ08, P_COMLIQ07, P_COMLIQ06, P_COMLIQ05, P_COMLIQ04, P_COMLIQ03, P_COMLIQ02, P_COMLIQ01, P_DEVCOM12
        , P_DEVCOM11, P_DEVCOM10, P_DEVCOM09, P_DEVCOM08, P_DEVCOM07, P_DEVCOM06, P_DEVCOM05, P_DEVCOM04, P_DEVCOM03, P_DEVCOM02, P_DEVCOM01
        , P_QTDVE12, P_QTDVE11, P_QTDVE10, P_QTDVE09, P_QTDVE08, P_QTDVE07, P_QTDVE06, P_QTDVE05, P_QTDVE04, P_QTDVE03, P_QTDVE02, P_QTDVE01
        , P_SOLCOMPER12, P_SOLCOMPER11, P_SOLCOMPER10, P_SOLCOMPER09, P_SOLCOMPER08, P_SOLCOMPER07, P_SOLCOMPER06, P_SOLCOMPER05
        , P_SOLCOMPER04, P_SOLCOMPER03, P_SOLCOMPER02, P_SOLCOMPER01;

      UPDATE ANALISE_COMPRAS_NOVA COM 
         SET ( COM.ORCAME12, COM.ORCAME11, COM.ORCAME10, COM.ORCAME09, COM.ORCAME08, COM.ORCAME07, COM.ORCAME06, COM.ORCAME05
             , COM.ORCAME04, COM.ORCAME03, COM.ORCAME02, COM.ORCAME01, COM.SOMPEDPEN, COM.SOMDEVCOM, COM.VENLIQ12, COM.VENLIQ11, COM.VENLIQ10
             , COM.VENLIQ09, COM.VENLIQ08, COM.VENLIQ07, COM.VENLIQ06, COM.VENLIQ05, COM.VENLIQ04, COM.VENLIQ03, COM.VENLIQ02, COM.VENLIQ01
             , COM.COMLIQ12, COM.COMLIQ11, COM.COMLIQ10, COM.COMLIQ09, COM.COMLIQ08, COM.COMLIQ07, COM.COMLIQ06, COM.COMLIQ05, COM.COMLIQ04
             , COM.COMLIQ03, COM.COMLIQ02, COM.COMLIQ01, COM.DEVCOM12, COM.DEVCOM11, COM.DEVCOM10, COM.DEVCOM09, COM.DEVCOM08, COM.DEVCOM07
             , COM.DEVCOM06, COM.DEVCOM05, COM.DEVCOM04, COM.DEVCOM03, COM.DEVCOM02, COM.DEVCOM01, COM.QTDVE12, COM.QTDVE11, COM.QTDVE10
             , COM.QTDVE09, COM.QTDVE08, COM.QTDVE07, COM.QTDVE06, COM.QTDVE05, COM.QTDVE04, COM.QTDVE03, COM.QTDVE02, COM.QTDVE01
             , COM.SOLCOMPER12, COM.SOLCOMPER11, COM.SOLCOMPER10, COM.SOLCOMPER09, COM.SOLCOMPER08, COM.SOLCOMPER07, COM.SOLCOMPER06
             , COM.SOLCOMPER05, COM.SOLCOMPER04, COM.SOLCOMPER03, COM.SOLCOMPER02, COM.SOLCOMPER01) =
       (SELECT P_ORCAME12, P_ORCAME11, P_ORCAME10, P_ORCAME09, P_ORCAME08, P_ORCAME07, P_ORCAME06, P_ORCAME05, P_ORCAME04
             , P_ORCAME03, P_ORCAME02, P_ORCAME01, P_SOMPEDPEN, P_SOMDEVCOM, P_VENLIQ12, P_VENLIQ11, P_VENLIQ10, P_VENLIQ09, P_VENLIQ08
             , P_VENLIQ07, P_VENLIQ06, P_VENLIQ05, P_VENLIQ04, P_VENLIQ03, P_VENLIQ02, P_VENLIQ01, P_COMLIQ12, P_COMLIQ11, P_COMLIQ10
             , P_COMLIQ09, P_COMLIQ08, P_COMLIQ07, P_COMLIQ06, P_COMLIQ05, P_COMLIQ04, P_COMLIQ03, P_COMLIQ02, P_COMLIQ01, P_DEVCOM12
             , P_DEVCOM11, P_DEVCOM10, P_DEVCOM09, P_DEVCOM08, P_DEVCOM07, P_DEVCOM06, P_DEVCOM05, P_DEVCOM04, P_DEVCOM03, P_DEVCOM02
             , P_DEVCOM01, P_QTDVE12, P_QTDVE11, P_QTDVE10, P_QTDVE09, P_QTDVE08, P_QTDVE07, P_QTDVE06, P_QTDVE05, P_QTDVE04, P_QTDVE03
             , P_QTDVE02, P_QTDVE01, P_SOLCOMPER12, P_SOLCOMPER11, P_SOLCOMPER10, P_SOLCOMPER09, P_SOLCOMPER08, P_SOLCOMPER07, P_SOLCOMPER06
             , P_SOLCOMPER05, P_SOLCOMPER04, P_SOLCOMPER03, P_SOLCOMPER02, P_SOLCOMPER01
  FROM DUAL)
  WHERE COM.CODPROD = P_CODPROD 
    AND COM.CONTROLE = P_CONTROLE 
    AND COM.PK_CODEMP = P_CODEMP;
    
IF SQL%ROWCOUNT = 0 THEN
    
   INSERT INTO ANALISE_COMPRAS_NOVA COM ( COM.PK_CODEMP, COM.CODPROD, COM.CONTROLE, COM.ORCAME12, COM.ORCAME11, COM.ORCAME10
                                        , COM.ORCAME09, COM.ORCAME08, COM.ORCAME07, COM.ORCAME06, COM.ORCAME05, COM.ORCAME04, COM.ORCAME03
                                        , COM.ORCAME02, COM.ORCAME01, COM.SOMPEDPEN, COM.SOMDEVCOM, COM.VENLIQ12, COM.VENLIQ11, COM.VENLIQ10
                                        , COM.VENLIQ09, COM.VENLIQ08, COM.VENLIQ07, COM.VENLIQ06, COM.VENLIQ05, COM.VENLIQ04, COM.VENLIQ03
                                        , COM.VENLIQ02, COM.VENLIQ01, COM.COMLIQ12, COM.COMLIQ11, COM.COMLIQ10, COM.COMLIQ09, COM.COMLIQ08
                                        , COM.COMLIQ07, COM.COMLIQ06, COM.COMLIQ05, COM.COMLIQ04, COM.COMLIQ03, COM.COMLIQ02, COM.COMLIQ01
                                        , COM.DEVCOM12, COM.DEVCOM11, COM.DEVCOM10, COM.DEVCOM09, COM.DEVCOM08, COM.DEVCOM07, COM.DEVCOM06
                                        , COM.DEVCOM05, COM.DEVCOM04, COM.DEVCOM03, COM.DEVCOM02, COM.DEVCOM01, COM.QTDVE12, COM.QTDVE11
                                        , COM.QTDVE10, COM.QTDVE09, COM.QTDVE08, COM.QTDVE07, COM.QTDVE06, COM.QTDVE05, COM.QTDVE04
                                        , COM.QTDVE03, COM.QTDVE02, COM.QTDVE01, COM.SOLCOMPER12, COM.SOLCOMPER11, COM.SOLCOMPER10
                                        , COM.SOLCOMPER09, COM.SOLCOMPER08, COM.SOLCOMPER07, COM.SOLCOMPER06, COM.SOLCOMPER05
                                        , COM.SOLCOMPER04, COM.SOLCOMPER03, COM.SOLCOMPER02, COM.SOLCOMPER01)
        VALUES( P_CODEMP, P_CODPROD, P_CONTROLE, P_ORCAME12, P_ORCAME11, P_ORCAME10, P_ORCAME09, P_ORCAME08, P_ORCAME07
              , P_ORCAME06, P_ORCAME05, P_ORCAME04, P_ORCAME03, P_ORCAME02, P_ORCAME01, P_SOMPEDPEN, P_SOMDEVCOM, P_VENLIQ12, P_VENLIQ11
              , P_VENLIQ10, P_VENLIQ09, P_VENLIQ08, P_VENLIQ07, P_VENLIQ06, P_VENLIQ05, P_VENLIQ04, P_VENLIQ03, P_VENLIQ02, P_VENLIQ01
              , P_COMLIQ12, P_COMLIQ11, P_COMLIQ10, P_COMLIQ09, P_COMLIQ08, P_COMLIQ07, P_COMLIQ06, P_COMLIQ05, P_COMLIQ04, P_COMLIQ03
              , P_COMLIQ02, P_COMLIQ01, P_DEVCOM12, P_DEVCOM11, P_DEVCOM10, P_DEVCOM09, P_DEVCOM08, P_DEVCOM07, P_DEVCOM06, P_DEVCOM05
              , P_DEVCOM04, P_DEVCOM03, P_DEVCOM02, P_DEVCOM01, P_QTDVE12, P_QTDVE11, P_QTDVE10, P_QTDVE09, P_QTDVE08, P_QTDVE07, P_QTDVE06
              , P_QTDVE05, P_QTDVE04, P_QTDVE03, P_QTDVE02, P_QTDVE01, P_SOLCOMPER12, P_SOLCOMPER11, P_SOLCOMPER10, P_SOLCOMPER09
              , P_SOLCOMPER08, P_SOLCOMPER07, P_SOLCOMPER06, P_SOLCOMPER05, P_SOLCOMPER04, P_SOLCOMPER03, P_SOLCOMPER02, P_SOLCOMPER01);
  END IF;
  
   EXIT WHEN AnaliseCompras%NOTFOUND;
   END LOOP;

CLOSE AnaliseCompras;

DELETE 
  FROM ANALISE_COMPRAS_NOVA
 WHERE CODPROD IN (SELECT CODPROD 
                     FROM TGFPRO 
                    WHERE ATIVO = 'N');

COMMIT;

END;
/
