create or replace PROCEDURE         PROC_DADOS_ADICIONAIS_NOVA AS
/* -----------------------------------------
-- OBJETO: PROCEDURE PERSONALIZADA
-- AUTOR: LEANDRO MARCOS MOREIRA
-- OBJETIVO: ANALISAR BUSCAS E ATUALIZAÇÕES
*/ ----------------------------------------
BEGIN

/*
UPDATE ANALISE_COMPRAS_NOVA UP 
   SET UP.PRICOMPRA = 
(SELECT CAB.DTENTSAI AS PRICOMPRA
   FROM TGFCAB CAB
      , TGFITE ITE
  WHERE ITE.NUNOTA = CAB.NUNOTA
    AND CAB.CODTIPOPER IN (58,112)
    AND ITE.ROWID = (SELECT MIN(TGFITE.ROWID)
                       FROM TGFCAB
                          , TGFITE
                      WHERE TGFITE.NUNOTA = TGFCAB.NUNOTA
                        AND TGFCAB.CODTIPOPER IN (58,112)
                        AND TGFITE.CODPROD = ITE.CODPROD
                        AND TGFITE.CONTROLE = ITE.CONTROLE)
    AND ITE.CODPROD = UP.CODPROD
    AND ITE.CONTROLE = UP.CONTROLE);
*/

/*
UPDATE ANALISE_COMPRAS_NOVA UP 
   SET (UP.CODEMP
      , UP.CODVEND
      , UP.CODPARC
      , UP.CODUSU
      , UP.PERIPI
      , UP.ULTCOMPRA
      , UP.DTHRMOV
      , UP.DTALTER
      , UP.DTFATUR) =
(SELECT CAB.CODEMP
      , CAB.CODVEND
      , CAB.CODPARC
      , CAB.CODUSU
      , Snk_Dividir(IPI.PERCENTUAL, 100) AS PERIPI
      , CAB.DTENTSAI AS ULTCOMPRA
      , TO_DATE(TO_CHAR(CAB.DTMOV, 'DD/MM/YYYY') || TO_CHAR(CAB.HRMOV, '000000'), 'DD/MM/YYYY HH24:MI:SS') AS DTHRMOV
      , CAB.DTALTER
      , CAB.DTFATUR
   FROM TGFCAB CAB
      , TGFPRO PRO
      , TGFIPI IPI
      , TGFITE ITE
  WHERE CAB.NUNOTA = ITE.NUNOTA
    AND PRO.CODPROD = ITE.CODPROD
    AND IPI.CODIPI = PRO.CODIPI
    AND CAB.CODTIPOPER IN (58,112)
    AND CAB.CODPARC NOT IN (11, 14543, 14545, 14604, 14541)
    AND ITE.ROWID = (SELECT MAX(TGFITE.ROWID)
                       FROM TGFCAB
                          , TGFPRO
                          , TGFIPI
                          , TGFITE
                      WHERE TGFCAB.NUNOTA = TGFITE.NUNOTA
                        AND TGFPRO.CODPROD = TGFITE.CODPROD
                        AND TGFIPI.CODIPI = TGFPRO.CODIPI
                        AND TGFCAB.CODTIPOPER IN (58,112)
                        AND TGFCAB.CODPARC NOT IN (11, 14543, 14545, 14604, 14541)
                        AND TGFITE.CODPROD = ITE.CODPROD
                        AND TGFITE.CONTROLE = ITE.CONTROLE)
    AND ITE.CODPROD = UP.CODPROD
    AND ITE.CONTROLE = UP.CONTROLE);
*/

/*
UPDATE ANALISE_COMPRAS_NOVA UP 
   SET (UP.ULTPEDCOM, UP.PRAZOENTR) =
(SELECT MAX(CAB.DTENTSAI) AS ULTPEDCOM
      , CASE WHEN NVL(UP.ULTCOMPRA - MAX(CAB.DTENTSAI), 1) < 0 THEN 1 ELSE NVL(UP.ULTCOMPRA - MAX(CAB.DTENTSAI), 1) END AS PRAZOENTR
  FROM TGFCAB CAB
     , TGFITE ITE
 WHERE ITE.NUNOTA = CAB.NUNOTA
   AND CAB.TIPMOV = 'O'
   AND ITE.CODPROD = UP.CODPROD
   AND ITE.CONTROLE = UP.CONTROLE);
*/

UPDATE ANALISE_COMPRAS_NOVA UP SET (ULTCOMPRA, DTALTER, ULTPEDCOM, PRAZOENTR, PRICOMPRA) = 
(SELECT MAX (NOTA.DTMOV) AS ULTCOMPRA, MAX(NOTA.DTALTER) AS DTALTER, MAX (PED.DTMOV) AS ULTPEDCOM,
        TRUNC(NVL((MAX (NOTA.DTMOV) - MAX (PED.DTMOV)),1)) AS PRAZOENTR,
        MIN (NOTA.DTMOV) AS PRICOMPRA
     FROM TGFCAB NOTA, TGFCAB PED, TGFVAR VAR, TGFITE ITE
    WHERE VAR.NUNOTA = NOTA.NUNOTA
      AND PED.NUNOTA = VAR.NUNOTAORIG
      AND ITE.NUNOTA = NOTA.NUNOTA
      AND NOTA.CODTIPOPER IN (58, 112)
      AND NOTA.CODPARC NOT IN (11, 14543, 14545, 14604, 14541)
      AND ITE.CODPROD = UP.CODPROD
      AND ITE.CONTROLE = UP.CONTROLE);

UPDATE ANALISE_COMPRAS_NOVA COM SET (CODEMP, CODVEND, CODPARC, CODUSU, PERIPI, DTHRMOV, DTALTER, DTFATUR) =
(SELECT CAB.CODEMP, CAB.CODVEND, MAX (CAB.CODPARC), CAB.CODUSU, NVL(Snk_Dividir(IPI.PERCENTUAL, 100), 0) AS PERIPI, MAX(TO_DATE(TO_CHAR(CAB.DTMOV, 'DD/MM/YYYY') || TO_CHAR(CAB.HRMOV, '000000'), 'DD/MM/YYYY HH24:MI:SS')) AS DTHRMOV, MAX(CAB.DTALTER) AS DTALTER, MAX(CAB.DTFATUR) AS DTFATUR
  FROM TGFCAB CAB, TGFPRO PRO, TGFIPI IPI, TGFITE ITE
 WHERE CAB.NUNOTA = ITE.NUNOTA
   AND PRO.CODPROD = ITE.CODPROD
   AND IPI.CODIPI = PRO.CODIPI
   AND CAB.DTALTER = COM.DTALTER
   AND CAB.DTMOV = COM.ULTCOMPRA
   AND CAB.CODTIPOPER IN (58, 112)
   AND CAB.CODPARC NOT IN (11, 14543, 14545, 14604, 14541)
   AND COM.CODPROD = ITE.CODPROD
   AND COM.CONTROLE = ITE.CONTROLE
GROUP BY CAB.CODEMP, CAB.CODVEND, CAB.CODUSU, IPI.PERCENTUAL);

DELETE FROM ANALISE_COMPRAS_NOVA DEL WHERE DEL.CODPROD IN (SELECT PRO.CODPROD 
                                                             FROM TGFPRO PRO WHERE PRO.ATIVO = 'N');

   UPDATE ANALISE_COMPRAS_NOVA UP SET (UP.CUSREP, UP.CUSVAR) =
(SELECT NVL(Obtem_Custo_REP(UP.CODPROD), 0)
      , NVL(Obtem_Custo_Var(UP.CODPROD), 0)
   FROM DUAL);

 UPDATE ANALISE_COMPRAS_NOVA UP
   SET ( UP.DESCRPROD, UP.MARCA, UP.CODVOL, UP.CODGRUPOPROD, UP.DESCRGRUPOPROD
       , UP.QTDEMB, UP.SOLCOMPRA, UP.AD_MESESTMAX, UP.PROMOCAO, UP.MARGLUCRO, UP.ABC ) =
(SELECT PRO.DESCRPROD, PRO.MARCA, PRO.CODVOL, PRO.CODGRUPOPROD, GRU.DESCRGRUPOPROD
      , NVL(PRO.QTDEMB, 1), NVL(PRO.SOLCOMPRA, 'S'), NVL(PRO.AD_MESESTMAX, 1), PRO.PROMOCAO, NVL(PRO.MARGLUCRO, 9), NVL(PRO.AD_CURVAABC, 'C')
   FROM TGFPRO PRO
   INNER JOIN TGFGRU GRU ON GRU.CODGRUPOPROD = PRO.CODGRUPOPROD
  WHERE PRO.CODPROD = UP.CODPROD);

UPDATE ANALISE_COMPRAS_NOVA UP
   SET ( PERIODO12, PERIODO11, PERIODO10, PERIODO09, PERIODO08, PERIODO07, PERIODO06, PERIODO05, PERIODO04, PERIODO03, PERIODO02, PERIODO01) =
(SELECT TO_CHAR(TRUNC (ADD_MONTHS (SYSDATE, - 12)),'DD/MM/YYYY') || ' - ' || TO_CHAR(TRUNC (ADD_MONTHS (SYSDATE - 1, - 11)),'DD/MM/YYYY') AS PERIODO12
      , TO_CHAR(TRUNC (ADD_MONTHS (SYSDATE, - 11)),'DD/MM/YYYY') || ' - ' || TO_CHAR(TRUNC (ADD_MONTHS (SYSDATE - 1, - 10)),'DD/MM/YYYY') AS PERIODO11
      , TO_CHAR(TRUNC (ADD_MONTHS (SYSDATE, - 10)),'DD/MM/YYYY') || ' - ' || TO_CHAR(TRUNC (ADD_MONTHS (SYSDATE - 1, - 9)),'DD/MM/YYYY')  AS PERIODO10
      , TO_CHAR(TRUNC (ADD_MONTHS (SYSDATE, - 9)),'DD/MM/YYYY')  || ' - ' || TO_CHAR(TRUNC (ADD_MONTHS (SYSDATE - 1, - 8)),'DD/MM/YYYY')  AS PERIODO09
      , TO_CHAR(TRUNC (ADD_MONTHS (SYSDATE, - 8)),'DD/MM/YYYY')  || ' - ' || TO_CHAR(TRUNC (ADD_MONTHS (SYSDATE - 1, - 7)),'DD/MM/YYYY')  AS PERIODO08
      , TO_CHAR(TRUNC (ADD_MONTHS (SYSDATE, - 7)),'DD/MM/YYYY')  || ' - ' || TO_CHAR(TRUNC (ADD_MONTHS (SYSDATE - 1, - 6)),'DD/MM/YYYY')  AS PERIODO07
      , TO_CHAR(TRUNC (ADD_MONTHS (SYSDATE, - 6)),'DD/MM/YYYY')  || ' - ' || TO_CHAR(TRUNC (ADD_MONTHS (SYSDATE - 1, - 5)),'DD/MM/YYYY')  AS PERIODO06
      , TO_CHAR(TRUNC (ADD_MONTHS (SYSDATE, - 5)),'DD/MM/YYYY')  || ' - ' || TO_CHAR(TRUNC (ADD_MONTHS (SYSDATE - 1, - 4)),'DD/MM/YYYY')  AS PERIODO05
      , TO_CHAR(TRUNC (ADD_MONTHS (SYSDATE, - 4)),'DD/MM/YYYY')  || ' - ' || TO_CHAR(TRUNC (ADD_MONTHS (SYSDATE - 1, - 3)),'DD/MM/YYYY')  AS PERIODO04
      , TO_CHAR(TRUNC (ADD_MONTHS (SYSDATE, - 3)),'DD/MM/YYYY')  || ' - ' || TO_CHAR(TRUNC (ADD_MONTHS (SYSDATE - 1, - 2)),'DD/MM/YYYY')  AS PERIODO03
      , TO_CHAR(TRUNC (ADD_MONTHS (SYSDATE, - 2)),'DD/MM/YYYY')  || ' - ' || TO_CHAR(TRUNC (ADD_MONTHS (SYSDATE - 1, - 1)),'DD/MM/YYYY')  AS PERIODO02
      , TO_CHAR(TRUNC (ADD_MONTHS (SYSDATE, - 1)),'DD/MM/YYYY')  || ' - ' || TO_CHAR(TRUNC (SYSDATE - 1),'DD/MM/YYYY')                    AS PERIODO01
   FROM DUAL);

UPDATE ANALISE_COMPRAS_NOVA UP 
   SET (UP.MEDPONCOM, UP.MEDPONVEN) =
(SELECT CASE WHEN
             CASE WHEN COMLIQ01 = 0 THEN 0 ELSE COMLIQ01 * 12 END +
             CASE WHEN COMLIQ02 = 0 THEN 0 ELSE COMLIQ02 * 11 END +
             CASE WHEN COMLIQ03 = 0 THEN 0 ELSE COMLIQ03 * 10 END +
             CASE WHEN COMLIQ04 = 0 THEN 0 ELSE COMLIQ04 *  9 END +
             CASE WHEN COMLIQ05 = 0 THEN 0 ELSE COMLIQ05 *  8 END +
             CASE WHEN COMLIQ06 = 0 THEN 0 ELSE COMLIQ06 *  7 END +
             CASE WHEN COMLIQ07 = 0 THEN 0 ELSE COMLIQ07 *  6 END +
             CASE WHEN COMLIQ08 = 0 THEN 0 ELSE COMLIQ08 *  5 END +
             CASE WHEN COMLIQ09 = 0 THEN 0 ELSE COMLIQ09 *  4 END +
             CASE WHEN COMLIQ10 = 0 THEN 0 ELSE COMLIQ10 *  3 END +
             CASE WHEN COMLIQ11 = 0 THEN 0 ELSE COMLIQ11 *  2 END +
             CASE WHEN COMLIQ12 = 0 THEN 0 ELSE COMLIQ12 *  1 END > 0  AND
             CASE WHEN COMLIQ01 = 0 THEN 0 ELSE 12 END +
             CASE WHEN COMLIQ02 = 0 THEN 0 ELSE 11 END +
             CASE WHEN COMLIQ03 = 0 THEN 0 ELSE 10 END +
             CASE WHEN COMLIQ04 = 0 THEN 0 ELSE  9 END +
             CASE WHEN COMLIQ05 = 0 THEN 0 ELSE  8 END +
             CASE WHEN COMLIQ06 = 0 THEN 0 ELSE  7 END +
             CASE WHEN COMLIQ07 = 0 THEN 0 ELSE  6 END +
             CASE WHEN COMLIQ08 = 0 THEN 0 ELSE  5 END +
             CASE WHEN COMLIQ09 = 0 THEN 0 ELSE  4 END +
             CASE WHEN COMLIQ10 = 0 THEN 0 ELSE  3 END +
             CASE WHEN COMLIQ11 = 0 THEN 0 ELSE  2 END +
             CASE WHEN COMLIQ12 = 0 THEN 0 ELSE  1 END > 0 
        THEN ROUND((CASE WHEN COMLIQ01 = 0 THEN 0 ELSE COMLIQ01 * 12 END +
                    CASE WHEN COMLIQ02 = 0 THEN 0 ELSE COMLIQ02 * 11 END +
                    CASE WHEN COMLIQ03 = 0 THEN 0 ELSE COMLIQ03 * 10 END +
                    CASE WHEN COMLIQ04 = 0 THEN 0 ELSE COMLIQ04 *  9 END +
                    CASE WHEN COMLIQ05 = 0 THEN 0 ELSE COMLIQ05 *  8 END +
                    CASE WHEN COMLIQ06 = 0 THEN 0 ELSE COMLIQ06 *  7 END +
                    CASE WHEN COMLIQ07 = 0 THEN 0 ELSE COMLIQ07 *  6 END +
                    CASE WHEN COMLIQ08 = 0 THEN 0 ELSE COMLIQ08 *  5 END +
                    CASE WHEN COMLIQ09 = 0 THEN 0 ELSE COMLIQ09 *  4 END +
                    CASE WHEN COMLIQ10 = 0 THEN 0 ELSE COMLIQ10 *  3 END +
                    CASE WHEN COMLIQ11 = 0 THEN 0 ELSE COMLIQ11 *  2 END +
                    CASE WHEN COMLIQ12 = 0 THEN 0 ELSE COMLIQ12 *  1 END ) / (
                    CASE WHEN COMLIQ01 = 0 THEN 0 ELSE 12 END +
                    CASE WHEN COMLIQ02 = 0 THEN 0 ELSE 11 END +
                    CASE WHEN COMLIQ03 = 0 THEN 0 ELSE 10 END +
                    CASE WHEN COMLIQ04 = 0 THEN 0 ELSE  9 END +
                    CASE WHEN COMLIQ05 = 0 THEN 0 ELSE  8 END +
                    CASE WHEN COMLIQ06 = 0 THEN 0 ELSE  7 END +
                    CASE WHEN COMLIQ07 = 0 THEN 0 ELSE  6 END +
                    CASE WHEN COMLIQ08 = 0 THEN 0 ELSE  5 END +
                    CASE WHEN COMLIQ09 = 0 THEN 0 ELSE  4 END +
                    CASE WHEN COMLIQ10 = 0 THEN 0 ELSE  3 END +
                    CASE WHEN COMLIQ11 = 0 THEN 0 ELSE  2 END +
                    CASE WHEN COMLIQ12 = 0 THEN 0 ELSE  1 END ),0) 
        ELSE 0 END AS MEDPONCOM
   , CASE WHEN
          CASE WHEN VENLIQ01 = 0 THEN 0 ELSE VENLIQ01 * 12 END +
          CASE WHEN VENLIQ02 = 0 THEN 0 ELSE VENLIQ02 * 11 END +
          CASE WHEN VENLIQ03 = 0 THEN 0 ELSE VENLIQ03 * 10 END +
          CASE WHEN VENLIQ04 = 0 THEN 0 ELSE VENLIQ04 *  9 END +
          CASE WHEN VENLIQ05 = 0 THEN 0 ELSE VENLIQ05 *  8 END +
          CASE WHEN VENLIQ06 = 0 THEN 0 ELSE VENLIQ06 *  7 END +
          CASE WHEN VENLIQ07 = 0 THEN 0 ELSE VENLIQ07 *  6 END +
          CASE WHEN VENLIQ08 = 0 THEN 0 ELSE VENLIQ08 *  5 END +
          CASE WHEN VENLIQ09 = 0 THEN 0 ELSE VENLIQ09 *  4 END +
          CASE WHEN VENLIQ10 = 0 THEN 0 ELSE VENLIQ10 *  3 END +
          CASE WHEN VENLIQ11 = 0 THEN 0 ELSE VENLIQ11 *  2 END +
          CASE WHEN VENLIQ12 = 0 THEN 0 ELSE VENLIQ12 *  1 END > 0  AND
          CASE WHEN VENLIQ01 = 0 THEN 0 ELSE 12 END +
          CASE WHEN VENLIQ02 = 0 THEN 0 ELSE 11 END +
          CASE WHEN VENLIQ03 = 0 THEN 0 ELSE 10 END +
          CASE WHEN VENLIQ04 = 0 THEN 0 ELSE  9 END +
          CASE WHEN VENLIQ05 = 0 THEN 0 ELSE  8 END +
          CASE WHEN VENLIQ06 = 0 THEN 0 ELSE  7 END +
          CASE WHEN VENLIQ07 = 0 THEN 0 ELSE  6 END +
          CASE WHEN VENLIQ08 = 0 THEN 0 ELSE  5 END +
          CASE WHEN VENLIQ09 = 0 THEN 0 ELSE  4 END +
          CASE WHEN VENLIQ10 = 0 THEN 0 ELSE  3 END +
          CASE WHEN VENLIQ11 = 0 THEN 0 ELSE  2 END +
          CASE WHEN VENLIQ12 = 0 THEN 0 ELSE  1 END > 0 
    THEN ROUND((CASE WHEN VENLIQ01 = 0 THEN 0 ELSE VENLIQ01 * 12 END +
                CASE WHEN VENLIQ02 = 0 THEN 0 ELSE VENLIQ02 * 11 END +
                CASE WHEN VENLIQ03 = 0 THEN 0 ELSE VENLIQ03 * 10 END +
                CASE WHEN VENLIQ04 = 0 THEN 0 ELSE VENLIQ04 *  9 END +
                CASE WHEN VENLIQ05 = 0 THEN 0 ELSE VENLIQ05 *  8 END +
                CASE WHEN VENLIQ06 = 0 THEN 0 ELSE VENLIQ06 *  7 END +
                CASE WHEN VENLIQ07 = 0 THEN 0 ELSE VENLIQ07 *  6 END +
                CASE WHEN VENLIQ08 = 0 THEN 0 ELSE VENLIQ08 *  5 END +
                CASE WHEN VENLIQ09 = 0 THEN 0 ELSE VENLIQ09 *  4 END +
                CASE WHEN VENLIQ10 = 0 THEN 0 ELSE VENLIQ10 *  3 END +
                CASE WHEN VENLIQ11 = 0 THEN 0 ELSE VENLIQ11 *  2 END +
                CASE WHEN VENLIQ12 = 0 THEN 0 ELSE VENLIQ12 *  1 END ) / (
                CASE WHEN VENLIQ01 = 0 THEN 0 ELSE 12 END +
                CASE WHEN VENLIQ02 = 0 THEN 0 ELSE 11 END +
                CASE WHEN VENLIQ03 = 0 THEN 0 ELSE 10 END +
                CASE WHEN VENLIQ04 = 0 THEN 0 ELSE  9 END +
                CASE WHEN VENLIQ05 = 0 THEN 0 ELSE  8 END +
                CASE WHEN VENLIQ06 = 0 THEN 0 ELSE  7 END +
                CASE WHEN VENLIQ07 = 0 THEN 0 ELSE  6 END +
                CASE WHEN VENLIQ08 = 0 THEN 0 ELSE  5 END +
                CASE WHEN VENLIQ09 = 0 THEN 0 ELSE  4 END +
                CASE WHEN VENLIQ10 = 0 THEN 0 ELSE  3 END +
                CASE WHEN VENLIQ11 = 0 THEN 0 ELSE  2 END +
                CASE WHEN VENLIQ12 = 0 THEN 0 ELSE  1 END ),0) 
    ELSE 0 END AS MEDPONVEN
  FROM ANALISE_COMPRAS_NOVA
 WHERE ANALISE_COMPRAS_NOVA.CODPROD = UP.CODPROD
   AND ANALISE_COMPRAS_NOVA.CONTROLE = UP.CONTROLE
   AND ANALISE_COMPRAS_NOVA.PK_CODEMP = UP.PK_CODEMP);

UPDATE ANALISE_COMPRAS_NOVA UP 
   SET (DESVEN01, DESVEN02, DESVEN03, DESVEN04, DESVEN05, DESVEN06,
        DESVEN07, DESVEN08, DESVEN09, DESVEN10, DESVEN11, DESVEN12,
        DESCOM01, DESCOM02, DESCOM03, DESCOM04, DESCOM05, DESCOM06,
        DESCOM07, DESCOM08, DESCOM09, DESCOM10, DESCOM11, DESCOM12) =
(SELECT ROUND(CASE WHEN VENLIQ01 > 0 AND MEDPONVEN > 0 THEN SNK_DIVIDIR(VENLIQ01, MEDPONVEN) ELSE 0 END,4) AS DESVEN01
      , ROUND(CASE WHEN VENLIQ02 > 0 AND MEDPONVEN > 0 THEN SNK_DIVIDIR(VENLIQ02, MEDPONVEN) ELSE 0 END,4) AS DESVEN02
      , ROUND(CASE WHEN VENLIQ03 > 0 AND MEDPONVEN > 0 THEN SNK_DIVIDIR(VENLIQ03, MEDPONVEN) ELSE 0 END,4) AS DESVEN03
      , ROUND(CASE WHEN VENLIQ04 > 0 AND MEDPONVEN > 0 THEN SNK_DIVIDIR(VENLIQ04, MEDPONVEN) ELSE 0 END,4) AS DESVEN04
      , ROUND(CASE WHEN VENLIQ05 > 0 AND MEDPONVEN > 0 THEN SNK_DIVIDIR(VENLIQ05, MEDPONVEN) ELSE 0 END,4) AS DESVEN05
      , ROUND(CASE WHEN VENLIQ06 > 0 AND MEDPONVEN > 0 THEN SNK_DIVIDIR(VENLIQ06, MEDPONVEN) ELSE 0 END,4) AS DESVEN06
      , ROUND(CASE WHEN VENLIQ07 > 0 AND MEDPONVEN > 0 THEN SNK_DIVIDIR(VENLIQ07, MEDPONVEN) ELSE 0 END,4) AS DESVEN07
      , ROUND(CASE WHEN VENLIQ08 > 0 AND MEDPONVEN > 0 THEN SNK_DIVIDIR(VENLIQ08, MEDPONVEN) ELSE 0 END,4) AS DESVEN08
      , ROUND(CASE WHEN VENLIQ09 > 0 AND MEDPONVEN > 0 THEN SNK_DIVIDIR(VENLIQ09, MEDPONVEN) ELSE 0 END,4) AS DESVEN09
      , ROUND(CASE WHEN VENLIQ10 > 0 AND MEDPONVEN > 0 THEN SNK_DIVIDIR(VENLIQ10, MEDPONVEN) ELSE 0 END,4) AS DESVEN10
      , ROUND(CASE WHEN VENLIQ11 > 0 AND MEDPONVEN > 0 THEN SNK_DIVIDIR(VENLIQ11, MEDPONVEN) ELSE 0 END,4) AS DESVEN11
      , ROUND(CASE WHEN VENLIQ12 > 0 AND MEDPONVEN > 0 THEN SNK_DIVIDIR(VENLIQ12, MEDPONVEN) ELSE 0 END,4) AS DESVEN12
      , ROUND(CASE WHEN COMLIQ01 > 0 AND MEDPONCOM > 0 THEN SNK_DIVIDIR(COMLIQ01, MEDPONCOM) ELSE 0 END,4) AS DESCOM01
      , ROUND(CASE WHEN COMLIQ02 > 0 AND MEDPONCOM > 0 THEN SNK_DIVIDIR(COMLIQ02, MEDPONCOM) ELSE 0 END,4) AS DESCOM02
      , ROUND(CASE WHEN COMLIQ03 > 0 AND MEDPONCOM > 0 THEN SNK_DIVIDIR(COMLIQ03, MEDPONCOM) ELSE 0 END,4) AS DESCOM03
      , ROUND(CASE WHEN COMLIQ04 > 0 AND MEDPONCOM > 0 THEN SNK_DIVIDIR(COMLIQ04, MEDPONCOM) ELSE 0 END,4) AS DESCOM04
      , ROUND(CASE WHEN COMLIQ05 > 0 AND MEDPONCOM > 0 THEN SNK_DIVIDIR(COMLIQ05, MEDPONCOM) ELSE 0 END,4) AS DESCOM05
      , ROUND(CASE WHEN COMLIQ06 > 0 AND MEDPONCOM > 0 THEN SNK_DIVIDIR(COMLIQ06, MEDPONCOM) ELSE 0 END,4) AS DESCOM06
      , ROUND(CASE WHEN COMLIQ07 > 0 AND MEDPONCOM > 0 THEN SNK_DIVIDIR(COMLIQ07, MEDPONCOM) ELSE 0 END,4) AS DESCOM07
      , ROUND(CASE WHEN COMLIQ08 > 0 AND MEDPONCOM > 0 THEN SNK_DIVIDIR(COMLIQ08, MEDPONCOM) ELSE 0 END,4) AS DESCOM08
      , ROUND(CASE WHEN COMLIQ09 > 0 AND MEDPONCOM > 0 THEN SNK_DIVIDIR(COMLIQ09, MEDPONCOM) ELSE 0 END,4) AS DESCOM09
      , ROUND(CASE WHEN COMLIQ10 > 0 AND MEDPONCOM > 0 THEN SNK_DIVIDIR(COMLIQ10, MEDPONCOM) ELSE 0 END,4) AS DESCOM10
      , ROUND(CASE WHEN COMLIQ11 > 0 AND MEDPONCOM > 0 THEN SNK_DIVIDIR(COMLIQ11, MEDPONCOM) ELSE 0 END,4) AS DESCOM11
      , ROUND(CASE WHEN COMLIQ12 > 0 AND MEDPONCOM > 0 THEN SNK_DIVIDIR(COMLIQ12, MEDPONCOM) ELSE 0 END,4) AS DESCOM12
   FROM ANALISE_COMPRAS_NOVA 
  WHERE ANALISE_COMPRAS_NOVA.CODPROD = UP.CODPROD 
    AND ANALISE_COMPRAS_NOVA.CONTROLE = UP.CONTROLE 
    AND ANALISE_COMPRAS_NOVA.PK_CODEMP = UP.PK_CODEMP);

UPDATE ANALISE_COMPRAS_NOVA UP SET (DESPDVEN, DESPDCOM) =
(
SELECT ROUND(((((((((((((((((((((((DESVEN12 + DESVEN11) / 2) + DESVEN10) / 2) + DESVEN09) / 2) + DESVEN08) / 2) + DESVEN07) / 2) + DESVEN06) / 2) + DESVEN05) / 2) + DESVEN04) / 2) + DESVEN03) / 2) + DESVEN02) / 2) + DESVEN01) / 2),4) AS DESPDVEN,
    ROUND(((((((((((((((((((((((DESCOM12 + DESCOM11) / 2) + DESCOM10) / 2) + DESCOM09) / 2) + DESCOM08) / 2) + DESCOM07) / 2) + DESCOM06) / 2) + DESCOM05) / 2) + DESCOM04) / 2) + DESCOM03) / 2) + DESCOM02) / 2) + DESCOM01) / 2),4) AS DESPDCOM
  FROM ANALISE_COMPRAS_NOVA 
 WHERE ANALISE_COMPRAS_NOVA.CODPROD = UP.CODPROD 
   AND ANALISE_COMPRAS_NOVA.CONTROLE = UP.CONTROLE 
   AND ANALISE_COMPRAS_NOVA.PK_CODEMP = UP.PK_CODEMP);

UPDATE ANALISE_COMPRAS_NOVA UP 
   SET (UP.TKVEN12
      , UP.TKVEN11
      , UP.TKVEN10
      , UP.TKVEN09
      , UP.TKVEN08
      , UP.TKVEN07
      , UP.TKVEN06
      , UP.TKVEN05
      , UP.TKVEN04
      , UP.TKVEN03
      , UP.TKVEN02
      , UP.TKVEN01) =
(SELECT TRUNC(CASE WHEN COM.QTDVE12 = 0 THEN 0 ELSE SNK_DIVIDIR(COM.VENLIQ12, COM.QTDVE12) END),
        TRUNC(CASE WHEN COM.QTDVE11 = 0 THEN 0 ELSE SNK_DIVIDIR(COM.VENLIQ11, COM.QTDVE11) END),
        TRUNC(CASE WHEN COM.QTDVE10 = 0 THEN 0 ELSE SNK_DIVIDIR(COM.VENLIQ10, COM.QTDVE10) END),
        TRUNC(CASE WHEN COM.QTDVE09 = 0 THEN 0 ELSE SNK_DIVIDIR(COM.VENLIQ09, COM.QTDVE09) END),
        TRUNC(CASE WHEN COM.QTDVE08 = 0 THEN 0 ELSE SNK_DIVIDIR(COM.VENLIQ08, COM.QTDVE08) END),
        TRUNC(CASE WHEN COM.QTDVE07 = 0 THEN 0 ELSE SNK_DIVIDIR(COM.VENLIQ07, COM.QTDVE07) END),
        TRUNC(CASE WHEN COM.QTDVE06 = 0 THEN 0 ELSE SNK_DIVIDIR(COM.VENLIQ06, COM.QTDVE06) END),
        TRUNC(CASE WHEN COM.QTDVE05 = 0 THEN 0 ELSE SNK_DIVIDIR(COM.VENLIQ05, COM.QTDVE05) END),
        TRUNC(CASE WHEN COM.QTDVE04 = 0 THEN 0 ELSE SNK_DIVIDIR(COM.VENLIQ04, COM.QTDVE04) END),
        TRUNC(CASE WHEN COM.QTDVE03 = 0 THEN 0 ELSE SNK_DIVIDIR(COM.VENLIQ03, COM.QTDVE03) END),
        TRUNC(CASE WHEN COM.QTDVE02 = 0 THEN 0 ELSE SNK_DIVIDIR(COM.VENLIQ02, COM.QTDVE02) END),
        TRUNC(CASE WHEN COM.QTDVE01 = 0 THEN 0 ELSE SNK_DIVIDIR(COM.VENLIQ01, COM.QTDVE01) END)
   FROM ANALISE_COMPRAS_NOVA COM
  WHERE COM.CODPROD = UP.CODPROD
    AND COM.CONTROLE = UP.CONTROLE
    AND COM.PK_CODEMP = UP.PK_CODEMP);

UPDATE ANALISE_COMPRAS_NOVA UP SET MEDIAPVEND =
NVL((SELECT ROUND(MEDPONVEN * DESPDVEN) FROM ANALISE_COMPRAS_NOVA
WHERE ANALISE_COMPRAS_NOVA.CODPROD = UP.CODPROD 
  AND ANALISE_COMPRAS_NOVA.CONTROLE = UP.CONTROLE 
  AND ANALISE_COMPRAS_NOVA.PK_CODEMP = UP.PK_CODEMP),0);

UPDATE ANALISE_COMPRAS_NOVA UP
   SET ESTATUAL =
NVL((SELECT NVL(SUM(EST.ESTOQUE),0)
   FROM TGFEST EST
  WHERE EST.CODLOCAL IN (1, 3, 5)
    AND EST.CODEMP = UP.PK_CODEMP
    AND EST.CODPROD = UP.CODPROD
    AND EST.CONTROLE = UP.CONTROLE),0);

UPDATE ANALISE_COMPRAS_NOVA COM
   SET COM.PERIPI =
NVL((SELECT Snk_Dividir(IPI.PERCENTUAL, 100) AS PERIPI
  FROM TGFPRO PRO
     , TGFIPI IPI
 WHERE PRO.CODPROD    =   COM.CODPROD
   AND IPI.CODIPI     =   PRO.CODIPI),0);

 UPDATE ANALISE_COMPRAS_NOVA UP
    SET UP.PEDSOLCOM =
(SELECT NVL(SUM(ITE.QTDNEG), 0) AS QTDNEG
   FROM TGFITE ITE
INNER JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA
WHERE CAB.CODTIPOPER   =   6
  AND ITE.PENDENTE     =   'S'
  AND ITE.CODPROD      =   UP.CODPROD
  AND ITE.CONTROLE     =   UP.CONTROLE);

UPDATE ANALISE_COMPRAS_NOVA UP 
   SET (ESTMIN, ESTMAX) =
(SELECT TRUNC(SNK_DIVIDIR(CASE WHEN MEDIAPVEND = 0 THEN 0 
                   ELSE (MEDIAPVEND / 28) * CASE WHEN PK_CODEMP IN (41,51) THEN 1 
                                                 ELSE 
                   TRUNC(CASE WHEN PRAZOENTR <= 0 THEN 1 
                                                       ELSE PRAZOENTR END)
                                                 END 
                                                       END, QTDEMB) + 0.99) * QTDEMB AS ESTMIN
      , TRUNC(SNK_DIVIDIR(CASE WHEN PK_CODEMP IN (1,31) 
                               THEN NVL(ROUND(AD_MESESTMAX * MEDIAPVEND) + 
                                    ROUND(CASE WHEN MEDIAPVEND = 0 THEN 0 
                                                ELSE (MEDIAPVEND / 28) * TRUNC(CASE WHEN PRAZOENTR <= 0 THEN 1 
                                                                                    ELSE PRAZOENTR END) END),0)
                               ELSE MEDIAPVEND END, QTDEMB) + 0.99) * QTDEMB AS ESTMAX
 FROM ANALISE_COMPRAS_NOVA 
WHERE ANALISE_COMPRAS_NOVA.CODPROD = UP.CODPROD 
  AND ANALISE_COMPRAS_NOVA.CONTROLE = UP.CONTROLE 
  AND ANALISE_COMPRAS_NOVA.PK_CODEMP = UP.PK_CODEMP);

UPDATE ANALISE_COMPRAS_NOVA UP 
   SET ESTEXC =
(SELECT TRUNC(CASE WHEN ESTATUAL > ESTMAX THEN ESTATUAL - ESTMAX ELSE 0 END) AS ESTEXC 
 FROM ANALISE_COMPRAS_NOVA 
WHERE ANALISE_COMPRAS_NOVA.CODPROD = UP.CODPROD 
  AND ANALISE_COMPRAS_NOVA.CONTROLE = UP.CONTROLE 
  AND ANALISE_COMPRAS_NOVA.PK_CODEMP = UP.PK_CODEMP);

UPDATE ANALISE_COMPRAS_NOVA UP 
   SET ESTEXCTOT =
(SELECT SUM(TRUNC(CASE WHEN ESTATUAL > ESTMAX THEN ESTATUAL - ESTMAX ELSE 0 END)) AS ESTEXCTOT
   FROM ANALISE_COMPRAS_NOVA 
  WHERE ANALISE_COMPRAS_NOVA.CODPROD = UP.CODPROD 
    AND ANALISE_COMPRAS_NOVA.CONTROLE = UP.CONTROLE);

/*
-----------------------------------------------
CALCULO DE PRODUTOS ALTERNATIVOS
EFETUAR A SOMA DE TODOS OS PRODUTOS
ALTERNATIVOS PARA SOMAR COM O PRODUTO PRINCIPAL
-----------------------------------------------
*/

UPDATE ANALISE_COMPRAS_NOVA UP
   SET (ESTATUAL, ESTMIN, MEDIAPVEND, SOMPEDPEN, ESTMAX, ESTEXC) =
(SELECT ESTATUAL
      , ESTMIN
      , MEDIAPVEND
      , SOMPEDPEN
      , ESTMAX
      , ESTEXC
FROM
   (SELECT PK_CODEMP
     , CODPROD
     , CONTROLE
     , NVL(SUM(UNIAO.ESTATUAL), 0) AS ESTATUAL
     , NVL(SUM(UNIAO.ESTMIN), 0) AS ESTMIN
     , NVL(SUM(UNIAO.MEDIAPVEND), 0) AS MEDIAPVEND
     , NVL(SUM(UNIAO.SOMPEDPEN), 0) AS SOMPEDPEN
     , NVL(SUM(UNIAO.ESTMAX), 0) AS ESTMAX
     , NVL(SUM(UNIAO.ESTEXC), 0) AS ESTEXC
  FROM
(SELECT COM.PK_CODEMP
     , PAL.CODPROD
     , NVL(COM.CONTROLE, ' ') AS CONTROLE
     , NVL(COM.ESTATUAL, 0) AS ESTATUAL
     , NVL(COM.ESTMIN, 0) AS ESTMIN
     , NVL(COM.MEDIAPVEND, 0) AS MEDIAPVEND
     , NVL(COM.SOMPEDPEN, 0) AS SOMPEDPEN
     , NVL(COM.ESTMAX, 0) AS ESTMAX
     , NVL(COM.ESTEXC, 0) AS ESTEXC
 FROM ANALISE_COMPRAS_NOVA COM
    , TGFPAL PAL
WHERE COM.CODPROD = PAL.CODPRODALT
UNION
SELECT COM.PK_CODEMP
     , PAL.CODPROD
     , NVL(COM.CONTROLE, ' ') AS CONTROLE
     , NVL(COM.ESTATUAL, 0) AS ESTATUAL
     , NVL(COM.ESTMIN, 0) AS ESTMIN
     , NVL(COM.MEDIAPVEND, 0) AS MEDIAPVEND
     , NVL(COM.SOMPEDPEN, 0) AS SOMPEDPEN
     , NVL(COM.ESTMAX, 0) AS ESTMAX
     , NVL(COM.ESTEXC, 0) AS ESTEXC
 FROM ANALISE_COMPRAS_NOVA COM
    , TGFPAL PAL
WHERE COM.CODPROD = PAL.CODPROD) UNIAO
GROUP BY PK_CODEMP, CODPROD, CONTROLE) ANA
WHERE ANA.PK_CODEMP = UP.PK_CODEMP
  AND ANA.CODPROD = UP.CODPROD
  AND ANA.CONTROLE = UP.CONTROLE)
 WHERE UP.CODPROD IN (SELECT CODPROD FROM TGFPAL);

UPDATE ANALISE_COMPRAS_NOVA UP
   SET (ESTATUAL, ESTMIN, MEDIAPVEND, AD_MESESTMAX, SOMPEDPEN, ESTMAX, ESTEXC) =
   (SELECT 0,0,0,0,0,0,0 FROM DUAL)
 WHERE UP.CODPROD IN (SELECT CODPRODALT FROM TGFPAL)
   AND UP.CODPROD IN (SELECT CODPROD FROM TGFPRO WHERE AD_SOMANCOM = 'N' AND SOLCOMPRA = 'N');

UPDATE ANALISE_COMPRAS_NOVA UP
   SET (SUGESTAO, VLRSUGESTAO) =
(SELECT CASE WHEN ESTATUAL <= SNK_DIVIDIR(ESTMAX,2) THEN ESTMAX - ESTATUAL
             WHEN ESTATUAL > ESTMAX THEN ESTMAX - ESTATUAL
             ELSE 0
         END AS SUGESTAO,
        CASE WHEN ESTATUAL <= SNK_DIVIDIR(ESTMAX,2) THEN ESTMAX - ESTATUAL
             WHEN ESTATUAL > ESTMAX THEN ESTMAX - ESTATUAL
             ELSE 0
         END * ROUND(NVL(CUSREP, 0), 2) AS VLRSUGESTAO
  FROM ANALISE_COMPRAS_NOVA
  WHERE ANALISE_COMPRAS_NOVA.CODPROD = UP.CODPROD 
   AND ANALISE_COMPRAS_NOVA.CONTROLE = UP.CONTROLE
   AND ANALISE_COMPRAS_NOVA.PK_CODEMP = UP.PK_CODEMP);

-- Remove lixo na base de dados
DELETE FROM ANALISE_COMPRAS_NOVA
 WHERE CODPARC IS NULL
   AND SUGESTAO <= 0;

COMMIT;
END;
