/*

     , CAST (ROUND(CASE WHEN FIN.COUNT_01 = 0 THEN 0 ELSE SNK_DIVIDIR(FIN.VLRDESDOB_01, FIN.COUNT_01) END, 2) AS FLOAT(126)) AS TKVEN_01
     , CAST (ROUND(CASE WHEN FIN.COUNT_02 = 0 THEN 0 ELSE SNK_DIVIDIR(FIN.VLRDESDOB_02, FIN.COUNT_02) END, 2) AS FLOAT(126)) AS TKVEN_02
     , CAST (ROUND(CASE WHEN FIN.COUNT_03 = 0 THEN 0 ELSE SNK_DIVIDIR(FIN.VLRDESDOB_03, FIN.COUNT_03) END, 2) AS FLOAT(126)) AS TKVEN_03
     , CAST (ROUND(CASE WHEN FIN.COUNT_04 = 0 THEN 0 ELSE SNK_DIVIDIR(FIN.VLRDESDOB_04, FIN.COUNT_04) END, 2) AS FLOAT(126)) AS TKVEN_04
     , CAST (ROUND(CASE WHEN FIN.COUNT_05 = 0 THEN 0 ELSE SNK_DIVIDIR(FIN.VLRDESDOB_05, FIN.COUNT_05) END, 2) AS FLOAT(126)) AS TKVEN_05
     , CAST (ROUND(CASE WHEN FIN.COUNT_06 = 0 THEN 0 ELSE SNK_DIVIDIR(FIN.VLRDESDOB_06, FIN.COUNT_06) END, 2) AS FLOAT(126)) AS TKVEN_06
     , CAST (ROUND(CASE WHEN FIN.COUNT_06 = 0 THEN 0 ELSE SNK_DIVIDIR(FIN.VLRDESDOB_TOT, FIN.COUNT_TOT) END, 2) AS FLOAT(126)) AS TKVEN_TOT


     , CAST (ROUND(SNK_DIVIDIR((SNK_DIVIDIR((SNK_DIVIDIR((SNK_DIVIDIR((SNK_DIVIDIR((FIN.DESVEN06 + FIN.DESVEN05), 2) + FIN.DESVEN04), 2) + FIN.DESVEN03), 2) + FIN.DESVEN02), 2) + FIN.DESVEN01), 2), 2) AS FLOAT(126)) AS DESPDVEN
     , CAST (ROUND((SNK_DIVIDIR((SNK_DIVIDIR((SNK_DIVIDIR((SNK_DIVIDIR((SNK_DIVIDIR((FIN.DESVEN06 + FIN.DESVEN05), 2) + FIN.DESVEN04), 2) + FIN.DESVEN03), 2) + FIN.DESVEN02), 2) + FIN.DESVEN01), 2) * FIN.MEDPONVEN), 2) AS FLOAT(126)) AS MEDIAPVEND

*/

CREATE OR REPLACE VIEW VW_ANALISE_CREDITO AS
SELECT CAST (FIN.CODEMP AS NUMBER(5)) AS CODEMP
     , CAST (FIN.CODPARC AS NUMBER(10)) AS CODPARC
     , CAST (FIN.CODVEND AS NUMBER(5)) AS CODVEND
     , CAST (FIN.VLRDESDOB_01 AS FLOAT(126)) AS VLRDESDOB_01
     , CAST (FIN.VLRDESDOB_02 AS FLOAT(126)) AS VLRDESDOB_02
     , CAST (FIN.VLRDESDOB_03 AS FLOAT(126)) AS VLRDESDOB_03
     , CAST (FIN.VLRDESDOB_04 AS FLOAT(126)) AS VLRDESDOB_04
     , CAST (FIN.VLRDESDOB_05 AS FLOAT(126)) AS VLRDESDOB_05
     , CAST (FIN.VLRDESDOB_06 AS FLOAT(126)) AS VLRDESDOB_06
     , CAST (FIN.VLRDESDOB_TOT AS FLOAT(126)) AS VLRDESDOB_TOT
     , CAST (FIN.COUNT_01 AS INTEGER) AS COUNT_01
     , CAST (FIN.COUNT_02 AS INTEGER) AS COUNT_02
     , CAST (FIN.COUNT_03 AS INTEGER) AS COUNT_03
     , CAST (FIN.COUNT_04 AS INTEGER) AS COUNT_04
     , CAST (FIN.COUNT_05 AS INTEGER) AS COUNT_05
     , CAST (FIN.COUNT_06 AS INTEGER) AS COUNT_06
     , CAST (FIN.COUNT_TOT AS INTEGER) AS COUNT_TOT
     , CAST (FIN.MEDPONVEN AS FLOAT(126)) AS MEDPONVEN
     , CAST (ROUND(CASE WHEN FIN.VLRDESDOB_01 > 0 AND FIN.MEDPONVEN > 0 THEN SNK_DIVIDIR(FIN.VLRDESDOB_01, FIN.MEDPONVEN) ELSE 0 END,4) AS FLOAT(126)) AS DESVEN01
     , CAST (ROUND(CASE WHEN FIN.VLRDESDOB_02 > 0 AND FIN.MEDPONVEN > 0 THEN SNK_DIVIDIR(FIN.VLRDESDOB_02, FIN.MEDPONVEN) ELSE 0 END,4) AS FLOAT(126)) AS DESVEN02
     , CAST (ROUND(CASE WHEN FIN.VLRDESDOB_03 > 0 AND FIN.MEDPONVEN > 0 THEN SNK_DIVIDIR(FIN.VLRDESDOB_03, FIN.MEDPONVEN) ELSE 0 END,4) AS FLOAT(126)) AS DESVEN03
     , CAST (ROUND(CASE WHEN FIN.VLRDESDOB_04 > 0 AND FIN.MEDPONVEN > 0 THEN SNK_DIVIDIR(FIN.VLRDESDOB_04, FIN.MEDPONVEN) ELSE 0 END,4) AS FLOAT(126)) AS DESVEN04
     , CAST (ROUND(CASE WHEN FIN.VLRDESDOB_05 > 0 AND FIN.MEDPONVEN > 0 THEN SNK_DIVIDIR(FIN.VLRDESDOB_05, FIN.MEDPONVEN) ELSE 0 END,4) AS FLOAT(126)) AS DESVEN05
     , CAST (ROUND(CASE WHEN FIN.VLRDESDOB_06 > 0 AND FIN.MEDPONVEN > 0 THEN SNK_DIVIDIR(FIN.VLRDESDOB_06, FIN.MEDPONVEN) ELSE 0 END,4) AS FLOAT(126)) AS DESVEN06
     , CAST (ROUND(SNK_DIVIDIR((SNK_DIVIDIR((SNK_DIVIDIR((SNK_DIVIDIR((SNK_DIVIDIR((ROUND(CASE WHEN FIN.VLRDESDOB_06 > 0 AND FIN.MEDPONVEN > 0 THEN SNK_DIVIDIR(FIN.VLRDESDOB_06, FIN.MEDPONVEN) ELSE 0 END,4) + ROUND(CASE WHEN FIN.VLRDESDOB_05 > 0 AND FIN.MEDPONVEN > 0 THEN SNK_DIVIDIR(FIN.VLRDESDOB_05, FIN.MEDPONVEN) ELSE 0 END,4)), 2) + ROUND(CASE WHEN FIN.VLRDESDOB_04 > 0 AND FIN.MEDPONVEN > 0 THEN SNK_DIVIDIR(FIN.VLRDESDOB_04, FIN.MEDPONVEN) ELSE 0 END,4)), 2) + ROUND(CASE WHEN FIN.VLRDESDOB_03 > 0 AND FIN.MEDPONVEN > 0 THEN SNK_DIVIDIR(FIN.VLRDESDOB_03, FIN.MEDPONVEN) ELSE 0 END,4)), 2) + ROUND(CASE WHEN FIN.VLRDESDOB_02 > 0 AND FIN.MEDPONVEN > 0 THEN SNK_DIVIDIR(FIN.VLRDESDOB_02, FIN.MEDPONVEN) ELSE 0 END,4)), 2) + ROUND(CASE WHEN FIN.VLRDESDOB_01 > 0 AND FIN.MEDPONVEN > 0 THEN SNK_DIVIDIR(FIN.VLRDESDOB_01, FIN.MEDPONVEN) ELSE 0 END,4)), 2), 2) AS FLOAT(126)) AS DESPDVEN
     , CAST (ROUND((SNK_DIVIDIR((SNK_DIVIDIR((SNK_DIVIDIR((SNK_DIVIDIR((SNK_DIVIDIR((ROUND(CASE WHEN FIN.VLRDESDOB_06 > 0 AND FIN.MEDPONVEN > 0 THEN SNK_DIVIDIR(FIN.VLRDESDOB_06, FIN.MEDPONVEN) ELSE 0 END,4) + ROUND(CASE WHEN FIN.VLRDESDOB_05 > 0 AND FIN.MEDPONVEN > 0 THEN SNK_DIVIDIR(FIN.VLRDESDOB_05, FIN.MEDPONVEN) ELSE 0 END,4)), 2) + ROUND(CASE WHEN FIN.VLRDESDOB_04 > 0 AND FIN.MEDPONVEN > 0 THEN SNK_DIVIDIR(FIN.VLRDESDOB_04, FIN.MEDPONVEN) ELSE 0 END,4)), 2) + ROUND(CASE WHEN FIN.VLRDESDOB_03 > 0 AND FIN.MEDPONVEN > 0 THEN SNK_DIVIDIR(FIN.VLRDESDOB_03, FIN.MEDPONVEN) ELSE 0 END,4)), 2) + ROUND(CASE WHEN FIN.VLRDESDOB_02 > 0 AND FIN.MEDPONVEN > 0 THEN SNK_DIVIDIR(FIN.VLRDESDOB_02, FIN.MEDPONVEN) ELSE 0 END,4)), 2) + ROUND(CASE WHEN FIN.VLRDESDOB_01 > 0 AND FIN.MEDPONVEN > 0 THEN SNK_DIVIDIR(FIN.VLRDESDOB_01, FIN.MEDPONVEN) ELSE 0 END,4)), 2) * FIN.MEDPONVEN), 2) AS FLOAT(126)) AS MEDIAPVEND
FROM (
SELECT CAST (FIN.CODEMP AS NUMBER(5)) AS CODEMP
     , CAST (FIN.CODPARC AS NUMBER(10)) AS CODPARC
     , CAST (FIN.CODVEND AS NUMBER(5)) AS CODVEND
     , CAST (FIN.VLRDESDOB_01 AS FLOAT(126)) AS VLRDESDOB_01
     , CAST (FIN.VLRDESDOB_02 AS FLOAT(126)) AS VLRDESDOB_02
     , CAST (FIN.VLRDESDOB_03 AS FLOAT(126)) AS VLRDESDOB_03
     , CAST (FIN.VLRDESDOB_04 AS FLOAT(126)) AS VLRDESDOB_04
     , CAST (FIN.VLRDESDOB_05 AS FLOAT(126)) AS VLRDESDOB_05
     , CAST (FIN.VLRDESDOB_06 AS FLOAT(126)) AS VLRDESDOB_06
     , CAST (FIN.VLRDESDOB_TOT AS FLOAT(126)) AS VLRDESDOB_TOT
     , CAST (FIN.COUNT_01 AS INTEGER) AS COUNT_01
     , CAST (FIN.COUNT_02 AS INTEGER) AS COUNT_02
     , CAST (FIN.COUNT_03 AS INTEGER) AS COUNT_03
     , CAST (FIN.COUNT_04 AS INTEGER) AS COUNT_04
     , CAST (FIN.COUNT_05 AS INTEGER) AS COUNT_05
     , CAST (FIN.COUNT_06 AS INTEGER) AS COUNT_06
     , CAST (FIN.COUNT_TOT AS INTEGER) AS COUNT_TOT
     , CAST (ROUND(SNK_DIVIDIR((CASE WHEN FIN.VLRDESDOB_01 = 0 THEN 0 ELSE FIN.VLRDESDOB_01 * 6 END +
                                CASE WHEN FIN.VLRDESDOB_02 = 0 THEN 0 ELSE FIN.VLRDESDOB_02 * 5 END +
                                CASE WHEN FIN.VLRDESDOB_03 = 0 THEN 0 ELSE FIN.VLRDESDOB_03 * 4 END +
                                CASE WHEN FIN.VLRDESDOB_04 = 0 THEN 0 ELSE FIN.VLRDESDOB_04 * 3 END +
                                CASE WHEN FIN.VLRDESDOB_05 = 0 THEN 0 ELSE FIN.VLRDESDOB_05 * 2 END +
                                CASE WHEN FIN.VLRDESDOB_06 = 0 THEN 0 ELSE FIN.VLRDESDOB_06 * 1 END )
                              ,(CASE WHEN FIN.VLRDESDOB_01 = 0 THEN 0 ELSE 6 END +
                                CASE WHEN FIN.VLRDESDOB_02 = 0 THEN 0 ELSE 5 END +
                                CASE WHEN FIN.VLRDESDOB_03 = 0 THEN 0 ELSE 4 END +
                                CASE WHEN FIN.VLRDESDOB_04 = 0 THEN 0 ELSE 3 END +
                                CASE WHEN FIN.VLRDESDOB_05 = 0 THEN 0 ELSE 2 END +
                                CASE WHEN FIN.VLRDESDOB_06 = 0 THEN 0 ELSE 1 END )), 2)  AS FLOAT(126)) AS MEDPONVEN
FROM (
SELECT DISTINCT
       CAST (FIN.CODEMP AS NUMBER(5)) AS CODEMP
     , CAST (FIN.CODPARC AS NUMBER(10)) AS CODPARC
     , CAST (FIN.CODVEND AS NUMBER(5)) AS CODVEND
     , CAST (ROUND(SUM(CASE WHEN FIN.DTNEG BETWEEN ROUND(SYSDATE - 30) AND ROUND(SYSDATE)        THEN FIN.VLRDESDOB ELSE 0 END), 2) AS FLOAT(126)) AS VLRDESDOB_01
     , CAST (ROUND(SUM(CASE WHEN FIN.DTNEG BETWEEN ROUND(SYSDATE - 60) AND ROUND(SYSDATE - 30)   THEN FIN.VLRDESDOB ELSE 0 END), 2) AS FLOAT(126)) AS VLRDESDOB_02
     , CAST (ROUND(SUM(CASE WHEN FIN.DTNEG BETWEEN ROUND(SYSDATE - 90) AND ROUND(SYSDATE - 60)   THEN FIN.VLRDESDOB ELSE 0 END), 2) AS FLOAT(126)) AS VLRDESDOB_03
     , CAST (ROUND(SUM(CASE WHEN FIN.DTNEG BETWEEN ROUND(SYSDATE - 120) AND ROUND(SYSDATE - 90)  THEN FIN.VLRDESDOB ELSE 0 END), 2) AS FLOAT(126)) AS VLRDESDOB_04
     , CAST (ROUND(SUM(CASE WHEN FIN.DTNEG BETWEEN ROUND(SYSDATE - 150) AND ROUND(SYSDATE - 120) THEN FIN.VLRDESDOB ELSE 0 END), 2) AS FLOAT(126)) AS VLRDESDOB_05
     , CAST (ROUND(SUM(CASE WHEN FIN.DTNEG BETWEEN ROUND(SYSDATE - 180) AND ROUND(SYSDATE - 150) THEN FIN.VLRDESDOB ELSE 0 END), 2) AS FLOAT(126)) AS VLRDESDOB_06
     , CAST (ROUND(SUM(CASE WHEN FIN.DTNEG BETWEEN ROUND(SYSDATE - 180) AND ROUND(SYSDATE)       THEN FIN.VLRDESDOB ELSE 0 END), 2) AS FLOAT(126)) AS VLRDESDOB_TOT
     , CAST (COUNT(CASE WHEN FIN.DTNEG BETWEEN ROUND(SYSDATE - 30) AND ROUND(SYSDATE)        THEN FIN.NUFIN END) AS INTEGER) AS COUNT_01
     , CAST (COUNT(CASE WHEN FIN.DTNEG BETWEEN ROUND(SYSDATE - 60) AND ROUND(SYSDATE - 30)   THEN FIN.NUFIN END) AS INTEGER) AS COUNT_02
     , CAST (COUNT(CASE WHEN FIN.DTNEG BETWEEN ROUND(SYSDATE - 90) AND ROUND(SYSDATE - 60)   THEN FIN.NUFIN END) AS INTEGER) AS COUNT_03
     , CAST (COUNT(CASE WHEN FIN.DTNEG BETWEEN ROUND(SYSDATE - 120) AND ROUND(SYSDATE - 90)  THEN FIN.NUFIN END) AS INTEGER) AS COUNT_04
     , CAST (COUNT(CASE WHEN FIN.DTNEG BETWEEN ROUND(SYSDATE - 150) AND ROUND(SYSDATE - 120) THEN FIN.NUFIN END) AS INTEGER) AS COUNT_05
     , CAST (COUNT(CASE WHEN FIN.DTNEG BETWEEN ROUND(SYSDATE - 180) AND ROUND(SYSDATE - 150) THEN FIN.NUFIN END) AS INTEGER) AS COUNT_06
     , CAST (COUNT(CASE WHEN FIN.DTNEG BETWEEN ROUND(SYSDATE - 180) AND ROUND(SYSDATE)       THEN FIN.NUFIN END) AS INTEGER) AS COUNT_TOT
  FROM TGFFIN FIN
     , TGFPAR PAR
 WHERE PAR.CODPARC = FIN.CODPARC
   AND FIN.RECDESP = 1
   AND FIN.PROVISAO = 'N'
   AND FIN.CODTIPTIT NOT IN (0,18,27,99)
   AND FIN.DTNEG >= ROUND(SYSDATE-180)
   --AND FIN.DTNEG >= PAR.AD_DTALTSERASA
   AND PAR.CODTIPPARC NOT IN (40000, 50100, 50200)
   AND FIN.ORIGEM = 'E'
GROUP BY FIN.CODEMP
       , FIN.CODPARC
       , FIN.CODVEND) FIN) FIN;