UPDATE TCSPOS 
	SET APLICAVEL = 'N'
WHERE 
	NUMOS = :NUMOS AND 
	CODFLD = :CODFLD AND 
	NOT EXISTS (SELECT 1 
				FROM TPQPES PES, TPQQUE QUE
				WHERE 
					TCSPOS.NUPESQ = PES.NUPESQ AND 
					PES.CODQUEST = QUE.CODQUEST AND 
					QUE.DESCRQUEST = 'Informações Gerais') 