DELETE FROM TPQRPE 
WHERE 
	TEXTO IS NULL AND	
	NUPESQ IN (	SELECT DISTINCT NUPESQ 
				FROM TCSPOS POS 
				WHERE POS.NUMOS = :NUMOS) AND  
	NOT EXISTS ( SELECT 1 FROM TPQPES PES, TPQQUE QUE
				 WHERE 
				 	PES.NUPESQ = TPQRPE.NUPESQ AND 
				 	PES.CODQUEST = QUE.CODQUEST AND 
				 	QUE.DESCRQUEST = 'Informações Gerais' )  