SELECT  DISTINCT
  C.NUMCONTRATO,
    QUES.CODQUEST,
    RESP.CODPERG,
    PERG.DESCRPERG,
    PERG.CODQUEST,
    RESP.CODRESP AS CODRESP_CONTRATADO,
    (SELECT RESP2.CODRESP 
     FROM TPQRES RESP2 
     WHERE  
        RESP2.CODPERG = PERG.CODPERG AND
        UPPER(RESP2.DESCRRESP) = 'NÃO') AS CODRESP_NAO
FROM 
    TCSQXF QX
    INNER JOIN TPQQUE QUES ON (QUES.CODQUEST = QX.CODQUEST) 
    INNER JOIN TPQPER PERG ON (PERG.CODQUEST = QUES.CODQUEST)
    INNER JOIN TPQRES RESP ON (RESP.CODPERG = PERG.CODPERG)
    INNER JOIN TCSCON C ON (C.CODPARC = :CODPARC)
    INNER JOIN TCSPSC TCSPSC  ON (TCSPSC.NUMCONTRATO = C.NUMCONTRATO)
--    left join (SELECT DESCRPROD,CODPROD FROM TGFPRO) Produto  ON(TCSPSC.CODPROD = Produto.CODPROD) 
--    left join (SELECT X.CODTIPOPER,X.DHALTER,X.DESCROPER FROM TGFTOP X   WHERE X.DHALTER = (SELECT MAX(Y.DHALTER) FROM TGFTOP Y   WHERE Y.CODTIPOPER = X.CODTIPOPER)) TipoOperacaoGrupoFaturamento  ON(TCSPSC.TOPFATURCON = TipoOperacaoGrupoFaturamento.CODTIPOPER) left join (SELECT CODUSU,NOMEUSU FROM TSIUSU) Usuario  ON(TCSPSC.CODUSU = Usuario.CODUSU) left join (SELECT CODUSU,NOMEUSU FROM TSIUSU) Usuario_AD001  ON(TCSPSC.AD_CODUSULIBHDE = Usuario_AD001.CODUSU)   
    inner join AD_TCSPROCPRO  AD_TCSPROCPRO ON (AD_TCSPROCPRO.CODPROD = TCSPSC.CODPROD)
 -- INNER JOIN AD_TCSPROCXCON  PROCED ON (PROCED.NUMCONTRATO  = C.NUMCONTRATO  AND PROCED.NUPROC = PERG.CODPERG)
--   INNER JOIN AD_TCSPROCPRO PROCPRO ON (PROCPRO.NUPROC = RESP.CODPERG)
   
WHERE
   QX.CODFLD = 30
   AND TCSPSC.SITPROD = 'A'
   AND    UPPER(RESP.DESCRRESP) LIKE '%CONTRATADO'
   AND C.ATIVO = 'S'
   AND AD_TCSPROCPRO.NUPROC = PERG.CODPERG
--   AND ( ( C.AD_TIPOVENDA = 'VP' AND  PROCED.NUPROC = PERG.CODPERG ) OR  (C.AD_TIPOVENDA = 'VU' AND PERG.AD_DEFAULTUSU  = 'SIM' )  OR 
--   ( C.AD_TIPOVENDA = 'VU' AND PERG.AD_DEFAULTUSU  = 'NAO'  AND  PROCED.NUPROC = PERG.CODPERG) )
    order by PERG.DESCRPERG ASC