-- =====================================================
-- SCRIPT DE CRIACAO DAS TABELAS PARA INTEGRACAO SERASA
-- =====================================================
-- Data: 03/01/2025
-- Versao: 1.0.0
-- Objetivo: Criar tabelas necessarias para integracao Serasa Experian
-- =====================================================

-- Tabela de configuracao da integracao Serasa
CREATE TABLE AD_SERASACONFIG (
    CODCONFIG NUMBER(10) NOT NULL,
    CHAVE VARCHAR2(100) NOT NULL,
    VALOR VARCHAR2(500),
    DESCRICAO VARCHAR2(200),
    ATIVO CHAR(1) DEFAULT 'S',
    DTALTERACAO DATE DEFAULT SYSDATE,
    USUARIOALTERACAO VARCHAR2(50),
    CONSTRAINT PK_AD_SERASACONFIG PRIMARY KEY (CODCONFIG),
    CONSTRAINT UK_AD_SERASACONFIG_CHAVE UNIQUE (CHAVE)
);

-- Comentarios da tabela AD_SERASACONFIG
COMMENT ON TABLE AD_SERASACONFIG IS 'Configuracoes da integracao Serasa Experian';
COMMENT ON COLUMN AD_SERASACONFIG.CODCONFIG IS 'Codigo unico da configuracao';
COMMENT ON COLUMN AD_SERASACONFIG.CHAVE IS 'Chave da configuracao';
COMMENT ON COLUMN AD_SERASACONFIG.VALOR IS 'Valor da configuracao';
COMMENT ON COLUMN AD_SERASACONFIG.DESCRICAO IS 'Descricao da configuracao';
COMMENT ON COLUMN AD_SERASACONFIG.ATIVO IS 'Indica se a configuracao esta ativa (S/N)';
COMMENT ON COLUMN AD_SERASACONFIG.DTALTERACAO IS 'Data da ultima alteracao';
COMMENT ON COLUMN AD_SERASACONFIG.USUARIOALTERACAO IS 'Usuario que fez a ultima alteracao';

-- Tabela de logs da integracao Serasa
CREATE TABLE AD_SERASALOG (
    CODLOG NUMBER(10) NOT NULL,
    TIPOOPERACAO VARCHAR2(50) NOT NULL,
    DOCUMENTO VARCHAR2(20),
    STATUS VARCHAR2(20) NOT NULL,
    MENSAGEM VARCHAR2(1000),
    DADOSEXTRAS CLOB,
    DTCRIACAO DATE DEFAULT SYSDATE,
    USUARIO VARCHAR2(50),
    CONSTRAINT PK_AD_SERASALOG PRIMARY KEY (CODLOG)
);

-- Comentarios da tabela AD_SERASALOG
COMMENT ON TABLE AD_SERASALOG IS 'Logs de operacoes da integracao Serasa';
COMMENT ON COLUMN AD_SERASALOG.CODLOG IS 'Codigo unico do log';
COMMENT ON COLUMN AD_SERASALOG.TIPOOPERACAO IS 'Tipo da operacao realizada';
COMMENT ON COLUMN AD_SERASALOG.DOCUMENTO IS 'Documento consultado (CPF/CNPJ)';
COMMENT ON COLUMN AD_SERASALOG.STATUS IS 'Status da operacao';
COMMENT ON COLUMN AD_SERASALOG.MENSAGEM IS 'Mensagem descritiva';
COMMENT ON COLUMN AD_SERASALOG.DADOSEXTRAS IS 'Dados extras em formato JSON';
COMMENT ON COLUMN AD_SERASALOG.DTCRIACAO IS 'Data de criacao do log';
COMMENT ON COLUMN AD_SERASALOG.USUARIO IS 'Usuario que executou a operacao';

-- Tabela de monitoramento continuo
CREATE TABLE AD_SERASAMONITOR (
    CODMONITOR NUMBER(10) NOT NULL,
    DOCUMENTO VARCHAR2(20) NOT NULL,
    TIPOOPERACAO VARCHAR2(50) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    DADOSMONITOR CLOB,
    DTPROXIMAMONITOR DATE,
    ATIVO CHAR(1) DEFAULT 'S',
    DTCRIACAO DATE DEFAULT SYSDATE,
    DTALTERACAO DATE,
    CONSTRAINT PK_AD_SERASAMONITOR PRIMARY KEY (CODMONITOR)
);

-- Comentarios da tabela AD_SERASAMONITOR
COMMENT ON TABLE AD_SERASAMONITOR IS 'Monitoramento continuo de documentos';
COMMENT ON COLUMN AD_SERASAMONITOR.CODMONITOR IS 'Codigo unico do monitoramento';
COMMENT ON COLUMN AD_SERASAMONITOR.DOCUMENTO IS 'Documento monitorado';
COMMENT ON COLUMN AD_SERASAMONITOR.TIPOOPERACAO IS 'Tipo da operacao monitorada';
COMMENT ON COLUMN AD_SERASAMONITOR.STATUS IS 'Status do monitoramento';
COMMENT ON COLUMN AD_SERASAMONITOR.DADOSMONITOR IS 'Dados do monitoramento em JSON';
COMMENT ON COLUMN AD_SERASAMONITOR.DTPROXIMAMONITOR IS 'Data da proxima verificacao';
COMMENT ON COLUMN AD_SERASAMONITOR.ATIVO IS 'Indica se o monitoramento esta ativo';
COMMENT ON COLUMN AD_SERASAMONITOR.DTCRIACAO IS 'Data de criacao';
COMMENT ON COLUMN AD_SERASAMONITOR.DTALTERACAO IS 'Data da ultima alteracao';

-- Tabela de alertas automaticos
CREATE TABLE AD_SERASAALERTAS (
    CODALERTA NUMBER(10) NOT NULL,
    DOCUMENTO VARCHAR2(20) NOT NULL,
    TIPOALERTA VARCHAR2(50) NOT NULL,
    PARAMETROS CLOB,
    ATIVO CHAR(1) DEFAULT 'S',
    DTPROXIMAEXECUCAO DATE,
    DTCRIACAO DATE DEFAULT SYSDATE,
    DTALTERACAO DATE,
    CONSTRAINT PK_AD_SERASAALERTAS PRIMARY KEY (CODALERTA)
);

-- Comentarios da tabela AD_SERASAALERTAS
COMMENT ON TABLE AD_SERASAALERTAS IS 'Alertas automaticos da integracao Serasa';
COMMENT ON COLUMN AD_SERASAALERTAS.CODALERTA IS 'Codigo unico do alerta';
COMMENT ON COLUMN AD_SERASAALERTAS.DOCUMENTO IS 'Documento para monitoramento';
COMMENT ON COLUMN AD_SERASAALERTAS.TIPOALERTA IS 'Tipo do alerta';
COMMENT ON COLUMN AD_SERASAALERTAS.PARAMETROS IS 'Parametros do alerta em JSON';
COMMENT ON COLUMN AD_SERASAALERTAS.ATIVO IS 'Indica se o alerta esta ativo';
COMMENT ON COLUMN AD_SERASAALERTAS.DTPROXIMAEXECUCAO IS 'Data da proxima execucao';
COMMENT ON COLUMN AD_SERASAALERTAS.DTCRIACAO IS 'Data de criacao';
COMMENT ON COLUMN AD_SERASAALERTAS.DTALTERACAO IS 'Data da ultima alteracao';

-- Tabela de resultados das consultas
CREATE TABLE AD_SERASARESULTADOS (
    CODRESULTADO NUMBER(10) NOT NULL,
    CODPARC NUMBER(10),
    DOCUMENTO VARCHAR2(20) NOT NULL,
    TIPOCONSULTA VARCHAR2(10) NOT NULL,
    SCOREFINAL NUMBER(5),
    RECOMENDACAO VARCHAR2(50),
    DADOSCOMPLETOS CLOB,
    DTCRIACAO DATE DEFAULT SYSDATE,
    CONSTRAINT PK_AD_SERASARESULTADOS PRIMARY KEY (CODRESULTADO)
);

-- Comentarios da tabela AD_SERASARESULTADOS
COMMENT ON TABLE AD_SERASARESULTADOS IS 'Resultados das consultas Serasa';
COMMENT ON COLUMN AD_SERASARESULTADOS.CODRESULTADO IS 'Codigo unico do resultado';
COMMENT ON COLUMN AD_SERASARESULTADOS.CODPARC IS 'Codigo do parceiro';
COMMENT ON COLUMN AD_SERASARESULTADOS.DOCUMENTO IS 'Documento consultado';
COMMENT ON COLUMN AD_SERASARESULTADOS.TIPOCONSULTA IS 'Tipo da consulta (PF/PJ)';
COMMENT ON COLUMN AD_SERASARESULTADOS.SCOREFINAL IS 'Score final calculado';
COMMENT ON COLUMN AD_SERASARESULTADOS.RECOMENDACAO IS 'Recomendacao final';
COMMENT ON COLUMN AD_SERASARESULTADOS.DADOSCOMPLETOS IS 'Dados completos em JSON';
COMMENT ON COLUMN AD_SERASARESULTADOS.DTCRIACAO IS 'Data da consulta';

-- Criacao de indices para melhor performance
CREATE INDEX IDX_AD_SERASALOG_DOCUMENTO ON AD_SERASALOG(DOCUMENTO);
CREATE INDEX IDX_AD_SERASALOG_DTCRIACAO ON AD_SERASALOG(DTCRIACAO);
CREATE INDEX IDX_AD_SERASALOG_STATUS ON AD_SERASALOG(STATUS);

CREATE INDEX IDX_AD_SERASAMONITOR_DOCUMENTO ON AD_SERASAMONITOR(DOCUMENTO);
CREATE INDEX IDX_AD_SERASAMONITOR_ATIVO ON AD_SERASAMONITOR(ATIVO);
CREATE INDEX IDX_AD_SERASAMONITOR_DTPROXIMA ON AD_SERASAMONITOR(DTPROXIMAMONITOR);

CREATE INDEX IDX_AD_SERASAALERTAS_DOCUMENTO ON AD_SERASAALERTAS(DOCUMENTO);
CREATE INDEX IDX_AD_SERASAALERTAS_ATIVO ON AD_SERASAALERTAS(ATIVO);
CREATE INDEX IDX_AD_SERASAALERTAS_DTPROXIMA ON AD_SERASAALERTAS(DTPROXIMAEXECUCAO);

CREATE INDEX IDX_AD_SERASARESULTADOS_DOCUMENTO ON AD_SERASARESULTADOS(DOCUMENTO);
CREATE INDEX IDX_AD_SERASARESULTADOS_CODPARC ON AD_SERASARESULTADOS(CODPARC);
CREATE INDEX IDX_AD_SERASARESULTADOS_DTCRIACAO ON AD_SERASARESULTADOS(DTCRIACAO);

-- Insercao de configuracoes padrao
INSERT INTO AD_SERASACONFIG (CODCONFIG, CHAVE, VALOR, DESCRICAO, ATIVO) VALUES (1, 'CLIENT_ID', '', 'Client ID da API Serasa', 'S');
INSERT INTO AD_SERASACONFIG (CODCONFIG, CHAVE, VALOR, DESCRICAO, ATIVO) VALUES (2, 'CLIENT_SECRET', '', 'Client Secret da API Serasa', 'S');
INSERT INTO AD_SERASACONFIG (CODCONFIG, CHAVE, VALOR, DESCRICAO, ATIVO) VALUES (3, 'API_URL', 'https://api.serasaexperian.com.br', 'URL base da API Serasa', 'S');
INSERT INTO AD_SERASACONFIG (CODCONFIG, CHAVE, VALOR, DESCRICAO, ATIVO) VALUES (4, 'TIMEOUT', '30000', 'Timeout em milissegundos', 'S');
INSERT INTO AD_SERASACONFIG (CODCONFIG, CHAVE, VALOR, DESCRICAO, ATIVO) VALUES (5, 'RETRY_COUNT', '3', 'Numero de tentativas em caso de erro', 'S');
INSERT INTO AD_SERASACONFIG (CODCONFIG, CHAVE, VALOR, DESCRICAO, ATIVO) VALUES (6, 'LOG_LEVEL', 'INFO', 'Nivel de log (DEBUG, INFO, WARN, ERROR)', 'S');

-- Commit das alteracoes
COMMIT;

-- Mensagem de sucesso
SELECT 'Tabelas da integracao Serasa criadas com sucesso!' AS RESULTADO FROM DUAL;
