/*
NomeObjeto: TSICADSERV
TipoObjeto: TABLE
NomeTabela: TSICADSERV
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE TSICADSERV
   (      CODSERV NUMBER(10,0),
            NOMESERV VARCHAR2(100 BYTE),
            IPSERV VARCHAR2(100 BYTE),
            PORTSERVER NUMBER(10,0),
            ATIVO VARCHAR2(10 BYTE),
            PRIMARY KEY(CODSERV)
   )
/

/*
NomeObjeto: INTERNOCREDPAR
TipoObjeto: COLUMN
NomeTabela: TGFPAR
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE TGFPAR ADD INTERNOCREDPAR VARCHAR2(100 BYTE)
/

/*
NomeObjeto: ACESSOAPP
TipoObjeto: COLUMN
NomeTabela: TGFCTT
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE TGFCTT ADD ACESSOAPP VARCHAR2(1 BYTE) DEFAULT 'T'
/

/*
NomeObjeto: TGFCOMP
TipoObjeto: TABLE
NomeTabela: TGFCOMP
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE TGFCOMP
   (        CODCOMP  NUMBER(10,0),
            CODCID NUMBER(10,0),
            NOMEPARC VARCHAR2(250 BYTE),
            SEGMENTO VARCHAR2(250 BYTE),
            ENDERECO VARCHAR2(250 BYTE),
            TELEFONE VARCHAR2(100 BYTE),
            PRIMARY KEY(CODCOMP),
	    CONSTRAINT FK_CODCIDADE_TSICID   FOREIGN KEY(CODCID ) REFERENCES TSICID(CODCID )
   )
/

