SELECT
    ADI.CODUSU,
    USU.NOMEUSU,
    ADI.DTINICIO,
    ADI.DTFIM,
    ADI.DESCRICAO,
    ADI.CODUSUADI,
    ADI.STATUS,
    (SELECT NOMEUSU FROM TSIUSU WHERE TSIUSU.CODUSU = ADI.CODUSUADI) AS NOMEUSUADI,
    ADI.CODEVENTO
FROM
    AD_EVENTOSADICIONAIS ADI
    LEFT JOIN TSIUSU USU ON ADI.CODUSU = USU.CODUSU
WHERE
    USU.CODUSU IS NOT NULL /*FILTRO_USUARIOS AND USU.CODUSU IN (--${USUARIOS}) FILTRO_USUARIOS*/ /*FILTRO_CELULA AND USU.CODUSU IN (SELECT AD_MEMBCELULA.CODUSU FROM AD_MEMBCELULA WHERE CODCELPROD in (--${CELULAS})) FILTRO_CELULA*/