SELECT
     ESTFER.CODFUNC,
     ESTFER.CODEMP,
     ESTFER.CODEST,
     USU.CODUSU,
     USU.NOMEUSU,
     ESTFER.DTINIEST,
     ESTFER.QTDDIASDESCANSO,
     ESTFER.CODSOL
     
    FROM
        AD_TFPFUNCESTFER ESTFER
          LEFT JOIN TSIUSU USU ON USU.CODEMP = ESTFER.CODEMP AND USU.CODFUNC = ESTFER.CODFUNC
    WHERE
        ESTFER.DTINIEST IS NOT NULL AND ESTFER.QTDDIASDESCANSO IS NOT NULL AND CODSOL IS NULL
        AND USU.CODUSU IS NOT NULL /*FILTRO_USUARIOS AND USU.CODUSU IN (--${USUARIOS}) FILTRO_USUARIOS*/