SELECT
    FER.CODFUNC,
    FER.CODEMP,
    USU.CODUSU,
    USU.NOMEUSU,
    FER.DTFERIAS,
    FER.QTDDESC,
    FER.QTDVENDA,
    FER.OBS,
    FER.SOLIC,
    FER.CODUSU AS SOLICITANTE
       
    FROM
        AD_TFPFERIAS FER
        LEFT JOIN TSIUSU USU ON USU.CODEMP = FER.CODEMP AND USU.CODFUNC = FER.CODFUNC
    WHERE
	    USU.CODUSU IS NOT NULL /*FILTRO_USUARIOS AND USU.CODUSU IN (--${USUARIOS}) FILTRO_USUARIOS*/
	    AND FER.DTFERIAS >= SYSDATE