SELECT
    SBLD.NUMOS,
    SBLD.NUMSPRINT,
    SBL.CICLO,
    (SELECT OSE.AD_CELULALEAN FROM TCSOSE OSE WHERE OSE.NUMOS = SBLD.NUMOS) AS CELULA,
    SBL.COR,
    SBLD.STATUS,
     CASE
        WHEN (DESCRICAO IS NULL)
        THEN CONCAT('Tarefa da OS: ',SBLD.NUMOS)
        ELSE
            CASE
                WHEN (LENGTH(DESCRICAO) > 50)
                THEN CONCAT(SUBSTR(DESCRICAO,1,50),'...')
                ELSE DESCRICAO
            END
    END AS DESCRICAO,
    NUMTAREFA,
    TIPO,
    USU.CODUSU,
    USU.NOMEUSU AS NOMEUSU,
    DTINICIO AS DTINI,
    DTPREV AS DTFIM
FROM
    AD_TCSSBLD SBLD
    LEFT JOIN AD_TCSSBL SBL ON SBL.NUMOS = SBLD.NUMOS
    LEFT JOIN TSIUSU USU ON SBLD.CODUSU = USU.CODUSU
WHERE
	SBLD.CODUSU IN (--${USUARIOS})
   /*VERSAO_VARIAVEL AND SBL.CICLO IN (--${VERSOES}) VERSAO_VARIAVEL*/
   /*VERSAO_ATUAL AND SBL.CICLO = (SELECT VERSAO FROM AD_TSIVER WHERE LINHA = 'J' AND SYSDATE >= DTINI AND SYSDATE <= DTLANC) VERSAO_ATUAL*/