SELECT
    X.NUMOS,
    X.NUMSPRINT,
    X.CICLO,
    X.TITULO,
    X.NOMEPARC,
    CASE
        WHEN X.DTINIEXEC IS NULL
        THEN X.DTINI
        ELSE X.DTINIEXEC
    END AS DTINI,
    CASE
        WHEN X.DTFIMEXEC IS NULL
        THEN X.DTFIM
        ELSE X.DTFIMEXEC
    END AS DTFIM,
    CASE
        WHEN X.DTINIEXECTESTE IS NULL
        THEN X.DTINI
        ELSE X.DTINIEXECTESTE
    END AS DTINITESTE,
    CASE
        WHEN X.DTFIMEXECTESTE IS NULL
        THEN X.DTFIM
        ELSE X.DTFIMEXECTESTE
    END AS DTFIMTESTE,
    X.STATUS,
    X.TESTEAUTO,
    X.PAIRPROG,
    X.COR,
    X.EXECDEV,
    X.NOMEEXECDEV,
    X.EXECTESTE,
    X.NOMEEXECTESTE,
    X.CELULA,
    X.CELULADEV,
    X.CELULATESTER,
    CASE
        WHEN (X.DTINIEXEC IS NULL OR X.DTINIEXECTESTE IS NULL)
        THEN 'N'
        ELSE 'S'
    END AS EMEXECUCAO
FROM (
    SELECT 
        SBL.NUMOS,
        SBL.NUMSPRINT,
        SBL.CICLO,
        SBL.TITULO,
        PAR.NOMEPARC,
        SBL.DTINI,
        SBL.DTFIM,
        SBL.STATUS,
        SBL.TESTEAUTO,
        SBL.PAIRPROG,
        SBL.COR,
        USUD.CODUSU AS EXECDEV,
        USUD.NOMEUSU AS NOMEEXECDEV,
        USUT.CODUSU AS EXECTESTE,
        USUT.NOMEUSU AS NOMEEXECTESTE,
        (SELECT OSE.AD_CELULALEAN FROM TCSOSE OSE WHERE OSE.NUMOS = SBL.NUMOS) AS CELULA,
        (SELECT MIN(SBLD.DTINICIO) FROM AD_TCSSBLD SBLD WHERE SBLD.NUMOS = SBL.NUMOS AND SBLD.NUMSPRINT = SBL.NUMSPRINT  AND TIPO <> 'T') AS DTINIEXEC,
        (SELECT MAX(SBLD.DTPREV) AS DTFIM FROM AD_TCSSBLD SBLD WHERE SBLD.NUMOS = SBL.NUMOS AND SBLD.NUMSPRINT = SBL.NUMSPRINT  AND TIPO <> 'T') AS DTFIMEXEC,
        (SELECT MIN(SBLD.DTINICIO) FROM AD_TCSSBLD SBLD WHERE SBLD.NUMOS = SBL.NUMOS AND SBLD.NUMSPRINT = SBL.NUMSPRINT AND TIPO = 'T') AS DTINIEXECTESTE,
        (SELECT MAX(SBLD.DTPREV) AS DTFIM FROM AD_TCSSBLD SBLD WHERE SBLD.NUMOS = SBL.NUMOS AND SBLD.NUMSPRINT = SBL.NUMSPRINT AND TIPO = 'T') AS DTFIMEXECTESTE,
        GET_USUARIO_CELULA(USUD.CODUSU)  AS CELULADEV,
        GET_USUARIO_CELULA(USUT.CODUSU)  AS CELULATESTER
    FROM 
        AD_TCSSBL SBL
        LEFT JOIN TGFPAR PAR ON SBL.CODPARC = PAR.CODPARC
        LEFT JOIN TSIUSU USUD ON SBL.DONO = USUD.CODUSU
        LEFT JOIN TSIUSU USUT ON SBL.DONOTESTE = USUT.CODUSU
    WHERE
       SBL.DTINI IS NOT NULL
       AND SBL.DTFIM IS NOT NULL
       /*VERSAO_VARIAVEL AND SBL.CICLO IN (--${VERSOES}) VERSAO_VARIAVEL*/
       /*VERSAO_ATUAL AND SBL.CICLO = (SELECT VERSAO FROM AD_TSIVER WHERE LINHA = 'J' AND SYSDATE >= DTINI AND SYSDATE <= DTLANC) VERSAO_ATUAL*/
       AND EXISTS (SELECT 1 FROM TCSOSE OSE WHERE OSE.NUMOS = SBL.NUMOS AND OSE.AD_CELULALEAN IS NOT NULL)
    ORDER BY 
       CELULA ASC,
       SBL.COR
) X
WHERE
    (X.EXECDEV IS NULL AND X.EXECTESTE IS NULL /*FILTRO_CELULA AND CELULA IN (--${CELULAS}) FILTRO_CELULA*/)