SELECT
    TRI.NUMOS,
    TRI.CODCELPROD AS CELULA,
    TRI.TITULO,
    TRI.DTINIPREV,
    TRI.DTFIMPREV,
    TRI.CODUSUDEV AS EXECDEV,
    (SELECT NUMITEM FROM TCSITE WHERE NUMOS = TRI.NUMOS AND TERMEXEC IS NULL AND (TCSITE.CODUSU IN (SELECT CODUSU FROM TSIUSU WHERE CODGRUPO = 10112) OR TCSITE.CODUSU IN (176,667,2109,46,2060)) ORDER BY NUMITEM DESC FETCH FIRST 1 ROWS ONLY) AS LASTITEMOPEN,
    (SELECT USU.NOMEUSU FROM TSIUSU USU WHERE USU.CODUSU = TRI.CODUSUDEV) AS NOMEEXECDEV,
    TRI.CODUSUTESTE AS EXECTESTE,
   (SELECT USU.NOMEUSU FROM TSIUSU USU WHERE USU.CODUSU = TRI.CODUSUTESTE) AS NOMEEXECTESTE,
   (SELECT PAR.NOMEPARC FROM TCSOSE OSE INNER JOIN TGFPAR PAR ON PAR.CODPARC = OSE.CODPARC WHERE OSE.NUMOS = TRI.NUMOS) AS NOMEPARC,
   GET_USUARIO_CELULA(TRI.CODUSUDEV)  AS CELULADEV,
   GET_USUARIO_CELULA(TRI.CODUSUTESTE)  AS CELULATESTER
FROM
    AD_INDTRIAMAN TRI
WHERE 
    ((TRI.CODUSUDEV IS NOT NULL OR TRI.CODUSUTESTE IS NOT NULL) /*FILTRO_CELULA AND (TRI.CODUSUDEV IN (SELECT AD_MEMBCELULA.CODUSU FROM AD_MEMBCELULA WHERE CODCELPROD in (--${CELULAS})) OR TRI.CODUSUTESTE IN (SELECT AD_MEMBCELULA.CODUSU FROM AD_MEMBCELULA WHERE CODCELPROD in (--${CELULAS})) ) FILTRO_CELULA*/)
    AND TRI.DTINIPREV IS NOT NULL
    AND TRI.DTFIMPREV IS NOT NULL
    AND TRI.CODCELPROD IS NOT NULL
    /*FILTRA_USUARIO AND (TRI.CODUSUDEV IN (--${USUARIOS}) OR TRI.CODUSUTESTE IN (--${USUARIOS})) FILTRA_USUARIO*/
ORDER BY
    TRI.CODCELPROD ASC