/*
NomeObjeto: TIMPORTCONF
TipoObjeto: TABLE
NomeTabela: TIMPORTCONF
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE TIMPORTCONF(
  IDTELA VARCHAR(100) NOT NULL,
  NOMEIMPORT VARCHAR(100),
  INSTANCIA VARCHAR(100),
  CAMPOARQUIVO VARCHAR(100),
  CAMPONOME VARCHAR(100),
  STPFINAL VARCHAR(100),
  EVENTOANT VARCHAR(100),
  CONSTRAINT PK_TIMPCONF PRIMARY KEY (IDTELA)
)

GO

/*
NomeObjeto: STPLINHA
TipoObjeto: COLUMN
NomeTabela: TIMPORTCONF
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE TIMPORTCONF ADD STPLINHA VARCHAR(100)
GO

/*
NomeObjeto: TIPOARQ
TipoObjeto: COLUMN
NomeTabela: TIMPORTCONF
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE TIMPORTCONF ADD TIPOARQ VARCHAR(10)

GO

/*
NomeObjeto: DIRETORIOLER
TipoObjeto: COLUMN
NomeTabela: TIMPORTCONF
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE TIMPORTCONF ADD DIRETORIOLER VARCHAR(100)
GO

/*
NomeObjeto: DIRETORIOGRAVAR
TipoObjeto: COLUMN
NomeTabela: TIMPORTCONF
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE TIMPORTCONF ADD DIRETORIOGRAVAR VARCHAR(100)
GO

/*
NomeObjeto: FAZERAPOSLER
TipoObjeto: COLUMN
NomeTabela: TIMPORTCONF
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE TIMPORTCONF ADD FAZERAPOSLER VARCHAR(10)
GO

/*
NomeObjeto: TIMPORTLOG
TipoObjeto: TABLE
NomeTabela: TIMPORTLOG
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE TIMPORTLOG(
  IDTELA VARCHAR(100) NOT NULL,
  SEQUENCIA INT NOT NULL,
  MENSAGEM VARCHAR(4000),
  DHIMPORTACAO DATETIME,
  NOMEARQUIVO VARCHAR(100),
  TIPO VARCHAR(10),
  CONSTRAINT PK_TIMPORTLOG PRIMARY KEY (IDTELA, SEQUENCIA)
)
GO

/*
NomeObjeto: TEXTO
TipoObjeto: COLUMN
NomeTabela: TSIPAR
Executar  : SEMPRE
*/ 

INSERT INTO TSIPAR(CHAVE, DESCRICAO, CODUSU, TIPO, MODULO, CLASSE, ABA, LOGICO, TEXTO)
SELECT 'IDEXTHTML5', 'Lista de extensões em HTML5', 0 , 'T', 'B', 'Diversas', 'Diversas', 'S', ''
FROM DUAL 
WHERE NOT EXISTS(SELECT 1 FROM TSIPAR WHERE CHAVE = 'IDEXTHTML5')
GO

/*
NomeObjeto: TEXTO
TipoObjeto: COLUMN
NomeTabela: TSIPAR
Executar  : SEMPRE
*/ 

UPDATE TSIPAR 
  SET TEXTO = CAST(TEXTO AS NVARCHAR(MAX)) + (CASE WHEN DATALENGTH(TEXTO) > 0 THEN ',' ELSE '' END) + 'br.com.sankhya.hnzimp.cfg.configuracao.importacao'
WHERE CHAVE LIKE 'IDEXTHTML5'
  AND (TEXTO IS NULL OR TEXTO NOT LIKE '%br.com.sankhya.hnzimp.cfg.configuracao.importacao%')
GO

