/*
NomeObjeto: TIMPORTCONF
TipoObjeto: TABLE
NomeTabela: TIMPORTCONF
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE TIMPORTCONF(
  IDTELA VARCHAR2(100) NOT NULL,
  NOMEIMPORT VARCHAR2(100),
  INSTANCIA VARCHAR2(100),
  CAMPOARQUIVO VARCHAR2(100),
  CAMPONOME VARCHAR2(100),
  STPFINAL VARCHAR2(100),
  EVENTOANT VARCHAR2(100),
  CONSTRAINT PK_TIMPCONF PRIMARY KEY (IDTELA)
)
/

/*
NomeObjeto: STPLINHA
TipoObjeto: COLUMN
NomeTabela: TIMPORTCONF
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE TIMPORTCONF ADD STPLINHA VARCHAR2(100)
/

/*
NomeObjeto: TIPOARQ
TipoObjeto: COLUMN
NomeTabela: TIMPORTCONF
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE TIMPORTCONF ADD TIPOARQ VARCHAR2(10)
/

/*
NomeObjeto: DIRETORIOLER
TipoObjeto: COLUMN
NomeTabela: TIMPORTCONF
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE TIMPORTCONF ADD DIRETORIOLER VARCHAR2(100)
/

/*
NomeObjeto: DIRETORIOGRAVAR
TipoObjeto: COLUMN
NomeTabela: TIMPORTCONF
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE TIMPORTCONF ADD DIRETORIOGRAVAR VARCHAR2(100)
/

/*
NomeObjeto: FAZERAPOSLER
TipoObjeto: COLUMN
NomeTabela: TIMPORTCONF
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE TIMPORTCONF ADD FAZERAPOSLER VARCHAR2(10)
/

/*
NomeObjeto: TIMPORTLOG
TipoObjeto: TABLE
NomeTabela: TIMPORTLOG
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE TIMPORTLOG(
  IDTELA VARCHAR2(100) NOT NULL,
  SEQUENCIA NUMBER(10) NOT NULL,
  MENSAGEM VARCHAR2(4000),
  DHIMPORTACAO DATE,
  NOMEARQUIVO VARCHAR2(100),
  TIPO VARCHAR2(10),
  CONSTRAINT PK_TIMPORTLOG PRIMARY KEY (IDTELA, SEQUENCIA)
)
/

/*
NomeObjeto: TEXTO
TipoObjeto: COLUMN
NomeTabela: TSIPAR
Executar  : SEMPRE
*/ 

INSERT INTO TSIPAR(CHAVE, DESCRICAO, CODUSU, TIPO, MODULO, CLASSE, ABA, LOGICO, TEXTO)
SELECT 'IDEXTHTML5', 'Lista de extensões em HTML5', 0 , 'T', 'B', 'Diversas', 'Diversas', 'S', ''
FROM DUAL 
WHERE NOT EXISTS(SELECT 1 FROM TSIPAR WHERE CHAVE = 'IDEXTHTML5')
/

/*
NomeObjeto: TEXTO
TipoObjeto: COLUMN
NomeTabela: TSIPAR
Executar  : SEMPRE
*/ 

UPDATE TSIPAR 
  SET TEXTO = NVL(TEXTO, '') || (CASE WHEN LENGTH(TEXTO) > 0 THEN ',' ELSE '' END) || 'br.com.sankhya.hnzimp.cfg.configuracao.importacao'
WHERE CHAVE LIKE 'IDEXTHTML5'
  AND (TEXTO IS NULL OR TEXTO NOT LIKE '%br.com.sankhya.hnzimp.cfg.configuracao.importacao%')
/

