WITH base_bal_patrimonial AS
  (SELECT CTACTB,
          SUM(CASE
                  WHEN REFERENCIA <= LAST_DAY(DATE(:VAR_DATA_REF_DRE)) THEN VLRLANC
                  ELSE 0
              END) AS soma_ate_atu,
          SUM(CASE
                  WHEN REFERENCIA <= LAST_DAY(DATE_SUB(DATE(:VAR_DATA_REF_DRE), INTERVAL 1 YEAR)) THEN VLRLANC
                  ELSE 0
              END) AS soma_ate_ant
   FROM IMP_BASE_BALANCETE
   WHERE CODEMP = :VAR_EMPRESA_DRE
     AND (CTACTB LIKE '1%'
          OR CTACTB LIKE '2%')
   GROUP BY CTACTB),
     base_bal_resultado AS
  (SELECT CTACTB,
          SUM(CASE
                  WHEN REFERENCIA >= MAKEDATE(YEAR(DATE(:VAR_DATA_REF_DRE)), 1)
                       AND REFERENCIA <= LAST_DAY(DATE(:VAR_DATA_REF_DRE)) THEN VLRLANC
                  ELSE 0
              END) AS soma_ate_atu,
          SUM(CASE
                  WHEN REFERENCIA >= MAKEDATE(YEAR(DATE_SUB(DATE(:VAR_DATA_REF_DRE), INTERVAL 1 YEAR)), 1)
                       AND REFERENCIA <= LAST_DAY(DATE_SUB(DATE(:VAR_DATA_REF_DRE), INTERVAL 1 YEAR)) THEN VLRLANC
                  ELSE 0
              END) AS soma_ate_ant
   FROM IMP_BASE_BALANCETE
   WHERE CODEMP = :VAR_EMPRESA_DRE
     AND (CTACTB LIKE '3%'
          OR CTACTB LIKE '4%'
          OR CTACTB LIKE '5%')
   GROUP BY CTACTB),
     base_bal AS
  (SELECT *
   FROM base_bal_patrimonial
   UNION ALL SELECT *
   FROM base_bal_resultado),
     regras_contas AS
  (SELECT DISTINCT DET.ORDEM,
                   DET.NOME_GRUPO,
                   DET.COD_NOTA_EXPLICATIVA,
                   DETCTACTB.PADRAO_CTACTB,
                   DETCTACTB.SINAL
   FROM ESTR_DEMONSTRATIVOS EST
   INNER JOIN DET_DEMONSTRATIVO DET ON EST.ID = DET.ID_ESTR_DEMONSTRATIVO
   INNER JOIN DET_DEMONSTRATIVO_REFERENCIA DETREF ON DET.ID = DETREF.ID_DET_DEMONSTRATIVO
   INNER JOIN DET_DEMONSTRATIVO_CTACTB DETCTACTB ON DETREF.ID = DETCTACTB.ID_DET_DEMONSTRATIVO_REFERENCIA
   WHERE EST.ID = 1
     AND DETREF.REFERENCIA =
       (SELECT MAX(R.REFERENCIA)
        FROM DET_DEMONSTRATIVO_REFERENCIA R
        WHERE R.ID_DET_DEMONSTRATIVO = DET.ID
          AND R.REFERENCIA <= DATE(:VAR_DATA_REF_DRE))),
     regras_excluidas AS
  (SELECT DISTINCT DET.ORDEM,
                   DET.NOME_GRUPO,
                   DETCTACTB_EXC.PADRAO_CTACTB
   FROM ESTR_DEMONSTRATIVOS EST
   INNER JOIN DET_DEMONSTRATIVO DET ON EST.ID = DET.ID_ESTR_DEMONSTRATIVO
   INNER JOIN DET_DEMONSTRATIVO_REFERENCIA DETREF ON DET.ID = DETREF.ID_DET_DEMONSTRATIVO
   INNER JOIN DET_DEMONSTRATIVO_CTACTB_EXC DETCTACTB_EXC ON DETREF.ID = DETCTACTB_EXC.ID_DET_DEMONSTRATIVO_REFERENCIA
   WHERE EST.ID = 1
     AND DETREF.REFERENCIA =
       (SELECT MAX(R.REFERENCIA)
        FROM DET_DEMONSTRATIVO_REFERENCIA R
        WHERE R.ID_DET_DEMONSTRATIVO = DET.ID
          AND R.REFERENCIA <= DATE(:VAR_DATA_REF_DRE))),
     contas_mapeadas AS
  (SELECT B.soma_ate_atu,
          B.soma_ate_ant,
          R.ORDEM,
          R.NOME_GRUPO,
          R.COD_NOTA_EXPLICATIVA,
          R.SINAL,
          ROW_NUMBER() OVER(PARTITION BY B.CTACTB, R.ORDEM, R.NOME_GRUPO
                            ORDER BY LENGTH(R.PADRAO_CTACTB) DESC, R.PADRAO_CTACTB DESC) AS rn
   FROM base_bal B
   JOIN regras_contas R ON B.CTACTB LIKE R.PADRAO_CTACTB
   LEFT JOIN regras_excluidas E ON B.CTACTB LIKE E.PADRAO_CTACTB
   AND E.ORDEM = R.ORDEM
   AND E.NOME_GRUPO = R.NOME_GRUPO
   WHERE E.PADRAO_CTACTB IS NULL)
SELECT R.ORDEM,
       R.NOME_GRUPO,
       R.COD_NOTA_EXPLICATIVA,
       IFNULL(Agg.VLRLANC_ATU, 0) AS VLRLANC_ATU,
       IFNULL(Agg.VLRLANC_ANT, 0) AS VLRLANC_ANT
FROM
  (SELECT DISTINCT ORDEM,
                   NOME_GRUPO,
                   COD_NOTA_EXPLICATIVA
   FROM regras_contas) R
LEFT JOIN
  (SELECT M.ORDEM,
          M.NOME_GRUPO,
          M.COD_NOTA_EXPLICATIVA,
          SUM(IFNULL(M.soma_ate_atu, 0) * IFNULL(M.SINAL, 1)) AS VLRLANC_ATU,
          SUM(IFNULL(M.soma_ate_ant, 0) * IFNULL(M.SINAL, 1)) AS VLRLANC_ANT
   FROM contas_mapeadas M
   WHERE M.rn = 1
   GROUP BY M.ORDEM,
            M.NOME_GRUPO,
            M.COD_NOTA_EXPLICATIVA) Agg ON R.ORDEM = Agg.ORDEM
AND R.NOME_GRUPO = Agg.NOME_GRUPO
AND R.COD_NOTA_EXPLICATIVA <=> Agg.COD_NOTA_EXPLICATIVA
ORDER BY R.ORDEM
