SELECT NUMCONTRATO,
	   CODPARC,
       CODCENCUS,
       NUFINORIGEM,
       PERCDESCONTO,
       VLRDESCONTO,
       TruncMonth(ADD_MONTHS(SYSDATE,-1)) REFERENCIA,
       DIASEMATRASO
FROM 
(SELECT DISTINCT CON.NUMCONTRATO,
    CON.CODCENCUS,
    PAR.CODPARC,
    PAR.CODPARC || '/' || PAR.NOMEPARC  AS CODNOMEPARC,
    CASE WHEN NVL(PAR.CODPARCMATRIZ,0) = 0 THEN PAR.CODPARC 
         ELSE PAR.CODPARCMATRIZ
    END || '/' || CASE WHEN NVL(PAR.CODPARCMATRIZ,NULL)=NULL THEN PAR.NOMEPARC 
                                     ELSE PAR2.NOMEPARC
                                END AS CODNOMEPARCMATRIZ,
    FIN.NUFIN AS NUFINORIGEM,
    NAT.CODNAT || '/' || NAT.DESCRNAT AS CODDESCRICAONAT,
    NVL(CON.FREQVISITAS,0) AS INTERVALOVISITAS,  
    CON.DTULTVAG AS ULTIMAEXECUCAO, 
    TRUNC(CASE WHEN (CON.DTULTVAG + NVL(CON.FREQVISITAS,0)) < TO_DATE('01/01/2015', 'DD/MM/YYYY') THEN TO_DATE('01/01/2015', 'DD/MM/YYYY')
         ELSE (CON.DTULTVAG + NVL(CON.FREQVISITAS,0)) END) AS PROXIMAEXEC,      
    ROUND(SYSDATE - TRUNC(CASE WHEN (CON.DTULTVAG + NVL(CON.FREQVISITAS,0)) < TO_DATE('01/01/2015', 'DD/MM/YYYY') THEN TO_DATE('01/01/2015', 'DD/MM/YYYY')
                        ELSE (CON.DTULTVAG + NVL(CON.FREQVISITAS,0)) END),0) AS DIASEMATRASO,
    SUM(FIN.VLRDESDOB) AS VLRMENSALIDADE,
    ROUND((((SELECT ICND.PERCRATEIO
      FROM   TGFICND ICND
      WHERE  CODNATDESP = 110206 
            AND EXISTS ( SELECT 1 
                         FROM   TGFCND CND 
                         WHERE  CND.CODNAT = CON.CODNAT
                                AND CND.CODCENCUS = CON.CODCENCUS 
                                AND CND.CODPROJ = CON.CODPROJ
                                AND CND.ATIVO = 'S'
                                AND CND.NUCND = ICND.NUCND))/100) * SUM(FIN.VLRDESDOB)),2) AS VLRREPASSE,
    (CASE WHEN SYSDATE - TRUNC(CASE WHEN (CON.DTULTVAG + NVL(CON.FREQVISITAS,0)) < TO_DATE('01/01/2015', 'DD/MM/YYYY') THEN TO_DATE('01/01/2015', 'DD/MM/YYYY')
                        ELSE (CON.DTULTVAG + NVL(CON.FREQVISITAS,0)) END) < 30 THEN 0
          WHEN  SYSDATE - TRUNC(CASE WHEN (CON.DTULTVAG + NVL(CON.FREQVISITAS,0)) < TO_DATE('01/01/2015', 'DD/MM/YYYY') THEN TO_DATE('01/01/2015', 'DD/MM/YYYY')
                        ELSE (CON.DTULTVAG + NVL(CON.FREQVISITAS,0)) END)  BETWEEN 30 and 59 THEN 10
          WHEN  SYSDATE - TRUNC(CASE WHEN (CON.DTULTVAG + NVL(CON.FREQVISITAS,0)) < TO_DATE('01/01/2015', 'DD/MM/YYYY') THEN TO_DATE('01/01/2015', 'DD/MM/YYYY')
                        ELSE (CON.DTULTVAG + NVL(CON.FREQVISITAS,0)) END)  BETWEEN 60 and 89 THEN 20 
          WHEN  SYSDATE - TRUNC(CASE WHEN (CON.DTULTVAG + NVL(CON.FREQVISITAS,0)) < TO_DATE('01/01/2015', 'DD/MM/YYYY') THEN TO_DATE('01/01/2015', 'DD/MM/YYYY')
                        ELSE (CON.DTULTVAG + NVL(CON.FREQVISITAS,0)) END)  BETWEEN 90 and 119 THEN 30
          ELSE  ((SELECT ICND.PERCRATEIO
                  FROM   TGFICND ICND
                  WHERE  CODNATDESP = 110206 
                        AND EXISTS ( SELECT 1 
                                     FROM   TGFCND CND 
                                     WHERE  CND.CODNAT = CON.CODNAT
                                            AND CND.CODCENCUS = CON.CODCENCUS 
                                            AND CND.CODPROJ = CON.CODPROJ
                                            AND CND.ATIVO = 'S'
                                            AND CND.NUCND = ICND.NUCND)))
    END) AS PERCDESCONTO,
    ROUND(((CASE WHEN SYSDATE - TRUNC(CASE WHEN (CON.DTULTVAG + NVL(CON.FREQVISITAS,0)) < TO_DATE('01/01/2015', 'DD/MM/YYYY') THEN TO_DATE('01/01/2015', 'DD/MM/YYYY')
                        ELSE (CON.DTULTVAG + NVL(CON.FREQVISITAS,0)) END) < 30 THEN 0
          WHEN  SYSDATE - TRUNC(CASE WHEN (CON.DTULTVAG + NVL(CON.FREQVISITAS,0)) < TO_DATE('01/01/2015', 'DD/MM/YYYY') THEN TO_DATE('01/01/2015', 'DD/MM/YYYY')
                        ELSE (CON.DTULTVAG + NVL(CON.FREQVISITAS,0)) END)  BETWEEN 30 and 59 THEN 10
          WHEN  SYSDATE - TRUNC(CASE WHEN (CON.DTULTVAG + NVL(CON.FREQVISITAS,0)) < TO_DATE('01/01/2015', 'DD/MM/YYYY') THEN TO_DATE('01/01/2015', 'DD/MM/YYYY')
                        ELSE (CON.DTULTVAG + NVL(CON.FREQVISITAS,0)) END)  BETWEEN 60 and 89 THEN 20 
          WHEN  SYSDATE - TRUNC(CASE WHEN (CON.DTULTVAG + NVL(CON.FREQVISITAS,0)) < TO_DATE('01/01/2015', 'DD/MM/YYYY') THEN TO_DATE('01/01/2015', 'DD/MM/YYYY')
                        ELSE (CON.DTULTVAG + NVL(CON.FREQVISITAS,0)) END)  BETWEEN 90 and 119 THEN 30
          ELSE  (SELECT ICND.PERCRATEIO
                  FROM   TGFICND ICND
                  WHERE  CODNATDESP = 110206 
                        AND EXISTS ( SELECT 1 
                                     FROM   TGFCND CND 
                                     WHERE  CND.CODNAT = CON.CODNAT
                                            AND CND.CODCENCUS = CON.CODCENCUS 
                                            AND CND.CODPROJ = CON.CODPROJ
                                            AND CND.ATIVO = 'S'
                                            AND CND.NUCND = ICND.NUCND))
    END /100) *  SUM(FIN.VLRDESDOB)),2) AS VLRDESCONTO, 
    ROUND(((((SELECT ICND.PERCRATEIO
      FROM   TGFICND ICND
      WHERE  CODNATDESP = 110206 
            AND EXISTS ( SELECT 1 
                         FROM   TGFCND CND 
                         WHERE  CND.CODNAT = CON.CODNAT
                                AND CND.CODCENCUS = CON.CODCENCUS 
                                AND CND.CODPROJ = CON.CODPROJ
                                AND CND.ATIVO = 'S'
                                AND CND.NUCND = ICND.NUCND))/100) * SUM(FIN.VLRDESDOB)) -
    ((CASE WHEN SYSDATE - TRUNC(CASE WHEN (CON.DTULTVAG + NVL(CON.FREQVISITAS,0)) < TO_DATE('01/01/2015', 'DD/MM/YYYY') THEN TO_DATE('01/01/2015', 'DD/MM/YYYY')
                        ELSE (CON.DTULTVAG + NVL(CON.FREQVISITAS,0)) END) < 30 THEN 0
          WHEN  SYSDATE - TRUNC(CASE WHEN (CON.DTULTVAG + NVL(CON.FREQVISITAS,0)) < TO_DATE('01/01/2015', 'DD/MM/YYYY') THEN TO_DATE('01/01/2015', 'DD/MM/YYYY')
                        ELSE (CON.DTULTVAG + NVL(CON.FREQVISITAS,0)) END)  BETWEEN 30 and 59 THEN 10
          WHEN  SYSDATE - TRUNC(CASE WHEN (CON.DTULTVAG + NVL(CON.FREQVISITAS,0)) < TO_DATE('01/01/2015', 'DD/MM/YYYY') THEN TO_DATE('01/01/2015', 'DD/MM/YYYY')
                        ELSE (CON.DTULTVAG + NVL(CON.FREQVISITAS,0)) END)  BETWEEN 60 and 89 THEN 20 
          WHEN  SYSDATE - TRUNC(CASE WHEN (CON.DTULTVAG + NVL(CON.FREQVISITAS,0)) < TO_DATE('01/01/2015', 'DD/MM/YYYY') THEN TO_DATE('01/01/2015', 'DD/MM/YYYY')
                        ELSE (CON.DTULTVAG + NVL(CON.FREQVISITAS,0)) END)  BETWEEN 90 and 119 THEN 30
          ELSE  (SELECT ICND.PERCRATEIO
                  FROM   TGFICND ICND
                  WHERE  CODNATDESP = 110206 
                        AND EXISTS ( SELECT 1 
                                     FROM   TGFCND CND 
                                     WHERE  CND.CODNAT = CON.CODNAT
                                            AND CND.CODCENCUS = CON.CODCENCUS 
                                            AND CND.CODPROJ = CON.CODPROJ
                                            AND CND.ATIVO = 'S'
                                            AND CND.NUCND = ICND.NUCND))
    END /100) *  SUM(FIN.VLRDESDOB))),2) AS VLRLIQUIDO,
    CASE WHEN (SELECT DISTINCT 1 
               FROM TGFDRV DRV 
               WHERE (DRV.REFERENCIA BETWEEN TRUNC(ADD_MONTHS(SYSDATE,-1),'MM') AND SYSDATE) 
                      AND DRV.NUMCONTRATO = CON.NUMCONTRATO) = 1 THEN 'S'
         ELSE  'N'
    END AS DESCONTADO
  FROM 
    TCSCON CON     
    LEFT JOIN TGFPAR PAR ON (CON.CODPARC = PAR.CODPARC)
    INNER JOIN TGFNAT NAT ON (CON.CODNAT = NAT.CODNAT)  
    INNER JOIN VGFFRV FIN ON (FIN.CODPARC IN (SELECT DISTINCT CODPARC FROM TGFPAR WHERE CODPARC = CON.CODPARC OR CODPARCMATRIZ = CON.CODPARC))
                          AND FIN.CODNAT = CON.CODNAT
                          AND FIN.CODCENCUS = CON.CODCENCUS
                          AND FIN.CODPROJ = CON.CODPROJ               
    LEFT JOIN TGFPAR PAR2 ON (PAR2.CODPARC = PAR.CODPARCMATRIZ)
  WHERE CON.CODPROJ IN (101000,108000,111000)
    AND CON.CODNAT IN (110201,110202,110203, 110204, 110205, 110213, 110107)
    AND CON.AD_VISITA = 'COMVAG'
    AND EXISTS(SELECT 1 FROM TCSPSC PSC WHERE CON.NUMCONTRATO = PSC.NUMCONTRATO AND PSC.SITPROD IN ('A','B'))
    AND (EXISTS(SELECT 1 AS NUFAP FROM TCSFAP FAP WHERE FAP.CODMETOD IN (99,21,8) AND FAP.STATUS = 'C' AND FAP.CODPARC = CON.CODPARC
                 AND FAP.NUFAP = (SELECT MAX(NUFAP) FROM TCSFAP FAP1 WHERE FAP1.CODMETOD IN (99,21,8) AND  FAP1.CODPARC = CON.CODPARC )) OR
       NOT EXISTS(SELECT 1 AS NUFAP FROM TCSFAP FAP WHERE FAP.CODMETOD IN (99,21,8) AND FAP.CODPARC = CON.CODPARC))
  GROUP BY 
    CON.NUMCONTRATO , 
    NVL(CON.FREQVISITAS,0), 
    CON.CODPARC,
    CON.DTCONTRATO,      
    PAR.CODPARC || '/' || PAR.NOMEPARC ,
    CASE WHEN NVL(PAR.CODPARCMATRIZ,0) = 0 THEN PAR.CODPARC 
         ELSE PAR.CODPARCMATRIZ
    END || '/' || CASE WHEN NVL(PAR.CODPARCMATRIZ,NULL)=NULL THEN PAR.NOMEPARC 
                       ELSE PAR2.NOMEPARC
                  END ,
    NAT.CODNAT || '/' || NAT.DESCRNAT,            
    CON.CODNAT,
    CON.CODCENCUS,
    CON.CODPROJ,
    CON.DTULTVAG,
    CON.CODCENCUS,
    PAR.CODPARC,
    FIN.NUFIN)
WHERE DIASEMATRASO >= 30