SELECT
  CASE WHEN ICND.CODNATREC = 0 THEN FIN.CODNAT ELSE ICND.CODNATREC END AS CODNAT
, CASE WHEN ICND.CODCENCUSREC = 0 THEN FIN.CODCENCUS ELSE ICND.CODCENCUSREC END AS CODCENCUS
, CASE WHEN ICND.CODPROJREC = 0 THEN FIN.CODPROJ ELSE ICND.CODPROJREC END AS CODPROJ
, CASE WHEN ICND.CODEMPREC = 0 THEN FIN.CODEMP ELSE ICND.CODEMPREC END AS CODEMP
, CASE WHEN ICND.CODPARCREC = 0 THEN FIN.CODPARC ELSE ICND.CODPARCREC END AS CODPARC
, ABS(round(SUM(round((SELECT NVL(SUM(JUR.VLRCOM), 0) FROM AD_TGFAPJUR JUR WHERE JUR.NUFINORIG = FIN.NUFIN),2)),2)) AS VLRCOMISJUR
, ABS(round(SUM(round((SELECT NVL(SUM(VLRDESCREPASSE), 0)  FROM TGFDRV DRV WHERE DRV.NUFINORIG = FIN.NUFIN),2)),2)) AS VLRDESCVAG
, ABS(round(SUM(
                GREATEST(round((FIN.VLRBAIXA
/*$COM_DESCOMISJUR$
 - (SELECT NVL(SUM(JUR.VLRCOM), 0) FROM AD_TGFAPJUR JUR WHERE JUR.NUFINORIG = FIN.NUFIN)
$COM_DESCOMISJUR$*/
                         +
/*$SEM_IMPOSTO$
0
$SEM_IMPOSTO$*/
/*$COM_IMPOSTO$
                       CASE WHEN CAB.NUNOTA IS NULL
                            THEN 0
                            ELSE (CASE WHEN CAB.ISSRETIDO = 'S' THEN CAB.VLRISS ELSE 0 END +
                                  CAB.VLRIRF +
                                  CASE WHEN CAB.IRFRETIDO = 'S' THEN CAB.VLRINSS ELSE 0 END +
                                  nullValue((SELECT SUM(IMN.VALOR) FROM TGFIMN IMN
                                          WHERE IMN.NUNOTA = FIN.NUNOTA AND IMN.TIPIMP = -1),0)
                                  ) * FIN.VLRDESDOB / CAB.VLRNOTA END +
                       nullValue((SELECT SUM(IMF.VALOR) FROM TGFIMF IMF
                               WHERE IMF.NUFIN = FIN.NUFIN
                               AND IMF.TIPIMP = -1),0)
$COM_IMPOSTO$*/
                       ) * ICND.PERCRATEIO / 100 * FIN.RECDESP,2)
/*$COM_DESCVAG$
                       - (SELECT NVL(SUM(VLRDESCREPASSE), 0)  FROM TGFDRV DRV WHERE DRV.NUFINORIG = FIN.NUFIN)
$COM_DESCVAG$*/
                        , 0)
                ),2)) AS VALOR
, NAT.DESCRNAT
, CUS.DESCRCENCUS
, PRJ.IDENTIFICACAO
, PAR.NOMEPARC
, CASE WHEN CND.RECDESP IS NULL THEN 1.0
       WHEN SIGN(round(SUM(
                GREATEST(round((FIN.VLRBAIXA
/*$COM_DESCOMISJUR$
 - (SELECT NVL(SUM(JUR.VLRCOM), 0) FROM AD_TGFAPJUR JUR WHERE JUR.NUFINORIG = FIN.NUFIN)
$COM_DESCOMISJUR$*/
                         +
/*$SEM_IMPOSTO$
0
$SEM_IMPOSTO$*/
/*$COM_IMPOSTO$
                       CASE WHEN CAB.NUNOTA IS NULL
                            THEN 0
                            ELSE (CASE WHEN CAB.ISSRETIDO = 'S' THEN CAB.VLRISS ELSE 0 END +
                                  CAB.VLRIRF +
                                  CASE WHEN CAB.IRFRETIDO = 'S' THEN CAB.VLRINSS ELSE 0 END +
                                  nullValue((SELECT SUM(IMN.VALOR) FROM TGFIMN IMN
                                          WHERE IMN.NUNOTA = FIN.NUNOTA AND IMN.TIPIMP = -1),0)
                                  ) * FIN.VLRDESDOB / CAB.VLRNOTA END +
                       nullValue((SELECT SUM(IMF.VALOR) FROM TGFIMF IMF
                               WHERE IMF.NUFIN = FIN.NUFIN
                               AND IMF.TIPIMP = -1),0)
$COM_IMPOSTO$*/
                       ) * ICND.PERCRATEIO / 100 * FIN.RECDESP,2)
/*$COM_DESCVAG$
                       - (SELECT NVL(SUM(VLRDESCREPASSE), 0)  FROM TGFDRV DRV WHERE DRV.NUFINORIG = FIN.NUFIN)
$COM_DESCVAG$*/
                        , 0)
                ),2)) = CND.RECDESP THEN 1.0
       ELSE -1.0 END AS RECDESP
, FIN.RECDESP
FROM VGFFINRAT FIN
  LEFT JOIN TGFCAB CAB ON CAB.NUNOTA = FIN.NUNOTA
, TGFCND CND
, TGFICND ICND
, TGFNAT NAT
, TSICUS CUS
, TCSPRJ PRJ
, TGFPAR PAR
WHERE FIN.DHBAIXA IS NOT NULL
AND FIN.PROVISAO = 'N'
AND FIN.RECDESP <> 0
AND (ICND.CODNATREC <> 0 OR ICND.CODCENCUSREC <> 0 OR ICND.CODPROJREC <> 0)
AND (FIN.CODEMP = CND.CODEMP OR CND.CODEMP = 0)
AND (FIN.CODNAT = CND.CODNAT OR CND.CODNAT = 0)
AND (FIN.CODCENCUS = CND.CODCENCUS OR CND.CODCENCUS = 0)
AND (FIN.CODPROJ = CND.CODPROJ OR CND.CODPROJ = 0)
AND (:NUCND = 0 OR CND.NUCND = :NUCND)
AND CND.ATIVO = 'S'
AND CND.NUCND = ICND.NUCND
/*$INCLUI_ORDEM$
AND CND.ORDEM = :ORDEM
$INCLUI_ORDEM$*/
AND FIN.DHBAIXA BETWEEN :DATINI AND :DATFIM
AND NAT.CODNAT = CASE WHEN ICND.CODNATREC = 0 THEN FIN.CODNAT ELSE ICND.CODNATREC END
AND CUS.CODCENCUS = CASE WHEN ICND.CODCENCUSREC = 0 THEN FIN.CODCENCUS ELSE ICND.CODCENCUSREC END
AND PRJ.CODPROJ = CASE WHEN ICND.CODPROJREC = 0 THEN FIN.CODPROJ ELSE ICND.CODPROJREC END
AND PAR.CODPARC = CASE WHEN ICND.CODPARCREC = 0 THEN FIN.CODPARC ELSE ICND.CODPARCREC END
/*$DESCONSIDERA_RATEADOS$
AND NOT EXISTS (SELECT 1 FROM TGFFRP FRP WHERE FRP.NUFINORIG = FIN.NUFIN)
$DESCONSIDERA_RATEADOS$*/
group by
  CASE WHEN ICND.CODNATREC = 0 THEN FIN.CODNAT ELSE ICND.CODNATREC END
, CASE WHEN ICND.CODCENCUSREC = 0 THEN FIN.CODCENCUS ELSE ICND.CODCENCUSREC END
, CASE WHEN ICND.CODPROJREC = 0 THEN FIN.CODPROJ ELSE ICND.CODPROJREC END
, CASE WHEN ICND.CODEMPREC = 0 THEN FIN.CODEMP ELSE ICND.CODEMPREC END
, CASE WHEN ICND.CODPARCREC = 0 THEN FIN.CODPARC ELSE ICND.CODPARCREC END
, NAT.DESCRNAT
, CUS.DESCRCENCUS
, PRJ.IDENTIFICACAO
, PAR.NOMEPARC
, CND.RECDESP
, FIN.RECDESP

union all

SELECT
  cast(CASE WHEN ICND.CODNATDESP = 0 THEN FIN.CODNAT ELSE ICND.CODNATDESP END AS FLOAT) AS CODNAT
, cast(CASE WHEN ICND.CODCENCUSDESP = 0 THEN FIN.CODCENCUS ELSE ICND.CODCENCUSDESP END AS FLOAT) AS CODCENCUS
, cast(CASE WHEN ICND.CODPROJDESP = 0 THEN FIN.CODPROJ ELSE ICND.CODPROJDESP END AS FLOAT) AS CODPROJ
, cast(CASE WHEN ICND.CODEMPDESP = 0 THEN FIN.CODEMP ELSE ICND.CODEMPDESP END AS FLOAT) AS CODEMP
, cast(CASE WHEN ICND.CODPARCDESP = 0 THEN FIN.CODPARC ELSE ICND.CODPARCDESP END AS FLOAT) AS CODPARC
, ABS(round(SUM(round((SELECT NVL(SUM(JUR.VLRCOM), 0) FROM AD_TGFAPJUR JUR WHERE JUR.NUFINORIG = FIN.NUFIN),2)),2)) AS VLRCOMISJUR
, ABS(round(SUM(round((SELECT NVL(SUM(VLRDESCREPASSE), 0)  FROM TGFDRV DRV WHERE DRV.NUFINORIG = FIN.NUFIN),2)),2)) AS VLRDESCVAG
, ABS(round(SUM(
                GREATEST(round((FIN.VLRBAIXA
/*$COM_DESCOMISJUR$
 - (SELECT NVL(SUM(JUR.VLRCOM), 0) FROM AD_TGFAPJUR JUR WHERE JUR.NUFINORIG = FIN.NUFIN)
$COM_DESCOMISJUR$*/
                         +
/*$SEM_IMPOSTO$
0
$SEM_IMPOSTO$*/
/*$COM_IMPOSTO$
                       CASE WHEN CAB.NUNOTA IS NULL
                            THEN 0
                            ELSE (CASE WHEN CAB.ISSRETIDO = 'S' THEN CAB.VLRISS ELSE 0 END +
                                  CAB.VLRIRF +
                                  CASE WHEN CAB.IRFRETIDO = 'S' THEN CAB.VLRINSS ELSE 0 END +
                                  nullValue((SELECT SUM(IMN.VALOR) FROM TGFIMN IMN
                                          WHERE IMN.NUNOTA = FIN.NUNOTA AND IMN.TIPIMP = -1),0)
                                  ) * FIN.VLRDESDOB / CAB.VLRNOTA END +
                       nullValue((SELECT SUM(IMF.VALOR) FROM TGFIMF IMF
                               WHERE IMF.NUFIN = FIN.NUFIN
                               AND IMF.TIPIMP = -1),0)
$COM_IMPOSTO$*/
                       ) * ICND.PERCRATEIO / 100 * FIN.RECDESP,2)
/*$COM_DESCVAG$
                       - (SELECT NVL(SUM(VLRDESCREPASSE), 0)  FROM TGFDRV DRV WHERE DRV.NUFINORIG = FIN.NUFIN)
$COM_DESCVAG$*/
                        , 0)
                ),2)) AS VALOR
, NAT.DESCRNAT
, CUS.DESCRCENCUS
, PRJ.IDENTIFICACAO
, PAR.NOMEPARC
, CASE WHEN CND.RECDESP IS NULL THEN -1.0
       WHEN SIGN(round(SUM(
                GREATEST(round((FIN.VLRBAIXA
/*$COM_DESCOMISJUR$
 - (SELECT NVL(SUM(JUR.VLRCOM), 0) FROM AD_TGFAPJUR JUR WHERE JUR.NUFINORIG = FIN.NUFIN)
$COM_DESCOMISJUR$*/
                       +
/*$SEM_IMPOSTO$
0
$SEM_IMPOSTO$*/
/*$COM_IMPOSTO$
                       CASE WHEN CAB.NUNOTA IS NULL
                            THEN 0
                            ELSE (CASE WHEN CAB.ISSRETIDO = 'S' THEN CAB.VLRISS ELSE 0 END +
                                  CAB.VLRIRF +
                                  CASE WHEN CAB.IRFRETIDO = 'S' THEN CAB.VLRINSS ELSE 0 END +
                                  nullValue((SELECT SUM(IMN.VALOR) FROM TGFIMN IMN
                                          WHERE IMN.NUNOTA = FIN.NUNOTA AND IMN.TIPIMP = -1),0)
                                  ) * FIN.VLRDESDOB / CAB.VLRNOTA END +
                       nullValue((SELECT SUM(IMF.VALOR) FROM TGFIMF IMF
                               WHERE IMF.NUFIN = FIN.NUFIN
                               AND IMF.TIPIMP = -1),0)
$COM_IMPOSTO$*/
                       ) * ICND.PERCRATEIO / 100 * FIN.RECDESP,2)
/*$COM_DESCVAG$
                       - (SELECT NVL(SUM(VLRDESCREPASSE), 0)  FROM TGFDRV DRV WHERE DRV.NUFINORIG = FIN.NUFIN)
$COM_DESCVAG$*/
                        , 0)
                ),2)) = CND.RECDESP THEN -1.0
       ELSE 1.0 END AS RECDESP
, FIN.RECDESP
FROM VGFFINRAT FIN
  LEFT JOIN TGFCAB CAB ON CAB.NUNOTA = FIN.NUNOTA
, TGFCND CND
, TGFICND ICND
, TGFNAT NAT
, TSICUS CUS
, TCSPRJ PRJ
, TGFPAR PAR
WHERE FIN.DHBAIXA IS NOT NULL
AND FIN.PROVISAO = 'N'
AND FIN.RECDESP <> 0
AND (ICND.CODNATDESP <> 0 OR ICND.CODCENCUSDESP <> 0 OR ICND.CODPROJDESP <> 0)
AND (FIN.CODEMP = CND.CODEMP OR CND.CODEMP = 0)
AND (FIN.CODNAT = CND.CODNAT OR CND.CODNAT = 0)
AND (FIN.CODCENCUS = CND.CODCENCUS OR CND.CODCENCUS = 0)
AND (FIN.CODPROJ = CND.CODPROJ OR CND.CODPROJ = 0)
AND (:NUCND = 0 OR CND.NUCND = :NUCND)
AND CND.ATIVO = 'S'
AND CND.NUCND = ICND.NUCND
/*$INCLUI_ORDEM$
AND CND.ORDEM = :ORDEM
$INCLUI_ORDEM$*/
AND FIN.DHBAIXA BETWEEN :DATINI AND :DATFIM
AND NAT.CODNAT = CASE WHEN ICND.CODNATDESP = 0 THEN FIN.CODNAT ELSE ICND.CODNATDESP END
AND CUS.CODCENCUS = CASE WHEN ICND.CODCENCUSDESP = 0 THEN FIN.CODCENCUS ELSE ICND.CODCENCUSDESP END
AND PRJ.CODPROJ = CASE WHEN ICND.CODPROJDESP = 0 THEN FIN.CODPROJ ELSE ICND.CODPROJDESP END
AND PAR.CODPARC = CASE WHEN ICND.CODPARCDESP = 0 THEN FIN.CODPARC ELSE ICND.CODPARCDESP END
/*$DESCONSIDERA_RATEADOS$
AND NOT EXISTS (SELECT 1 FROM TGFFRP FRP WHERE FRP.NUFINORIG = FIN.NUFIN)
$DESCONSIDERA_RATEADOS$*/
group by
  CASE WHEN ICND.CODNATDESP = 0 THEN FIN.CODNAT ELSE ICND.CODNATDESP END
, CASE WHEN ICND.CODCENCUSDESP = 0 THEN FIN.CODCENCUS ELSE ICND.CODCENCUSDESP END
, CASE WHEN ICND.CODPROJDESP = 0 THEN FIN.CODPROJ ELSE ICND.CODPROJDESP END
, CASE WHEN ICND.CODEMPDESP = 0 THEN FIN.CODEMP ELSE ICND.CODEMPDESP END
, CASE WHEN ICND.CODPARCDESP = 0 THEN FIN.CODPARC ELSE ICND.CODPARCDESP END
, NAT.DESCRNAT
, CUS.DESCRCENCUS
, PRJ.IDENTIFICACAO
, PAR.NOMEPARC
, CND.RECDESP
, FIN.RECDESP
ORDER BY CODEMP, CODPARC