
SELECT * FROM 


(


SELECT 
CODMETA,
DTREF,
CODEMP,
CODPROJ,
CODCENCUS,
CODNAT,
SUM(PREVDESP) AS PREVDESP,
sUM(REALDESP) AS REALDESP,
SUM(PREVREC) AS PREVREC,
SUM(REALREC) AS REALREC,
SUM(BAIXA_REC) AS BAIXA_REC,
SUM(BAIXA_DESP) AS BAIXA_DESP,
SUM(COMP_REC) AS COMP_REC,
SUM(COMP_DESP) AS COMP_DESP,
SUM(BAIXA_REC_ANO_ANT) AS BAIXA_REC_ANO_ANT,
SUM(BAIXA_DESP_ANO_ANT) AS BAIXA_DESP_ANO_ANT

FROM 
(
-- ORÇAMENTO NORMAL IMPORTADO
SELECT
    MET.CODMETA,
    MET.DTREF,
    MET.CODEMP,
    MET.CODPROJ,
    MET.CODCENCUS,
    MET.CODNAT,
    ABS(MET.PREVDESP) AS PREVDESP,
    MET.REALDESP,
    ABS(MET.PREVREC) AS PREVREC,
    MET.REALREC,

    NVL((SELECT SUM(FIN.VLRBAIXA)
         FROM TGFFIN FIN
         WHERE FIN.PROVISAO = 'N'
           AND FIN.CODPROJ = MET.CODPROJ
           AND FIN.CODNAT = MET.CODNAT
           AND FIN.CODEMP = MET.CODEMP
           AND FIN.CODCENCUS = MET.CODCENCUS
           AND TRUNC(FIN.DHBAIXA,'MM') = MET.DTREF
           AND FIN.DHBAIXA IS NOT NULL
           AND FIN.RECDESP = 1),0) AS BAIXA_REC,

    NVL((SELECT SUM(FIN.VLRBAIXA)
         FROM TGFFIN FIN
         WHERE FIN.PROVISAO = 'N'
           AND FIN.CODPROJ = MET.CODPROJ
           AND FIN.CODNAT = MET.CODNAT
           AND FIN.CODEMP = MET.CODEMP
           AND FIN.CODCENCUS = MET.CODCENCUS
           AND TRUNC(FIN.DHBAIXA,'MM') = MET.DTREF
           AND FIN.DHBAIXA IS NOT NULL
           AND FIN.RECDESP = -1),0) AS BAIXA_DESP,


0 AS COMP_REC,

0 AS COMP_DESP,

0 AS BAIXA_REC_ANO_ANT,

0 AS BAIXA_DESP_ANO_ANT

FROM TGFMET MET

WHERE MET.CODMETA = 5

UNION ALL

-- ORRÇAMENTO DE FORECAST GERADO 

SELECT
    MET.CODMETA,
    MET.DTREF,
    MET.CODEMP,
    MET.CODPROJ,
    MET.CODCENCUS,
    MET.CODNAT,
    ABS(MET.PREVDESP) AS PREVDESP,
    MET.REALDESP,
    ABS(MET.PREVREC) AS PREVREC,
    MET.REALREC,

    NVL((SELECT SUM(FIN.VLRBAIXA)
         FROM TGFFIN FIN
         WHERE FIN.PROVISAO = 'N'
           AND FIN.CODPROJ = MET.CODPROJ
           AND FIN.CODNAT = MET.CODNAT
           AND FIN.CODEMP = MET.CODEMP
           AND FIN.CODCENCUS = MET.CODCENCUS
           AND TRUNC(FIN.DHBAIXA,'MM') = MET.DTREF
           AND FIN.DHBAIXA IS NOT NULL
           AND FIN.RECDESP = 1),0) AS BAIXA_REC,

    NVL((SELECT SUM(FIN.VLRBAIXA)
         FROM TGFFIN FIN
         WHERE FIN.PROVISAO = 'N'
           AND FIN.CODPROJ = MET.CODPROJ
           AND FIN.CODNAT = MET.CODNAT
           AND FIN.CODEMP = MET.CODEMP
           AND FIN.CODCENCUS = MET.CODCENCUS
           AND TRUNC(FIN.DHBAIXA,'MM') = MET.DTREF
           AND FIN.DHBAIXA IS NOT NULL
           AND FIN.RECDESP = -1),0) AS BAIXA_DESP,


0 AS COMP_REC,

0 AS COMP_DESP,

0 AS BAIXA_REC_ANO_ANT,

0 AS BAIXA_DESP_ANO_ANT

FROM TGFMET MET

WHERE MET.CODMETA = 7

UNION ALL 

SELECT
    5 AS CODMETA,
    TRUNC(FIN.DHBAIXA,'MM') AS DTREF,
    FIN.CODEMP,
    FIN.CODPROJ,
    FIN.CODCENCUS,
    FIN.CODNAT,

    0 AS PREVDESP,
    0 AS REALDESP,
    0 AS PREVREC,
    0 AS REALREC,

    SUM(CASE WHEN FIN.RECDESP = 1 THEN FIN.VLRBAIXA ELSE 0 END) AS BAIXA_REC,
    SUM(CASE WHEN FIN.RECDESP = -1 THEN FIN.VLRBAIXA ELSE 0 END) AS BAIXA_DESP,
    
    0 AS COMP_REC,
    0 AS COMP_DESP,

    0 AS BAIXA_REC_ANO_ANT,
    0 AS BAIXA_DESP_ANO_ANT

FROM TGFFIN FIN

WHERE FIN.PROVISAO = 'N'
AND FIN.CODNAT IN (SELECT DISTINCT N.CODNAT FROM TGFNAT N START WITH N.DESCRNAT IN ('CANCELAMENTO RECEITA SERVICOS MENSALIDADES', 'OUTRAS RECEITAS', 'DOACOES RECEBIDAS', 'LOCACAO DE SALAS', 'RECEBIMENTOS NAO IDENTIFICADOS', 'TAXAS DIVERSAS', 'DESCONTOS CONCEDIDOS', 'JUROS E ENCARGOS PAGOS', 'TAXAS DE SERVICOS BANCARIOS', 'TAXAS OPERADORAS CARTOES E PIX', 'DESCONTOS OBTIDOS', 'JUROS E ENCARGOS RECEBIDOS', 'RENDIMENTO SOBRE APLICACOES FINANCEIRAS', 'RECEBIMENTO PRECATORIOS') CONNECT BY PRIOR N.CODNAT = N.CODNATPAI)

GROUP BY
    TRUNC(FIN.DHBAIXA,'MM'),
    FIN.CODEMP,
    FIN.CODPROJ,
    FIN.CODCENCUS,
    FIN.CODNAT

UNION ALL 


SELECT
    5 AS CODMETA,
    TRUNC(FIN.DTNEG,'MM') AS DTREF,
    FIN.CODEMP,
    FIN.CODPROJ,
    FIN.CODCENCUS,
    FIN.CODNAT,

    0 AS PREVDESP,
    0 AS REALDESP,
    0 AS PREVREC,
    0 AS REALREC,

    0 AS BAIXA_REC,
    0 AS BAIXA_DESP,

    SUM(CASE WHEN FIN.RECDESP = 1 THEN FIN.VLRDESDOB ELSE 0 END) AS COMP_REC,
    SUM(CASE WHEN FIN.RECDESP = -1 THEN FIN.VLRDESDOB ELSE 0 END) AS COMP_DESP,

    0 AS BAIXA_REC_ANO_ANT,
    0 AS BAIXA_DESP_ANO_ANT

FROM TGFFIN FIN

WHERE FIN.PROVISAO = 'N'
AND FIN.CODNAT IN (SELECT DISTINCT N.CODNAT FROM TGFNAT N START WITH N.DESCRNAT IN ('CANCELAMENTO RECEITA SERVICOS MENSALIDADES', 'OUTRAS RECEITAS', 'DOACOES RECEBIDAS', 'LOCACAO DE SALAS', 'RECEBIMENTOS NAO IDENTIFICADOS', 'TAXAS DIVERSAS', 'DESCONTOS CONCEDIDOS', 'JUROS E ENCARGOS PAGOS', 'TAXAS DE SERVICOS BANCARIOS', 'TAXAS OPERADORAS CARTOES E PIX', 'DESCONTOS OBTIDOS', 'JUROS E ENCARGOS RECEBIDOS', 'RENDIMENTO SOBRE APLICACOES FINANCEIRAS', 'RECEBIMENTO PRECATORIOS') CONNECT BY PRIOR N.CODNAT = N.CODNATPAI)

GROUP BY
    TRUNC(FIN.DTNEG,'MM'),
    FIN.CODEMP,
    FIN.CODPROJ,
    FIN.CODCENCUS,
    FIN.CODNAT

UNION ALL 


-- ADD_MONTHS(TRUNC(FIN.DTNEG,'MM'), 12)



SELECT
    5 AS CODFIN2A,
    TRUNC(FIN2.DTNEG,'MM') AS DTREF,
    FIN2.CODEMP,
    FIN2.CODPROJ,
    FIN2.CODCENCUS,
    FIN2.CODNAT,

    0 AS PREVDESP,
    0 AS REALDESP,
    0 AS PREVREC,
    0 AS REALREC,

    0 AS BAIXA_REC,
    0 AS BAIXA_DESP,
    
    0 AS COMP_REC,
    0 AS COMP_DESP,

    NVL((SELECT SUM(FIN.VLRDESDOB)
         FROM TGFFIN FIN
         WHERE FIN.PROVISAO = 'N'
           AND FIN.CODPROJ = FIN2.CODPROJ
           AND FIN.CODNAT = FIN2.CODNAT
           AND FIN.CODEMP = FIN2.CODEMP
           AND FIN.CODCENCUS = FIN2.CODCENCUS
           AND TRUNC(FIN.DTNEG,'MM') = ADD_MONTHS(TRUNC(FIN2.DTNEG,'MM'),-12)
           AND FIN.RECDESP = 1),0) AS BAIXA_REC_ANO_ANT,

    NVL((SELECT SUM(FIN.VLRDESDOB)
         FROM TGFFIN FIN
         WHERE FIN.PROVISAO = 'N'
           AND FIN.CODPROJ = FIN2.CODPROJ
           AND FIN.CODNAT = FIN2.CODNAT
           AND FIN.CODEMP = FIN2.CODEMP
           AND FIN.CODCENCUS = FIN2.CODCENCUS
           AND TRUNC(FIN.DTNEG,'MM') = ADD_MONTHS(TRUNC(FIN2.DTNEG,'MM'),-12)
           AND FIN.RECDESP = -1),0) AS BAIXA_DESP_ANO_ANT

FROM TGFFIN FIN2

WHERE FIN2.PROVISAO = 'N'
AND FIN2.CODNAT IN (SELECT DISTINCT N.CODNAT FROM TGFNAT N START WITH N.DESCRNAT IN ('CANCELAMENTO RECEITA SERVICOS MENSALIDADES', 'OUTRAS RECEITAS', 'DOACOES RECEBIDAS', 'LOCACAO DE SALAS', 'RECEBIMENTOS NAO IDENTIFICADOS', 'TAXAS DIVERSAS', 'DESCONTOS CONCEDIDOS', 'JUROS E ENCARGOS PAGOS', 'TAXAS DE SERVICOS BANCARIOS', 'TAXAS OPERADORAS CARTOES E PIX', 'DESCONTOS OBTIDOS', 'JUROS E ENCARGOS RECEBIDOS', 'RENDIMENTO SOBRE APLICACOES FINANCEIRAS', 'RECEBIMENTO PRECATORIOS') CONNECT BY PRIOR N.CODNAT = N.CODNATPAI)

GROUP BY
    TRUNC(FIN2.DTNEG,'MM'),
    FIN2.CODEMP,
    FIN2.CODPROJ,
    FIN2.CODCENCUS,
    FIN2.CODNAT

UNION ALL 

SELECT 
5 AS CODMETA,
TRUNC(CAB.DTNEG,'MM') AS DTREF,
CAB.CODEMP,
CAB.CODPROJ,
CAB.CODCENCUS,
CAB.CODNAT,
0 AS PREVDESP,
0 AS REALDESP,
0 AS PREVREC,
0 AS REALREC,
0 AS BAIXA_REC,
0 AS BAIXA_DESP,
CAB.VLRNOTA AS COMP_REC,
0 AS COMP_DESP,
0 AS BAIXA_REC_ANO_ANT,
0 AS BAIXA_DESP_ANO_ANT


FROM TGFCAB CAB 

WHERE CAB.CODEMP IN (1,2)
AND CODTIPOPER IN (1128) 


UNION ALL 

SELECT 

5 AS CODMETA,
LAN.REFERENCIA AS DTREF,
LAN.CODEMP,
LAN.CODPROJ,
LAN.CODCENCUS,
NAT.CODNAT,
0 AS PREVDESP,
0 AS REALDESP,
0 AS PREVREC,
0 AS REALREC,
0 AS BAIXA_REC,
0 AS BAIXA_DESP,
0 AS COMP_REC,
LAN.VLRLANC AS COMP_DESP,
0 AS BAIXA_REC_ANO_ANT,
0 AS BAIXA_DESP_ANO_ANT

FROM TCBLAN LAN
LEFT JOIN TGFNAT NAT ON LAN.CODCTACTB = NAT.CODCTACTB

WHERE NAT.ANALITICA = 'S'
AND NAT.CODNAT IN (SELECT DISTINCT N.CODNAT FROM TGFNAT N START WITH N.DESCRNAT IN ('REPASSE VENDAS', 'DESPESAS COM PESSOAL ADMINISTRATIVO', 'SALARIOS E ORDENADOS ADMINISTRATIVO', 'ENCARGOS PESSOAL ADMINISTRATIVOS', 'OUTROS RESULTADOS DE INVESTIMENTOS', 'PROVISOES E PERDAS GERAIS', 'RESULTADO DE PARTIC. EM OUTRAS SOCIEDADES', 'DEPRECIACAO E AMORTIZACAO', 'RESULTADO COM DERIVATIVOS DE SWAP - AVJ', 'VARIACAO CAMBIAL PASSIVA', 'VARIACAO MONETARIA PASSIVA', 'RESULTADO COM DERIVATIVOS DE HEDGE - AVJ', 'VARIACAO CAMBIAL ATIVA', 'VARIACAO MONETARIA ATIVA', 'PROVISAO TRIBUTOS S/ LUCRO', 'DESCONTOS CONCEDIDOS', 'TRIBUTOS E CONTRIBUICOES S/ RECEITA', 'RECEITA CLINICA ESCOLA', 'RECEITA SERVICOS MENSALIDADES', 'CUSTO DOCENTE', 'CUSTO PESSOAL DOCENTE', 'CUSTOS ENCARGOS DOCENTE', 'CUSTOS FINANCIAMENTO', 'DESPESAS TRIBUTARIAS', 'PROVISAO DE TRIBUTOS S/ LUCRO') CONNECT BY PRIOR N.CODNAT = N.CODNATPAI)

UNION ALL 

SELECT 
5 AS CODMETA,
TRUNC(CAB.DTNEG,'MM') AS DTREF,
CAB.CODEMP,
CAB.CODPROJ,
CAB.CODCENCUS,
CAB.CODNAT,
0 AS PREVDESP,
0 AS REALDESP,
0 AS PREVREC,
0 AS REALREC,
0 AS BAIXA_REC,
0 AS BAIXA_DESP,
CAB.VLRNOTA AS COMP_REC,
0 AS COMP_DESP,
0 AS BAIXA_REC_ANO_ANT,
0 AS BAIXA_DESP_ANO_ANT


FROM TGFCAB CAB 

WHERE CAB.CODTIPOPER IN (1132, 1133, 1134, 1135, 1137, 1140, 1717, 1714)
AND CAB.CODNAT IN (SELECT DISTINCT N.CODNAT FROM TGFNAT N START WITH N.DESCRNAT IN ('CUSTO DE MERCADORIA', 'MATERIAL BRINDES E BINIFICAÇÕES', 'MATERIAL DE DEMONSTRAÇÃO') CONNECT BY PRIOR N.CODNAT = N.CODNATPAI)

UNION ALL

-- PORTAL - DESPESA/RECEITA (hierarquia de naturezas)
SELECT
5 AS CODMETA,
TRUNC(CAB.DTNEG,'MM') AS DTREF,
CAB.CODEMP,
CAB.CODPROJ,
CAB.CODCENCUS,
CAB.CODNAT,
0 AS PREVDESP,
0 AS REALDESP,
0 AS PREVREC,
0 AS REALREC,
0 AS BAIXA_REC,
0 AS BAIXA_DESP,
CAB.VLRNOTA AS COMP_REC,
0 AS COMP_DESP,
0 AS BAIXA_REC_ANO_ANT,
0 AS BAIXA_DESP_ANO_ANT
FROM TGFCAB CAB
WHERE CAB.CODNAT IN (SELECT DISTINCT N.CODNAT FROM TGFNAT N START WITH N.DESCRNAT IN ('CUSTOS PESSOAL DIVERSOS DOCENTE', 'CUSTOS EDUCACIONAIS', 'DESPESAS ADMINISTRATIVAS', 'DESPESAS DE ALUGUEL', 'DESPESAS DE CONSERVACAO E MANUTENCAO', 'DESPESAS GERAIS', 'DESPESAS TECNOLOGICAS', 'GOVERNANCA CORPORATIVA', 'SERVICOS DE TERCEIROS', 'SERVICOS ASSESSORIA CORPORATIVA', 'PESSOAL DIVERSOS ADMINISTRATIVO', 'DESPESAS COM VENDAS', 'DESPESAS MARKETING E COMERCIAL', 'DESPESAS INDEDUTIVEIS', 'DEDUCOES DA RECEITA', 'DESCONTOS CONCEDIDOS', 'DEVOLUCOES/CANCELAMENTO', 'TRIBUTOS E CONTRIBUICOES S/ RECEITA', 'RECEITA DE BENS E SERVICOS', 'RECEITA BRUTA DE VENDA DE MERCADORIAS', 'RECEITA OPERACIONAL BRUTA SERVICOS', 'CUSTOS DE MERCADORIAS E SERVICOS', 'CUSTO PEDAGOGICO', 'INVESTIMENTOS') CONNECT BY PRIOR N.CODNAT = N.CODNATPAI)



    UNION ALL

    -- ============================================================
    -- 7. DIREITOS AUTORAIS - REALIZADO => COMP_DESP (natureza 2010300)
    -- ============================================================
    SELECT
        5                               AS CODMETA,
        DA.REFERENCIA                   AS DTREF,
        DA.CODEMP,
        DA.CODPROJ,
        DA.CODCENCUS,
        DA.CODNAT,
        0 AS PREVDESP,
        0 AS REALDESP,
        0 AS PREVREC,
        0 AS REALREC,
        0 AS BAIXA_REC,
        0 AS BAIXA_DESP,
        0 AS COMP_REC,
        DA.COMPARC                      AS COMP_DESP,
        0 AS BAIXA_REC_ANO_ANT,
        0 AS BAIXA_DESP_ANO_ANT
    FROM (
        SELECT
            TRUNC(FIN.DHBAIXA, 'MM') AS REFERENCIA,
            EMP.CODEMP,
            2010300 AS CODNAT,
            CAB.CODCENCUS,
            CAB.CODPROJ,
            ROUND(SUM(BASE.VLRBASECOM * (DIR.PERCENTUAL / 100)), 2) AS COMPARC
        FROM (
            SELECT
                CAB.NUNOTA, ITE.CODPROD, CAB2.CODTIPOPER, CAB2.DHTIPOPER,
                SUM((ITE.VLRUNIT * ITE.QTDNEG) * (FIN.VLRDESDOB / CAB.VLRNOTA)) AS VLRBASECOM
            FROM TGFCAB CAB
            INNER JOIN (
                SELECT CONT.IDCONTAINERS, CONT.NUNOTA, C.CODTIPOPER, C.DHTIPOPER
                FROM TGFCONT CONT
                INNER JOIN TGFCAB C ON C.NUNOTA = CONT.NUNOTA
                WHERE C.CODTIPOPER = 1131
            ) CAB2 ON CAB2.NUNOTA = CAB.NUNOTA
            INNER JOIN TGFITE ITE ON ITE.NUNOTA = CAB2.IDCONTAINERS
            INNER JOIN (
                SELECT NUNOTA, SUM(VLRDESDOB) AS VLRDESDOB
                FROM TGFFIN
                WHERE DHBAIXA BETWEEN '01/01/2000' AND '01/01/2990'
                GROUP BY NUNOTA
            ) FIN ON FIN.NUNOTA = CAB.NUNOTA
            WHERE CAB.STATUSNOTA = 'L' AND CAB.TIPMOV IN ('V', 'D') AND ITE.USOPROD <> 'D'
            GROUP BY CAB.NUNOTA, ITE.CODPROD, CAB2.CODTIPOPER, CAB2.DHTIPOPER

            UNION ALL

            SELECT
                CAB.NUNOTA, ITE.CODPROD, CAB.CODTIPOPER, CAB.DHTIPOPER,
                SUM((ITE.VLRUNIT * ITE.QTDNEG) * (FIN.VLRDESDOB / CAB.VLRNOTA)) AS VLRBASECOM
            FROM TGFCAB CAB
            INNER JOIN TGFITE ITE ON ITE.NUNOTA = CAB.NUNOTA
            INNER JOIN (
                SELECT NUNOTA, SUM(VLRDESDOB) AS VLRDESDOB
                FROM TGFFIN
                WHERE DHBAIXA BETWEEN '01/01/2000' AND '01/01/2990'
                GROUP BY NUNOTA
            ) FIN ON FIN.NUNOTA = CAB.NUNOTA
            WHERE CAB.STATUSNOTA = 'L' AND CAB.TIPMOV IN ('V', 'D') AND ITE.USOPROD <> 'D'
              AND CAB.CODTIPOPER IN (1714, 1718)
            GROUP BY CAB.NUNOTA, ITE.CODPROD, CAB.CODTIPOPER, CAB.DHTIPOPER
        ) BASE
        INNER JOIN TGFCAB CAB ON CAB.NUNOTA = BASE.NUNOTA
        INNER JOIN TGFPAR PAR ON PAR.CODPARC = CAB.CODPARC
        INNER JOIN TSIEMP EMP ON EMP.CODEMP = CAB.CODEMP
        INNER JOIN TGFPRO PRO ON PRO.CODPROD = BASE.CODPROD
        INNER JOIN AD_DIRAUTPROD DIR ON DIR.CODPROD = PRO.CODPROD
        INNER JOIN TGFVEN AUT ON AUT.CODVEND = DIR.CODVEND
        INNER JOIN TGFTOP TPO ON TPO.CODTIPOPER = BASE.CODTIPOPER AND TPO.DHALTER = BASE.DHTIPOPER
        INNER JOIN TGFFIN FIN ON FIN.NUNOTA = CAB.NUNOTA AND FIN.DHBAIXA BETWEEN '01/01/2000' AND '01/01/2990'
        WHERE NVL(PAR.AD_NAOCALCDIRAUT, 'N') = 'N' AND DIR.PERCENTUAL IS NOT NULL
        GROUP BY TRUNC(FIN.DHBAIXA, 'MM'), EMP.CODEMP, CAB.CODCENCUS, CAB.CODPROJ
    ) DA

    UNION ALL

    -- ============================================================
    -- 8. COMISSOES - REALIZADO => COMP_DESP (natureza 2010401)
    -- ============================================================
    SELECT
        5                               AS CODMETA,
        CM.DTFAT                        AS DTREF,
        CM.CODEMP,
        CM.CODPROJ,
        CM.CODCENCUS,
        CM.CODNAT,
        0 AS PREVDESP,
        0 AS REALDESP,
        0 AS PREVREC,
        0 AS REALREC,
        0 AS BAIXA_REC,
        0 AS BAIXA_DESP,
        0 AS COMP_REC,
        CM.VLRCOMI                      AS COMP_DESP,
        0 AS BAIXA_REC_ANO_ANT,
        0 AS BAIXA_DESP_ANO_ANT
    FROM (
        SELECT DISTINCT
            CAB.CODEMP, CAB.CODPROJ, CAB.CODCENCUS,
            2010401 AS CODNAT,
            TRUNC(CAB.DTFATUR, 'MM') AS DTFAT,
            COM.VLRCOM AS VLRCOMI
        FROM TGFCOM COM, TGFVEN VEN, TGFFIN FIN, TGFCAB CAB, TGFPAR PAR, TSIEMP EMP, TGFCCM CCM
        WHERE COM.CODVEND = VEN.CODVEND
          AND FIN.NUNOTA = CAB.NUNOTA
          AND CAB.NUNOTA = COM.NUNOTAORIG
          AND CAB.CODPARC = PAR.CODPARC
          AND CAB.CODEMP = EMP.CODEMP
          AND CCM.NUNOTA = CAB.NUNOTA
          AND CCM.CODVEND = VEN.CODVEND
          AND VEN.TIPVEND = 'R'
    ) CM
)

GROUP BY 
CODMETA,
DTREF,
CODEMP,
CODPROJ,
CODCENCUS,
CODNAT

)
