
SELECT * FROM 


(


SELECT 
CODMETA,
DTREF,
CODEMP,
CODPROJ,
CODCENCUS,
CODNAT,
SUM(PREVDESP) AS PREVDESP,
sUM(REALDESP) AS REALDESP,
SUM(PREVREC) AS PREVREC,
SUM(REALREC) AS REALREC,
SUM(BAIXA_REC) AS BAIXA_REC,
SUM(BAIXA_DESP) AS BAIXA_DESP,
SUM(COMP_REC) AS COMP_REC,
SUM(COMP_DESP) AS COMP_DESP,
SUM(BAIXA_REC_ANO_ANT) AS BAIXA_REC_ANO_ANT,
SUM(BAIXA_DESP_ANO_ANT) AS BAIXA_DESP_ANO_ANT

FROM 
(
-- ORÇAMENTO NORMAL IMPORTADO
SELECT
    MET.CODMETA,
    MET.DTREF,
    MET.CODEMP,
    MET.CODPROJ,
    MET.CODCENCUS,
    MET.CODNAT,
    ABS(MET.PREVDESP) AS PREVDESP,
    MET.REALDESP,
    ABS(MET.PREVREC) AS PREVREC,
    MET.REALREC,

    NVL((SELECT SUM(FIN.VLRBAIXA)
         FROM TGFFIN FIN
         WHERE FIN.PROVISAO = 'N'
           AND FIN.CODPROJ = MET.CODPROJ
           AND FIN.CODNAT = MET.CODNAT
           AND FIN.CODEMP = MET.CODEMP
           AND FIN.CODCENCUS = MET.CODCENCUS
           AND TRUNC(FIN.DHBAIXA,'MM') = MET.DTREF
           AND FIN.DHBAIXA IS NOT NULL
           AND FIN.RECDESP = 1),0) AS BAIXA_REC,

    NVL((SELECT SUM(FIN.VLRBAIXA)
         FROM TGFFIN FIN
         WHERE FIN.PROVISAO = 'N'
           AND FIN.CODPROJ = MET.CODPROJ
           AND FIN.CODNAT = MET.CODNAT
           AND FIN.CODEMP = MET.CODEMP
           AND FIN.CODCENCUS = MET.CODCENCUS
           AND TRUNC(FIN.DHBAIXA,'MM') = MET.DTREF
           AND FIN.DHBAIXA IS NOT NULL
           AND FIN.RECDESP = -1),0) AS BAIXA_DESP,


0 AS COMP_REC,

0 AS COMP_DESP,

0 AS BAIXA_REC_ANO_ANT,

0 AS BAIXA_DESP_ANO_ANT

FROM TGFMET MET

WHERE MET.CODMETA = 5

UNION ALL

-- ORRÇAMENTO DE FORECAST GERADO 

SELECT
    MET.CODMETA,
    MET.DTREF,
    MET.CODEMP,
    MET.CODPROJ,
    MET.CODCENCUS,
    MET.CODNAT,
    ABS(MET.PREVDESP) AS PREVDESP,
    MET.REALDESP,
    ABS(MET.PREVREC) AS PREVREC,
    MET.REALREC,

    NVL((SELECT SUM(FIN.VLRBAIXA)
         FROM TGFFIN FIN
         WHERE FIN.PROVISAO = 'N'
           AND FIN.CODPROJ = MET.CODPROJ
           AND FIN.CODNAT = MET.CODNAT
           AND FIN.CODEMP = MET.CODEMP
           AND FIN.CODCENCUS = MET.CODCENCUS
           AND TRUNC(FIN.DHBAIXA,'MM') = MET.DTREF
           AND FIN.DHBAIXA IS NOT NULL
           AND FIN.RECDESP = 1),0) AS BAIXA_REC,

    NVL((SELECT SUM(FIN.VLRBAIXA)
         FROM TGFFIN FIN
         WHERE FIN.PROVISAO = 'N'
           AND FIN.CODPROJ = MET.CODPROJ
           AND FIN.CODNAT = MET.CODNAT
           AND FIN.CODEMP = MET.CODEMP
           AND FIN.CODCENCUS = MET.CODCENCUS
           AND TRUNC(FIN.DHBAIXA,'MM') = MET.DTREF
           AND FIN.DHBAIXA IS NOT NULL
           AND FIN.RECDESP = -1),0) AS BAIXA_DESP,


0 AS COMP_REC,

0 AS COMP_DESP,

0 AS BAIXA_REC_ANO_ANT,

0 AS BAIXA_DESP_ANO_ANT

FROM TGFMET MET

WHERE MET.CODMETA = 7

UNION ALL 

SELECT
    5 AS CODMETA,
    TRUNC(FIN.DHBAIXA,'MM') AS DTREF,
    FIN.CODEMP,
    FIN.CODPROJ,
    FIN.CODCENCUS,
    FIN.CODNAT,

    0 AS PREVDESP,
    0 AS REALDESP,
    0 AS PREVREC,
    0 AS REALREC,

    SUM(CASE WHEN FIN.RECDESP = 1 THEN FIN.VLRBAIXA ELSE 0 END) AS BAIXA_REC,
    SUM(CASE WHEN FIN.RECDESP = -1 THEN FIN.VLRBAIXA ELSE 0 END) AS BAIXA_DESP,
    
    0 AS COMP_REC,
    0 AS COMP_DESP,

    0 AS BAIXA_REC_ANO_ANT,
    0 AS BAIXA_DESP_ANO_ANT

FROM TGFFIN FIN

WHERE FIN.PROVISAO = 'N'
AND FIN.CODNAT NOT LIKE '401%'

GROUP BY
    TRUNC(FIN.DHBAIXA,'MM'),
    FIN.CODEMP,
    FIN.CODPROJ,
    FIN.CODCENCUS,
    FIN.CODNAT

UNION ALL 


SELECT
    5 AS CODMETA,
    TRUNC(FIN.DTNEG,'MM') AS DTREF,
    FIN.CODEMP,
    FIN.CODPROJ,
    FIN.CODCENCUS,
    FIN.CODNAT,

    0 AS PREVDESP,
    0 AS REALDESP,
    0 AS PREVREC,
    0 AS REALREC,

    0 AS BAIXA_REC,
    0 AS BAIXA_DESP,

    SUM(CASE WHEN FIN.RECDESP = 1 THEN FIN.VLRDESDOB ELSE 0 END) AS COMP_REC,
    SUM(CASE WHEN FIN.RECDESP = -1 THEN FIN.VLRDESDOB ELSE 0 END) AS COMP_DESP,

    0 AS BAIXA_REC_ANO_ANT,
    0 AS BAIXA_DESP_ANO_ANT

FROM TGFFIN FIN

WHERE FIN.PROVISAO = 'N'
AND FIN.CODNAT NOT LIKE '401%'

GROUP BY
    TRUNC(FIN.DTNEG,'MM'),
    FIN.CODEMP,
    FIN.CODPROJ,
    FIN.CODCENCUS,
    FIN.CODNAT

UNION ALL 


-- ADD_MONTHS(TRUNC(FIN.DTNEG,'MM'), 12)



SELECT
    5 AS CODFIN2A,
    TRUNC(FIN2.DTNEG,'MM') AS DTREF,
    FIN2.CODEMP,
    FIN2.CODPROJ,
    FIN2.CODCENCUS,
    FIN2.CODNAT,

    0 AS PREVDESP,
    0 AS REALDESP,
    0 AS PREVREC,
    0 AS REALREC,

    0 AS BAIXA_REC,
    0 AS BAIXA_DESP,
    
    0 AS COMP_REC,
    0 AS COMP_DESP,

    NVL((SELECT SUM(FIN.VLRDESDOB)
         FROM TGFFIN FIN
         WHERE FIN.PROVISAO = 'N'
           AND FIN.CODPROJ = FIN2.CODPROJ
           AND FIN.CODNAT = FIN2.CODNAT
           AND FIN.CODEMP = FIN2.CODEMP
           AND FIN.CODCENCUS = FIN2.CODCENCUS
           AND TRUNC(FIN.DTNEG,'MM') = ADD_MONTHS(TRUNC(FIN2.DTNEG,'MM'),-12)
           AND FIN.RECDESP = 1),0) AS BAIXA_REC_ANO_ANT,

    NVL((SELECT SUM(FIN.VLRDESDOB)
         FROM TGFFIN FIN
         WHERE FIN.PROVISAO = 'N'
           AND FIN.CODPROJ = FIN2.CODPROJ
           AND FIN.CODNAT = FIN2.CODNAT
           AND FIN.CODEMP = FIN2.CODEMP
           AND FIN.CODCENCUS = FIN2.CODCENCUS
           AND TRUNC(FIN.DTNEG,'MM') = ADD_MONTHS(TRUNC(FIN2.DTNEG,'MM'),-12)
           AND FIN.RECDESP = -1),0) AS BAIXA_DESP_ANO_ANT

FROM TGFFIN FIN2

WHERE FIN2.PROVISAO = 'N'
AND FIN2.CODNAT NOT LIKE '401%'

GROUP BY
    TRUNC(FIN2.DTNEG,'MM'),
    FIN2.CODEMP,
    FIN2.CODPROJ,
    FIN2.CODCENCUS,
    FIN2.CODNAT

UNION ALL 

SELECT 
5 AS CODMETA,
TRUNC(CAB.DTNEG,'MM') AS DTREF,
CAB.CODEMP,
CAB.CODPROJ,
CAB.CODCENCUS,
CAB.CODNAT,
0 AS PREVDESP,
0 AS REALDESP,
0 AS PREVREC,
0 AS REALREC,
0 AS BAIXA_REC,
0 AS BAIXA_DESP,
CAB.VLRNOTA AS COMP_REC,
0 AS COMP_DESP,
0 AS BAIXA_REC_ANO_ANT,
0 AS BAIXA_DESP_ANO_ANT


FROM TGFCAB CAB 

WHERE CAB.CODEMP IN (1,2)
AND CODTIPOPER IN (1128) 


UNION ALL 

SELECT 

5 AS CODMETA,
LAN.REFERENCIA AS DTREF,
LAN.CODEMP,
LAN.CODPROJ,
LAN.CODCENCUS,
NAT.CODNAT,
0 AS PREVDESP,
0 AS REALDESP,
0 AS PREVREC,
0 AS REALREC,
0 AS BAIXA_REC,
0 AS BAIXA_DESP,
0 AS COMP_REC,
LAN.VLRLANC AS COMP_DESP,
0 AS BAIXA_REC_ANO_ANT,
0 AS BAIXA_DESP_ANO_ANT

FROM TCBLAN LAN
LEFT JOIN TGFNAT NAT ON LAN.CODCTACTB = NAT.CODCTACTB

WHERE NAT.ANALITICA = 'S'
AND NAT.CODNAT LIKE '401%'

UNION ALL 

SELECT 
5 AS CODMETA,
TRUNC(CAB.DTNEG,'MM') AS DTREF,
CAB.CODEMP,
CAB.CODPROJ,
CAB.CODCENCUS,
CAB.CODNAT,
0 AS PREVDESP,
0 AS REALDESP,
0 AS PREVREC,
0 AS REALREC,
0 AS BAIXA_REC,
0 AS BAIXA_DESP,
CAB.VLRNOTA AS COMP_REC,
0 AS COMP_DESP,
0 AS BAIXA_REC_ANO_ANT,
0 AS BAIXA_DESP_ANO_ANT


FROM TGFCAB CAB 

WHERE CODTIPOPER IN (1132,	
1133,	
1134,	
1135,	
1137) 

)

GROUP BY 
CODMETA,
DTREF,
CODEMP,
CODPROJ,
CODCENCUS,
CODNAT

)
