CREATE OR REPLACE PROCEDURE "STP_RECALCREMFIXDESLSATIS" (
       P_TIPOEVENTO INT,    -- Identifica o tipo de evento
       P_IDSESSAO VARCHAR2, -- Identificador da execução. Serve para buscar informações dos campos da execução.
       P_CODUSU INT         -- Código do usuário logado
) AS
       BEFORE_INSERT INT;
       AFTER_INSERT  INT;
       BEFORE_DELETE INT;
       AFTER_DELETE  INT;
       BEFORE_UPDATE INT;
       AFTER_UPDATE  INT;
       BEFORE_COMMIT INT;

       FIELD_NUFECH  INT;
       FIELD_SEQ     INT;
       P_DESLIGADO   VARCHAR2(100);
       P_DIASTRAB    INT;
       P_REMFIXA     NUMBER;
       P_VLRDIARIO   NUMBER;
       P_REMFIXA2    NUMBER;

BEGIN
       BEFORE_INSERT := 0;
       AFTER_INSERT  := 1;
       BEFORE_DELETE := 2;
       AFTER_DELETE  := 3;
       BEFORE_UPDATE := 4;
       AFTER_UPDATE  := 5;
       BEFORE_COMMIT := 10;

       FIELD_NUFECH := EVP_GET_CAMPO_INT(P_IDSESSAO, 'NUFECH');
       FIELD_SEQ := EVP_GET_CAMPO_INT(P_IDSESSAO, 'SEQUENCIA');


    IF P_TIPOEVENTO = AFTER_UPDATE THEN 

        SELECT DESLIGADO,DIASTRAB,REMFIXA INTO P_DESLIGADO, P_DIASTRAB,P_REMFIXA FROM AD_DBFECHCOMFIN WHERE SEQUENCIA = FIELD_SEQ AND NUFECH = FIELD_NUFECH; 
   
            IF P_DESLIGADO = 'SIM' AND P_REMFIXA > 0 THEN 
    
                SELECT P_REMFIXA / 30 INTO P_VLRDIARIO FROM DUAL;

                SELECT P_VLRDIARIO * P_DIASTRAB INTO P_REMFIXA2 FROM DUAL;

                     UPDATE AD_DBFECHCOMFIN SET REMFIXA = P_REMFIXA2 WHERE SEQUENCIA = FIELD_SEQ AND NUFECH = FIELD_NUFECH;
                     COMMIT;

            END IF;

    END IF ;

END;
/
