WITH MOVIMENTOS_POR_NOTA AS (

    SELECT
        G.NUNOTA,
        G.NUMNOTA,
        G.DATA_ENTREGA AS DT_MOV,
        G.CODPARC,
        'Entrada' AS TIPO_MOVIMENTO,
        I.PESO_ITEM,
        I.PESO_ITEM_LIQ
    FROM GESTAO_NOTAS_APROVACAO G
    JOIN IMP_ITENS_NOTAS_APRV I ON G.NUNOTA = I.NUNOTA
    WHERE G.CODPARC = :VAR_PARCEIRO_SELECIONADO
      AND G.DATA_ENTREGA BETWEEN :VAR_PERIODO_INICIO AND :VAR_PERIODO_FIM
      AND G.ENTREGUE = 1

    UNION ALL

    SELECT
        N.NUNOTA,
        N.NUMNOTA,
        N.DTNEG AS DT_MOV,
        N.CODPARC,
        'Saída' AS TIPO_MOVIMENTO,
        N.PESO_ITEM,
        N.PESO_ITEM_LIQ
    FROM IMP_NOTAS_ARMAZ N
    WHERE N.CODPARC = :VAR_PARCEIRO_SELECIONADO
      AND N.DTNEG BETWEEN :VAR_PERIODO_INICIO AND :VAR_PERIODO_FIM
      AND N.ATUALESTOQUE = 1
)
SELECT
    M.NUNOTA,
    M.NUMNOTA,
    DATE_FORMAT(M.DT_MOV, '%d/%m/%Y') AS DATA_NOTA,
    M.TIPO_MOVIMENTO,
    SUM(M.PESO_ITEM) AS PESO_BRUTO,
    SUM(M.PESO_ITEM_LIQ) AS PESO_LIQUIDO
FROM MOVIMENTOS_POR_NOTA M
GROUP BY
    M.NUNOTA,
    M.NUMNOTA,
    M.DT_MOV,
    M.TIPO_MOVIMENTO
ORDER BY
    M.DT_MOV, M.NUNOTA
