SELECT *
FROM 
	(SELECT 
		PES.NUPESQ, 
		PER.CODPERG,
		RES.CODRESP,
		(SELECT COUNT(1) FROM TPQRES RES2 WHERE RES2.CODPERG = PER.CODPERG AND RES2.ATIVO = 'S') AS QTD_RESP
	FROM 
		TPQPES PES, 
		TPQPER PER,
		TPQRES RES
	WHERE 
		PES.NUPESQ = :NUPESQ AND 
		PES.CODQUEST = PER.CODQUEST AND 
		RES.CODPERG = PER.CODPERG AND
		RES.DESCRRESP = 'Sim' AND 
		RES.ATIVO = 'S') TEMP
WHERE
    TEMP.QTD_RESP = 1