SELECT DISTINCT * FROM (
	SELECT 
		PES.NUPESQ, 
		RES.CODPERG, 
		RES.CODRESP 
	FROM 
		AD_TPQIMH IMH, 
		TPQPES PES, 
		TPQRES RES, 
		TPQPER PER 
	WHERE 
		IMH.NUMAHA = :CODMAHA AND 
		PES.NUPESQ IN (SELECT DISTINCT NUPESQ FROM TCSPOS POS WHERE POS.NUMOS = :NUMOS) AND 
		PES.CODQUEST = PER.CODQUEST AND 
		IMH.CODPERG = PER.CODPERG AND 
		IMH.CODPERG = RES.CODPERG AND 
		RES.DESCRRESP = :RESPOSTA AND 
		RES.ATIVO = 'S' 
	UNION 
	SELECT 
		PES.NUPESQ, 
		RES.CODPERG, 
		RES.CODRESP 
	FROM 
		AD_TPQIMH IMH, 
		TPQPES PES, 
		TPQRES RES, 
		TPQPER PER 
	WHERE 
		IMH.NUMAHA = :CODMAHA AND 
		PES.NUPESQ IN (SELECT DISTINCT NUPESQ FROM TCSPOS POS WHERE POS.NUMOS = :NUMOS) AND 
		PES.CODQUEST = PER.CODQUEST AND 
		IMH.CODPERG = PER.CODPERG AND 
		IMH.CODPERG = RES.CODPERG AND 
		RES.SEQAGRUPA = 2 AND 
		RES.ATIVO = 'S' 
) X WHERE NOT EXISTS (SELECT 1 FROM TPQRPE R WHERE R.NUPESQ = X.NUPESQ AND R.CODPERG = X.CODPERG AND R.CODRESP = X.CODRESP) 