SELECT 
	PES.NUPESQ, 
	RES.CODPERG, 
	RES.CODRESP, 
	DPD.CODPERGMESTRE, 
	DPD.CODRESPMESTRE 
FROM 
	AD_TPQIMH IMH, 
	TPQPES PES, 
	TPQRES RES, 
	TPQPER PER 
		LEFT JOIN TPQDPD DPD ON (
		    PER.CODPERG = DPD.CODPERGDEP AND 
		    --Consideramos apenas respostas do agrupamento 1 (Sim ou Nao)
		    EXISTS(SELECT 1 FROM TPQRES RES2 WHERE RES2.CODPERG = DPD.CODPERGMESTRE AND RES2.CODRESP = DPD.CODRESPMESTRE AND RES2.SEQAGRUPA = 1)
		)  
WHERE 
	IMH.NUMAHA = :CODMAHA AND 
	PES.NUPESQ IN (SELECT DISTINCT NUPESQ FROM TCSPOS POS WHERE POS.NUMOS = :NUMOS) AND 
	PES.CODQUEST = PER.CODQUEST AND 
	IMH.CODPERG = PER.CODPERG AND 
	IMH.CODPERG = RES.CODPERG AND 
	RES.DESCRRESP = :RESPOSTA AND 
	RES.ATIVO = 'S'  