SELECT 
PAR.CODPARC,
PAR.NOMEPARC
FROM TGFFIN FIN,TGFPAR PAR 
WHERE 
FIN.CODPARC = PAR.CODPARC
AND FIN.RECDESP = -1
AND FIN.DHBAIXA is null
AND FIN.PROVISAO='N'
AND FIN.NUMNOTA IS NOT NULL
AND FIN.NUMNOTA = :NUMNOTA
AND EXISTS (
	SELECT 1 FROM TGFFIN FINCLI, TGFFRE FRE WHERE 
		FRE.NUACERTO = FINCLI.NUMNOTA AND
		FINCLI.NUMNOTA = FIN.NUMNOTA AND		
		FINCLI.RECDESP = 1	AND
		FINCLI.CODPARC = :CODPARC AND
    	FRE.TIPACERTO = 'P'     	
)