SELECT 
  MIN(PAR.NOMEPARC) AS NOMEPARC
FROM TGFFIN FIN, TGFPAR PAR 
WHERE
  FIN.CODPARC = PAR.CODPARC 
  AND FIN.RECDESP = 1   
  AND FIN.PROVISAO = 'N'
  AND FIN.NUMNOTA = :NUMNOTA
  AND EXISTS (
		SELECT 1 FROM TGFFIN FINLOJ, TGFFRE FRE WHERE 
		FRE.NUFIN = FINLOJ.NUFIN AND
		FINLOJ.DTNEG = FIN.DTNEG AND
		FINLOJ.NUMNOTA = FIN.NUMNOTA AND
		FINLOJ.CODPARC = :CODPARC AND
		FINLOJ.RECDESP = -1	AND
    	FRE.TIPACERTO = 'P'
	)