SELECT 
FIN.DTVENC,
FIN.NUMCONTRATO,
FIN.NUMNOTA,
PAR.NOMEPARC,
FIN.VLRDESDOB,
FIN.DESDOBRAMENTO,
FIN.DTNEG
FROM 
TGFFIN FIN, 
TGFPAR PAR 
WHERE 
FIN.CODPARC = PAR.CODPARC 
AND  FIN.RECDESP = -1   
AND  TRUNC(FIN.DTVENC) BETWEEN :DTINI AND :DTFIN  
--AND PAR.TARE ='S'  
AND FIN.PROVISAO='N'
AND FIN.CODPARC = :CODPARC
AND FIN.NUMNOTA IS NOT NULL
AND EXISTS (
	SELECT 1 FROM TGFFRE FRE WHERE 
		FRE.NUFIN = FIN.NUFIN AND						
    	FRE.TIPACERTO = 'P'
	)
--FILTRO_TOP
ORDER BY FIN.DTNEG, FIN.DESDOBRAMENTO
