SELECT 
SUM(FIN.VLRDESDOB) AS VLRDESDOB
FROM TGFFIN FIN
, TSIBCO BCOF
, TGFPAR PAR
WHERE 
FIN.CODBCO = BCOF.CODBCO AND 
FIN.CODPARC = PAR.CODPARC AND
FIN.RECDESP = 1   AND 
FIN.DHBAIXA IS NULL  AND 
FIN.PROVISAO='N' AND
FIN.CODPARC = :CODPARC AND
FIN.NUMNOTA IS NOT NULL
ORDER BY FIN.DTVENC, FIN.NUMNOTA, FIN.DESDOBRAMENTO