SELECT 
FIN.DTNEG,
FIN.HISTORICO,
FIN.NUMCONTRATO,
FIN.NUMNOTA,
PAR.NOMEPARC,
SUM(FIN.VLRDESDOB) AS VLRDESDOB
FROM TGFFIN FIN, TGFPAR PAR,TGFPAR PAR2
WHERE
PAR2.CODPARC = :CODPARC 
AND FIN.CODBCO = PAR2.CODBCO 
AND FIN.CODPARC = PAR.CODPARC 
AND  FIN.RECDESP = 1   
AND  TRUNC(FIN.DTNEG) BETWEEN :DTINI AND :DTFIN  
AND FIN.NUMNOTA IS NOT NULL
AND EXISTS (
		SELECT 1 FROM TGFFIN FINLOJ, TGFFRE FRE WHERE 
		FRE.NUACERTO = FINLOJ.NUMNOTA AND
		FINLOJ.NUMNOTA = FIN.NUMNOTA AND
		FINLOJ.CODPARC = :CODPARC AND
		FINLOJ.RECDESP = -1	AND
    	FRE.TIPACERTO = 'P'
	)
--FILTRO_TOP
GROUP BY
FIN.DTNEG,
FIN.HISTORICO,
FIN.NUMNOTA,
FIN.NUMCONTRATO,
FIN.CODPARC,
PAR.NOMEPARC
ORDER BY FIN.DTNEG
