SELECT COMPRA.CODCID,
	   COMPRA.NOMEPARC,
       COMPRA.SEGMENTO, 
       COMPRA.ENDERECO,
       COMPRA.TELEFONE,
       CIDADE.NOMECID
  FROM TGFCOMP COMPRA,
       TSICID CIDADE  
 WHERE COMPRA.CODCID = CIDADE.CODCID
   AND UPPER(CIDADE.NOMECID) LIKE ''|| UPPER(:DESCRICAO) || '%' ORDER by CIDADE.NOMECID, COMPRA.SEGMENTO, COMPRA.NOMEPARC
  