WITH base_bal AS (
    SELECT CTACTB,
           SUM(CASE WHEN YEAR(REFERENCIA) = YEAR(DATE(:VAR_DATA_REF_DRE))
                    THEN VLRLANC ELSE 0 END) AS soma_ate_atu,
           SUM(CASE WHEN YEAR(REFERENCIA) = YEAR(DATE_SUB(DATE(:VAR_DATA_REF_DRE), INTERVAL 1 YEAR))
                    THEN VLRLANC ELSE 0 END) AS soma_ate_ant
    FROM IMP_BASE_BALANCETE
    WHERE CODEMP = :VAR_EMPRESA_DRE
      AND (CTACTB LIKE '3%' OR CTACTB LIKE '4%' OR CTACTB LIKE '5%')
      AND (YEAR(REFERENCIA) = YEAR(DATE(:VAR_DATA_REF_DRE))
        OR YEAR(REFERENCIA) = YEAR(DATE_SUB(DATE(:VAR_DATA_REF_DRE), INTERVAL 1 YEAR)))
    GROUP BY CTACTB
)
SELECT A.ORDEM AS HIERARQUIA, A.NOME_GRUPO AS DESCRICAO, A.COD_NOTA_EXPLICATIVA AS NOTA,
       SUM(CASE WHEN R.REFERENCIA = DATE(:VAR_DATA_REF_DRE)
                THEN IFNULL(B.soma_ate_atu, 0) * C.SINAL ELSE 0 END) AS VALOR_ANO_ATUAL,
       SUM(CASE WHEN R.REFERENCIA = DATE_SUB(DATE(:VAR_DATA_REF_DRE), INTERVAL 1 YEAR)
                THEN IFNULL(B.soma_ate_ant, 0) * C.SINAL ELSE 0 END) AS VALOR_ANO_ANTERIOR
FROM DET_DEMONSTRATIVO A
INNER JOIN ESTR_DEMONSTRATIVOS E ON E.ID = A.ID_ESTR_DEMONSTRATIVO
LEFT JOIN DET_DEMONSTRATIVO_REFERENCIA R ON R.ID_DET_DEMONSTRATIVO = A.ID AND R.REFERENCIA IN (DATE(:VAR_DATA_REF_DRE), DATE_SUB(DATE(:VAR_DATA_REF_DRE), INTERVAL 1 YEAR))
LEFT JOIN DET_DEMONSTRATIVO_CTACTB C ON C.ID_DET_DEMONSTRATIVO_REFERENCIA = R.ID
LEFT JOIN base_bal B ON B.CTACTB = C.PADRAO_CTACTB
WHERE E.ID = 3
GROUP BY A.ORDEM, A.NOME_GRUPO, A.COD_NOTA_EXPLICATIVA
ORDER BY A.ORDEM
