WITH base_bal AS (
    SELECT CTACTB,
           SUM(CASE WHEN REFERENCIA < DATE_ADD(LAST_DAY(DATE(:VAR_DATA_REF_DRE)), INTERVAL 1 DAY)
                    THEN VLRLANC ELSE 0 END) AS soma_ate_atu,
           SUM(CASE WHEN REFERENCIA < DATE_ADD(LAST_DAY(DATE_SUB(DATE(:VAR_DATA_REF_DRE), INTERVAL 1 YEAR)), INTERVAL 1 DAY)
                    THEN VLRLANC ELSE 0 END) AS soma_ate_ant
    FROM IMP_BASE_BALANCETE
    WHERE CODEMP = :VAR_EMPRESA_DRE
      AND REFERENCIA < DATE_ADD(LAST_DAY(DATE(:VAR_DATA_REF_DRE)), INTERVAL 1 DAY)
    GROUP BY CTACTB
),
valores_agrupados AS (
    SELECT DET.ORDEM,
           SUM(CASE WHEN DETREF.REFERENCIA = DATE(:VAR_DATA_REF_DRE)
                    THEN IFNULL(B.soma_ate_atu, 0) * DETCTACTB.SINAL ELSE 0 END) AS VLRLANC_ATU,
           SUM(CASE WHEN DETREF.REFERENCIA = DATE_SUB(DATE(:VAR_DATA_REF_DRE), INTERVAL 1 YEAR)
                    THEN IFNULL(B.soma_ate_ant, 0) * DETCTACTB.SINAL ELSE 0 END) AS VLRLANC_ANT
    FROM ESTR_DEMONSTRATIVOS EST
    INNER JOIN DET_DEMONSTRATIVO DET ON EST.ID = DET.ID_ESTR_DEMONSTRATIVO
    INNER JOIN DET_DEMONSTRATIVO_REFERENCIA DETREF ON DET.ID = DETREF.ID_DET_DEMONSTRATIVO AND DETREF.REFERENCIA IN (DATE(:VAR_DATA_REF_DRE), DATE_SUB(DATE(:VAR_DATA_REF_DRE), INTERVAL 1 YEAR))
    LEFT JOIN DET_DEMONSTRATIVO_CTACTB DETCTACTB ON DETREF.ID = DETCTACTB.ID_DET_DEMONSTRATIVO_REFERENCIA
    LEFT JOIN base_bal B ON B.CTACTB = DETCTACTB.PADRAO_CTACTB
    WHERE EST.ID = 1
    GROUP BY DET.ORDEM
)
SELECT SUM(CASE WHEN ORDEM LIKE '1.1.%' THEN VLRLANC_ATU ELSE 0 END) AS AC_ATU,
       SUM(CASE WHEN ORDEM LIKE '2.1.%' THEN VLRLANC_ATU ELSE 0 END) AS PC_ATU,
       SUM(CASE WHEN ORDEM = '1.1.3' THEN VLRLANC_ATU ELSE 0 END) AS ESTOQUE_ATU,
       SUM(CASE WHEN ORDEM = '1.2.1' THEN VLRLANC_ATU ELSE 0 END) AS RLP_ATU,
       SUM(CASE WHEN ORDEM LIKE '2.2.%' THEN VLRLANC_ATU ELSE 0 END) AS PNC_ATU,
       SUM(CASE WHEN ORDEM LIKE '1.%' THEN VLRLANC_ATU ELSE 0 END) AS ATIVO_TOTAL_ATU,
       SUM(CASE WHEN ORDEM LIKE '1.1.%' THEN VLRLANC_ANT ELSE 0 END) AS AC_ANT,
       SUM(CASE WHEN ORDEM LIKE '2.1.%' THEN VLRLANC_ANT ELSE 0 END) AS PC_ANT,
       SUM(CASE WHEN ORDEM = '1.1.3' THEN VLRLANC_ANT ELSE 0 END) AS ESTOQUE_ANT,
       SUM(CASE WHEN ORDEM = '1.2.1' THEN VLRLANC_ANT ELSE 0 END) AS RLP_ANT,
       SUM(CASE WHEN ORDEM LIKE '2.2.%' THEN VLRLANC_ANT ELSE 0 END) AS PNC_ANT,
       SUM(CASE WHEN ORDEM LIKE '1.%' THEN VLRLANC_ANT ELSE 0 END) AS ATIVO_TOTAL_ANT
FROM valores_agrupados
