WITH base_bal AS (
    SELECT CTACTB,
           SUM(CASE WHEN YEAR(REFERENCIA) = YEAR(DATE(:VAR_DATA_REF_DRE)) THEN VLRLANC ELSE 0 END) AS mov_atu,
           SUM(CASE WHEN YEAR(REFERENCIA) = YEAR(DATE_SUB(DATE(:VAR_DATA_REF_DRE), INTERVAL 1 YEAR)) THEN VLRLANC ELSE 0 END) AS mov_ant,
           SUM(CASE WHEN YEAR(REFERENCIA) = YEAR(DATE_SUB(DATE(:VAR_DATA_REF_DRE), INTERVAL 2 YEAR)) THEN VLRLANC ELSE 0 END) AS mov_ant2,
           SUM(CASE WHEN YEAR(REFERENCIA) <= YEAR(DATE(:VAR_DATA_REF_DRE)) THEN VLRLANC ELSE 0 END) AS acum_atu,
           SUM(CASE WHEN YEAR(REFERENCIA) <= YEAR(DATE_SUB(DATE(:VAR_DATA_REF_DRE), INTERVAL 1 YEAR)) THEN VLRLANC ELSE 0 END) AS acum_ant,
           SUM(CASE WHEN YEAR(REFERENCIA) <= YEAR(DATE_SUB(DATE(:VAR_DATA_REF_DRE), INTERVAL 2 YEAR)) THEN VLRLANC ELSE 0 END) AS acum_ant2
    FROM IMP_BASE_BALANCETE
    WHERE CODEMP = :VAR_EMPRESA_DRE
      AND YEAR(REFERENCIA) <= YEAR(DATE(:VAR_DATA_REF_DRE))
    GROUP BY CTACTB
),
base_valores AS (
    SELECT DET.ORDEM,
           SUM(IFNULL(B.mov_atu,0)   * DETCTACTB.SINAL) AS mov_atual,
           SUM(IFNULL(B.mov_ant,0)   * DETCTACTB.SINAL) AS mov_anterior,
           SUM(IFNULL(B.mov_ant2,0)  * DETCTACTB.SINAL) AS mov_anterior2,
           SUM(IFNULL(B.acum_atu,0)  * DETCTACTB.SINAL) AS acum_atual,
           SUM(IFNULL(B.acum_ant,0)  * DETCTACTB.SINAL) AS acum_anterior,
           SUM(IFNULL(B.acum_ant2,0) * DETCTACTB.SINAL) AS acum_anterior2
    FROM ESTR_DEMONSTRATIVOS EST
    INNER JOIN DET_DEMONSTRATIVO DET ON EST.ID = DET.ID_ESTR_DEMONSTRATIVO
    INNER JOIN DET_DEMONSTRATIVO_REFERENCIA DETREF ON DET.ID = DETREF.ID_DET_DEMONSTRATIVO AND DETREF.REFERENCIA = DATE(:VAR_DATA_REF_DRE)
    LEFT JOIN DET_DEMONSTRATIVO_CTACTB DETCTACTB ON DETREF.ID = DETCTACTB.ID_DET_DEMONSTRATIVO_REFERENCIA
    LEFT JOIN base_bal B ON B.CTACTB = DETCTACTB.PADRAO_CTACTB
    WHERE EST.ID = 11
    GROUP BY DET.ORDEM
)
SELECT BV.ORDEM,
       CASE WHEN BV.ORDEM IN ('1','5') THEN BV.acum_atual     ELSE BV.mov_atual     END / 1000 AS ANO_ATUAL,
       CASE WHEN BV.ORDEM IN ('1','5') THEN BV.acum_anterior  ELSE BV.mov_anterior  END / 1000 AS ANO_ANT,
       CASE WHEN BV.ORDEM IN ('1','5') THEN BV.acum_anterior2 ELSE BV.mov_anterior2 END / 1000 AS ANO_BASE
FROM base_valores BV
ORDER BY BV.ORDEM
